// This file is generated by scripts/generate-portal-sitemap.mjs.
// Do not edit it manually. It is refreshed before dev, typecheck, and build.

export type GeneratedPortalAudience =
  | "public"
  | "customer"
  | "partner"
  | "admin";

export type GeneratedAppPage = {
  route: string;
  audience: GeneratedPortalAudience;
  dynamic: boolean;
  sourcePath: string;
};

export const GENERATED_APP_PAGES = [
  {
    "route": "/",
    "audience": "public",
    "dynamic": false,
    "sourcePath": "app/page.tsx"
  },
  {
    "route": "/admin",
    "audience": "admin",
    "dynamic": false,
    "sourcePath": "app/admin/page.tsx"
  },
  {
    "route": "/admin/globals/[documentKey]",
    "audience": "admin",
    "dynamic": true,
    "sourcePath": "app/admin/globals/[documentKey]/page.tsx"
  },
  {
    "route": "/admin/login",
    "audience": "admin",
    "dynamic": false,
    "sourcePath": "app/admin/login/page.tsx"
  },
  {
    "route": "/admin/operations",
    "audience": "admin",
    "dynamic": false,
    "sourcePath": "app/admin/operations/page.tsx"
  },
  {
    "route": "/admin/pages/[pageKey]",
    "audience": "admin",
    "dynamic": true,
    "sourcePath": "app/admin/pages/[pageKey]/page.tsx"
  },
  {
    "route": "/admin/test-data",
    "audience": "admin",
    "dynamic": false,
    "sourcePath": "app/admin/test-data/page.tsx"
  },
  {
    "route": "/consult",
    "audience": "public",
    "dynamic": false,
    "sourcePath": "app/consult/page.tsx"
  },
  {
    "route": "/events/audit-quote",
    "audience": "public",
    "dynamic": false,
    "sourcePath": "app/events/audit-quote/page.tsx"
  },
  {
    "route": "/events/audit-quote/evaluate",
    "audience": "public",
    "dynamic": false,
    "sourcePath": "app/events/audit-quote/evaluate/page.tsx"
  },
  {
    "route": "/events/audit-quote/evaluations/[caseId]",
    "audience": "public",
    "dynamic": true,
    "sourcePath": "app/events/audit-quote/evaluations/[caseId]/page.tsx"
  },
  {
    "route": "/events/audit-quote/evaluations/[caseId]/report",
    "audience": "public",
    "dynamic": true,
    "sourcePath": "app/events/audit-quote/evaluations/[caseId]/report/page.tsx"
  },
  {
    "route": "/events/audit-quote/evaluations/[caseId]/review",
    "audience": "public",
    "dynamic": true,
    "sourcePath": "app/events/audit-quote/evaluations/[caseId]/review/page.tsx"
  },
  {
    "route": "/events/audit-quote/guide",
    "audience": "public",
    "dynamic": false,
    "sourcePath": "app/events/audit-quote/guide/page.tsx"
  },
  {
    "route": "/faq",
    "audience": "public",
    "dynamic": false,
    "sourcePath": "app/faq/page.tsx"
  },
  {
    "route": "/inquiries",
    "audience": "public",
    "dynamic": false,
    "sourcePath": "app/inquiries/page.tsx"
  },
  {
    "route": "/login",
    "audience": "public",
    "dynamic": false,
    "sourcePath": "app/login/page.tsx"
  },
  {
    "route": "/mypage",
    "audience": "customer",
    "dynamic": false,
    "sourcePath": "app/mypage/page.tsx"
  },
  {
    "route": "/mypage/quotes",
    "audience": "customer",
    "dynamic": false,
    "sourcePath": "app/mypage/quotes/page.tsx"
  },
  {
    "route": "/mypage/quotes/[quoteId]",
    "audience": "customer",
    "dynamic": true,
    "sourcePath": "app/mypage/quotes/[quoteId]/page.tsx"
  },
  {
    "route": "/mypage/requests/[requestId]",
    "audience": "customer",
    "dynamic": true,
    "sourcePath": "app/mypage/requests/[requestId]/page.tsx"
  },
  {
    "route": "/partner",
    "audience": "partner",
    "dynamic": false,
    "sourcePath": "app/partner/page.tsx"
  },
  {
    "route": "/partner/apply",
    "audience": "public",
    "dynamic": false,
    "sourcePath": "app/partner/apply/page.tsx"
  },
  {
    "route": "/partner/login",
    "audience": "partner",
    "dynamic": false,
    "sourcePath": "app/partner/login/page.tsx"
  },
  {
    "route": "/pending-approval",
    "audience": "public",
    "dynamic": false,
    "sourcePath": "app/pending-approval/page.tsx"
  },
  {
    "route": "/portal-access-denied",
    "audience": "public",
    "dynamic": false,
    "sourcePath": "app/portal-access-denied/page.tsx"
  },
  {
    "route": "/privacy",
    "audience": "public",
    "dynamic": false,
    "sourcePath": "app/privacy/page.tsx"
  },
  {
    "route": "/signup",
    "audience": "public",
    "dynamic": false,
    "sourcePath": "app/signup/page.tsx"
  },
  {
    "route": "/support",
    "audience": "public",
    "dynamic": false,
    "sourcePath": "app/support/page.tsx"
  },
  {
    "route": "/terms",
    "audience": "public",
    "dynamic": false,
    "sourcePath": "app/terms/page.tsx"
  }
] as const satisfies readonly GeneratedAppPage[];
