import type { CmsAdminOverview } from "@/lib/cms/admin-console-types";

export const ADMIN_CONSOLE_PREVIEW_OVERVIEW: CmsAdminOverview = {
  generatedAt: "2026-07-20T09:30:00.000Z",
  counts: {
    editablePages: 17,
    unpublishedDrafts: 3,
    recentlyModified: 5,
    recentlyPublished: 2,
    reviewRequired: 1,
  },
  pages: [
    {
      id: "home",
      name: "홈",
      description: "센터 소개, 지원 분야, 상담 절차와 주요 안내",
      url: "/",
      previewUrl: "/",
      audience: "public",
      audienceLabel: "전체 공개",
      category: "public",
      categoryLabel: "공개 화면",
      status: "draft",
      statusLabel: "게시 전 변경 있음",
      hasUnpublishedChanges: true,
      draftVersion: 4,
      publishedVersion: 3,
      modifiedBy: "김콘텐츠",
      modifiedAt: "2026-07-20T08:42:00.000Z",
      publishedAt: "2026-07-18T02:10:00.000Z",
      sections: [
        {
          name: "첫 화면",
          visible: true,
          protected: true,
          itemCount: 4,
        },
        {
          name: "지원 분야",
          visible: true,
          protected: false,
          itemCount: 8,
        },
      ],
    },
    {
      id: "public.consult",
      name: "상담 신청",
      description: "상담 분야와 문의 작성 안내",
      url: "/consult",
      previewUrl: "/consult",
      audience: "member",
      audienceLabel: "로그인 회원",
      category: "public",
      categoryLabel: "상담 서비스",
      status: "published",
      statusLabel: "게시됨",
      hasUnpublishedChanges: false,
      draftVersion: 2,
      publishedVersion: 2,
      modifiedBy: "박운영",
      modifiedAt: "2026-07-19T05:20:00.000Z",
      publishedAt: "2026-07-19T05:20:00.000Z",
      sections: [
        {
          name: "상담 진행 순서",
          visible: true,
          protected: true,
          itemCount: 3,
        },
        {
          name: "문의 유형 선택",
          visible: true,
          protected: true,
          itemCount: 10,
        },
      ],
    },
    {
      id: "admin.operations",
      name: "회원·상담 운영",
      description: "회원 승인, 상담, 포인트와 운영 업무의 표시 안내",
      url: "/admin/operations",
      previewUrl: "/admin/operations",
      audience: "admin",
      audienceLabel: "관리자",
      category: "admin",
      categoryLabel: "관리자 화면",
      status: "needsReview",
      statusLabel: "확인 필요",
      hasUnpublishedChanges: true,
      draftVersion: 7,
      publishedVersion: 6,
      modifiedBy: "이관리",
      modifiedAt: "2026-07-20T07:15:00.000Z",
      publishedAt: "2026-07-17T04:00:00.000Z",
      sections: [
        {
          name: "운영 업무 메뉴",
          visible: true,
          protected: true,
          itemCount: 6,
        },
      ],
    },
  ],
  commonAreas: [
    {
      id: "header",
      name: "상단 메뉴",
      description: "주요 메뉴와 로그인·상담 버튼을 관리합니다.",
      affectedArea: "공개 화면 상단",
      status: "draft",
      statusLabel: "게시 전 변경 있음",
      hasUnpublishedChanges: true,
      modifiedBy: "김콘텐츠",
      modifiedAt: "2026-07-20T06:40:00.000Z",
    },
    {
      id: "footer",
      name: "하단 정보",
      description: "운영 주체, 안내 문구와 정책 링크를 관리합니다.",
      affectedArea: "공개 화면 하단",
      status: "published",
      statusLabel: "게시됨",
      hasUnpublishedChanges: false,
      modifiedBy: "박운영",
      modifiedAt: "2026-07-18T03:30:00.000Z",
    },
  ],
  design: {
    palette: "default",
    paletteLabel: "기본 파랑",
    textScale: "default",
    textScaleLabel: "기본",
    spacing: "default",
    spacingLabel: "기본",
    radius: "rounded",
    radiusLabel: "둥글게",
    alignment: "left",
    alignmentLabel: "왼쪽 정렬",
    sourceLabel: "게시 전 설정",
  },
  assets: [
    {
      id: "preview-guide",
      name: "상담 안내서.pdf",
      kind: "PDF 문서",
      sizeLabel: "1.8 MB",
      alt: "농협지원센터 상담 이용 안내서",
      statusLabel: "사용 중",
      updatedAt: "2026-07-19T03:00:00.000Z",
      updatedBy: "박운영",
    },
  ],
  recentChanges: [
    {
      id: "preview-change-1",
      action: "초안을 수정했습니다.",
      target: "홈",
      actor: "김콘텐츠",
      createdAt: "2026-07-20T08:42:00.000Z",
      tone: "blue",
      published: false,
    },
    {
      id: "preview-change-2",
      action: "이전 내용을 초안으로 복원했습니다.",
      target: "상단 메뉴",
      actor: "이관리",
      createdAt: "2026-07-20T06:40:00.000Z",
      tone: "amber",
      published: false,
    },
  ],
  recentPublishes: [
    {
      id: "preview-publish-1",
      action: "게시했습니다.",
      target: "상담 신청",
      actor: "박운영",
      createdAt: "2026-07-19T05:20:00.000Z",
      tone: "green",
      published: true,
    },
  ],
  issues: [
    {
      id: "preview-issue-1",
      severity: "warning",
      title: "회원·상담 운영 초안이 이전 게시본을 기준으로 합니다.",
      description: "다른 관리자의 게시 내용을 확인한 뒤 편집을 계속해 주세요.",
      targetMenu: "pages",
    },
  ],
};
