import {
  CMS_GLOBAL_KEYS,
  CMS_PAGE_KEYS,
  CMS_PAGE_ROUTES,
  type CmsGlobalKey,
  type CmsPageKey,
} from "@/lib/cms/constants";
import {
  cmsGlobalContentSchema,
  cmsPageContentSchema,
  type CmsGlobalContent,
  type CmsContentGroup,
  type CmsLink,
  type CmsPageContent,
  type CmsSection,
} from "@/lib/cms/schemas";
import { DEFAULT_PUBLIC_FAQS } from "@/lib/default-faqs";

type SectionInput = Omit<
  CmsSection,
  "visible" | "locked" | "headingLevel" | "text" | "items" | "actions" | "groups" | "style"
> & {
  visible?: boolean;
  locked?: boolean;
  headingLevel?: CmsSection["headingLevel"];
  text?: CmsSection["text"];
  items?: CmsSection["items"];
  actions?: CmsLink[];
  groups?: CmsSection["groups"];
  style?: CmsSection["style"];
};

const action = (
  id: string,
  label: string,
  href: string,
  appearance: CmsLink["appearance"] = "primary",
): CmsLink => ({
  id,
  label,
  href,
  linkType: "internal",
  appearance,
  openInNewWindow: false,
});

const section = (input: SectionInput): CmsSection => ({
  visible: true,
  locked: false,
  headingLevel: 2,
  text: {},
  items: [],
  actions: [],
  groups: [],
  style: {
    title: {
      fontFamily: "pretendard",
      sizePreset: "default",
      fontWeight: "700",
      lineHeightPreset: "default",
      alignment: "left",
      color: "text",
    },
    body: {
      fontFamily: "pretendard",
      sizePreset: "default",
      fontWeight: "400",
      lineHeightPreset: "default",
      alignment: "left",
      color: "muted",
    },
    container: {
      background: "surface",
      spacing: "default",
      border: "none",
      radius: "default",
      shadow: "none",
    },
  },
  ...input,
});

const item = (
  id: string,
  title: string,
  description?: string,
  value?: string,
): CmsSection["items"][number] => ({
  id,
  title,
  description,
  value,
  visible: true,
  deleted: false,
});

const group = (
  id: string,
  input: Omit<CmsContentGroup, "id" | "visible" | "items" | "actions"> & {
    visible?: boolean;
    items?: CmsContentGroup["items"];
    actions?: CmsContentGroup["actions"];
  } = {},
): CmsContentGroup => ({
  id,
  visible: true,
  items: [],
  actions: [],
  ...input,
});

const page = (
  title: string,
  description: string,
  sections: CmsSection[],
  messages: CmsPageContent["messages"] = {},
): CmsPageContent => ({
  seo: { title, description, indexable: true },
  sections,
  messages,
});

export const CMS_PAGE_DEFAULTS: Record<CmsPageKey, CmsPageContent> = {
  home: page(
    "농협지원센터 · 주식회사 프리고",
    "농협 대상 상담 접수·분류·전문가 연결 플랫폼. 세무·노무·감사·회계 일반 문의를 안전하게 분류하고 필요한 전문가에게 연결합니다.",
    [
      section({
        id: "hero",
        eyebrow: "농협에 필요한 모든 전문지식을 가장 쉽게 제공합니다",
        title: "농협 업무의\n복잡한 전문 문의를",
        description:
          "세무, 회계, 법률, 노무 등 모든 전문 문의를\n한 곳에서 시작할 수 있습니다.",
        text: { highlight: "쉽게 풀어갑니다" },
        actions: [
          action("startConsult", "상담·견적 요청하기", "/consult"),
          action("viewServices", "지원분야 보기", "#services", "secondary"),
        ],
        groups: [
          group("serviceSummary", {
            label: "서비스 요약",
            items: [
              item("marketShare", "점유율 1위!", "농협 업무 상담 접수"),
              item("professions", "8대", "모든 8대 전문직 문의 가능"),
              item("experience", "80+", "농협 관련 감사 및 자문 경험"),
              item("oneStop", "원스톱", "상담·견적·전문가 연결"),
            ],
          }),
        ],
      }),
      section({
        id: "about",
        eyebrow: "Center Introduction",
        title: "농협 업무 지원의 새로운 연결 기준을 만듭니다",
        description:
          "농협지원센터는 서울에 집중된 전문가 정보 격차를 해소하기 위해 사업지원서비스 법인 프리고가 설립한, 전국 최초의 농협 전용 지원 조직입니다.",
        text: {
          highlight: "새로운 연결 기준",
          secondaryDescription:
            "농협 업무에 필요한 전문 지원을 보다 편리하게 연결하고, 다양한 전문가 네트워크를 바탕으로 전국 각지의 농협이 고도로 전문화된 지식과 서비스에 폭넓게 접근할 수 있도록 돕습니다.",
        },
        groups: [
          group("introductionSummary", {
            label: "센터 소개 요약",
            items: [
              item("first", "전국 최초", "농협 전용 지원 조직", "1"),
              item("professions", "8대 전문직", "통합 문의·연결 지원", "8"),
              item("oneStop", "원스톱", "상담·견적·업무 연결", "✓"),
            ],
          }),
          group("supportPromise", {
            label: "폭넓게 연결합니다",
            title: "농협에 필요한 전문지식을 더 쉽고 폭넓게 연결합니다",
            description:
              "농협 업무는 여러 전문 분야가 함께 연결되는 경우가 많습니다. 농협지원센터는 다양한 전문가 네트워크를 바탕으로 필요한 지원을 보다 편리하게 시작할 수 있도록 돕습니다.",
            items: [
              item("nationwide", "전국 농협 특성을 고려한 전문 안내"),
              item("network", "8대 분야 전문가 네트워크 직접 연계"),
              item("selection", "업무 목적에 최적화된 전문가 선정"),
              item("oneStop", "상담·견적·업무 연결 원스톱 진행"),
              item("followup", "후속 상담 및 사후 관리 지속 지원"),
            ],
          }),
          group("customerValue", {
            label: "Value",
            title: "농협이 체감하는 가치",
            items: [
              item(
                "expertConnection",
                "전문가 연결",
                "농협 업무에 맞는 전문가를 빠르고 정확하게 연결합니다.",
              ),
              item(
                "singleRequest",
                "통합 문의",
                "여러 분야의 전문 문의를 한 곳에서 효율적으로 진행합니다.",
              ),
              item(
                "estimate",
                "견적 진행",
                "상담 이후 필요한 업무의 견적과 연결 절차까지 함께 진행합니다.",
              ),
              item(
                "followup",
                "후속 지원",
                "추가 상담부터 실제 업무 진행까지 지속적으로 지원합니다.",
              ),
            ],
          }),
        ],
      }),
      section({
        id: "expertise",
        eyebrow: "Expertise",
        title: "농협 업무에 맞춘 전문성",
        description:
          "회계와 감사 문의를 구분하고, 복합 문의는 필요한 전문 영역으로 나누어 상담 또는 견적 절차를 안내합니다.",
        text: { highlight: "전문성" },
        items: [
          item(
            "nhKnowledge",
            "농협 업무 이해",
            "농협·조합 관련 법인의 회계, 감사, 세무, 인사노무, 계약 업무 특성을 고려해 문의를 검토합니다.",
            "NH",
          ),
          item(
            "professionalNetwork",
            "8대 전문직 네트워크",
            "회계사, 세무사, 노무사, 변호사, 법무사, 감정평가사, 변리사, 관세사 등 다양한 전문가와 협업합니다.",
            "8 Fields",
          ),
          item(
            "classification",
            "복합 문의 분류",
            "하나의 문의에 여러 분야가 섞여 있어도 필요한 전문 영역을 구분해 안내합니다.",
            "Classify",
          ),
          item(
            "connection",
            "상담과 견적 연결",
            "필요한 경우 후속 상담, 견적, 정식 업무 진행까지 안내합니다.",
            "Connect",
          ),
        ],
        locked: true,
      }),
      section({
        id: "services",
        eyebrow: "Services",
        title: "농협에 필요한 모든 전문 업무를 한 곳에서 시작하세요",
        description:
          "세무·회계·법률·노무 등 필요한 분야를 골라, 한 번의 요청으로 상담을 시작할 수 있습니다.",
        text: { highlight: "한 곳에서 시작하세요" },
        items: [
          item("tax", "세무", "법인세, 부가가치세, 원천세, 세무대리, 임직원·조합원 세무상담, 재산세제 문의를 접수합니다.", "tax"),
          item("accounting", "회계", "회계처리 일반 문의, 결산자료 정리, 재무자료 이해, 회계 관련 기초 상담을 접수합니다.", "ledger"),
          item("legal", "법률", "계약서 검토, 법률자문, 분쟁 예방, 소송 대리인 소개 등 법률 관련 문의를 연결합니다.", "shield"),
          item("labor", "노무", "급여, 4대보험, 근로계약, 취업규칙, 인사노무 관리 관련 문의를 접수합니다.", "control"),
          item("registration", "등기업무", "법인등기, 임원변경, 정관, 각종 등기 관련 업무를 연결합니다.", "structure"),
          item("valuation", "감정평가", "부동산, 자산, 담보, 출자·거래 관련 평가 문의를 연결합니다.", "valuation"),
          item("ip", "지식재산", "상표, 특허, 브랜드, 지식재산권 관련 문의를 연결합니다.", "feasibility"),
          item("customs", "관세/통관", "수출입, 통관, 관세, FTA 관련 문의를 연결합니다.", "subsidy"),
          item("audit", "감사", "감사 문의, 감사대응, 감사자료 준비, 감사인 선임 방법 검토, 감사 견적 요청을 지원합니다.", "audit"),
        ],
        groups: [
          group("multiFieldRequest", {
            label: "Policy",
            title: "여러 분야가 섞인 문의도 한 번의 요청으로 시작할 수 있습니다",
            actions: [
              action("consult", "상담·견적 요청", "/consult", "text"),
            ],
          }),
        ],
      }),
      section({
        id: "process",
        eyebrow: "농협지원센터",
        title: "고객이 체감하는 질문·답변 경험을 중심으로 안내합니다",
        text: {
          highlight: "질문·답변 경험",
          captionSuffix: "· 상담흐름",
          ariaLabel: "센터의 자세",
        },
        items: [
          { ...item("submit", "문의 등록", "궁금한 업무 분야와 내용을 남기고, 원하는 공개 범위를 선택해 문의를 등록합니다."), label: "STEP 01" },
          { ...item("review", "답변 확인", "게시판이나 마이페이지에서 답변을 확인하고, 필요한 내용을 바로 파악할 수 있습니다."), label: "STEP 02" },
          { ...item("followup", "추가 문의", "답변을 보고도 궁금한 점이 있으면 같은 문의에 추가 질문을 이어갈 수 있습니다."), label: "STEP 03" },
          { ...item("connection", "전문가 연결", "정식 업무가 필요하면 추가상담·견적진행을 요청해 전문가와 연결할 수 있습니다."), label: "STEP 04" },
        ],
      }),
      section({
        id: "caseStudies",
        eyebrow: "상담사례",
        title: "궁금한 문의, 게시판에서 바로 확인하세요",
        description:
          "비슷한 업무 사례를 먼저 살펴보고, 필요한 상담은 원하는 공개 범위를 선택해 편하게 남길 수 있습니다.",
        text: { highlight: "게시판에서 바로" },
        actions: [
          action("inquiries", "문의 게시판 보기", "/inquiries"),
        ],
        items: [
          { ...item("public", "다른 농협 사례도 함께 참고", "비슷한 업무 고민을 먼저 찾아보고, 필요할 때 바로 문의를 이어갈 수 있습니다."), label: "전체공개" },
          { ...item("organization", "우리 농협 안에서만 공유", "같은 농협 구성원만 본문과 답변을 볼 수 있어, 내부 업무 상담에 적합합니다."), label: "우리농협공개" },
          { ...item("private", "나만 확인하는 비공개 문의", "민감한 내용은 작성자와 담당자만 확인할 수 있도록 안전하게 관리합니다."), label: "비공개" },
        ],
      }),
      section({
        id: "faqPreview",
        eyebrow: "FAQ",
        title: "자주 받는 질문",
        text: { highlight: "질문", listTitle: "FAQ 목록" },
        actions: [action("viewAll", "전체보기", "/faq", "text")],
        items: DEFAULT_PUBLIC_FAQS.map((faq) => ({
          id: faq.id.replaceAll("-", "_"),
          label: faq.category,
          title: faq.question,
          description: faq.answer,
          visible: true,
          deleted: false,
        })),
      }),
    ],
    {
      loading: "FAQ를 불러오는 중입니다.",
      error:
        "운영자가 등록한 FAQ가 준비 중입니다. 아래는 기본 안내입니다.",
    },
  ),
  "auth.login": page(
    "로그인 · 농협지원센터",
    "농협지원센터 상담·견적 요청은 회원 로그인 후 이용할 수 있습니다.",
    [
      section({
        id: "hero",
        eyebrow: "Members only",
        title: "상담·견적 요청은\n회원 로그인 후 이용합니다",
        description:
          "아직 계정이 없다면 회원가입 신청을 통해 소속 농협을 검증해 주세요.",
        text: { highlight: "회원 로그인 후" },
      }),
      section({
        id: "loginForm",
        eyebrow: "로그인",
        title: "계정으로 로그인",
        description:
          "가입한 이메일과 비밀번호를 입력해 상담 내역과 마이페이지를 확인하세요.",
        text: {
          emailLabel: "이메일",
          emailPlaceholder: "example@email.com",
          passwordLabel: "비밀번호",
          passwordPlaceholder: "비밀번호를 입력하세요",
          showPasswordLabel: "비밀번호 보기",
          hidePasswordLabel: "비밀번호 숨기기",
          showLabel: "보기",
          hideLabel: "숨김",
          autoLoginLabel: "자동 로그인",
          signupLabel: "회원가입",
          submitLabel: "로그인",
          submittingLabel: "로그인 중...",
          hint: "가입한 농협 이메일 계정으로 로그인해 주세요.",
        },
        actions: [action("signup", "회원가입", "/signup", "text")],
      }),
      section({
        id: "recovery",
        title: "계정 정보를 잊으셨나요?",
        text: {
          ariaLabel: "계정 찾기",
          findEmailLabel: "아이디 찾기",
          resetPasswordLabel: "비밀번호 찾기",
          nameLabel: "이름",
          namePlaceholder: "가입자 이름",
          phoneLabel: "휴대폰 번호",
          phonePlaceholder: "010-0000-0000",
          findSubmitLabel: "아이디 확인",
          findingLabel: "확인 중...",
          resetEmailLabel: "가입 이메일",
          resetEmailPlaceholder: "example@email.com",
          resetSubmitLabel: "재설정 메일 발송",
          resettingLabel: "발송 중...",
        },
      }),
    ],
    {
      loading: "로그인하고 있습니다.",
      emailRequired: "이메일을 입력해 주세요.",
      passwordRequired: "비밀번호를 입력해 주세요.",
      invalidCredentials: "이메일 또는 비밀번호를 확인해 주세요.",
      tooManyRequests:
        "로그인 시도가 너무 많습니다. 잠시 후 다시 시도해 주세요.",
      networkError: "네트워크 연결을 확인한 뒤 다시 시도해 주세요.",
      findNameRequired: "이름을 입력해 주세요.",
      findPhoneRequired: "휴대폰 번호를 입력해 주세요.",
      findInvalidPhone:
        "휴대폰 번호는 010-0000-0000 형식으로 입력해 주세요.",
      findNotFound: "일치하는 가입 정보를 찾지 못했습니다.",
      findSuccessPrefix: "가입 이메일은",
      findSuccessSuffix: "입니다.",
      resetSuccess:
        "비밀번호 재설정 메일을 발송했습니다. 메일함을 확인해 주세요.",
      resetInvalidEmail: "이메일 형식이 올바르지 않습니다.",
      resetFailed: "비밀번호 재설정 메일 발송에 실패했습니다.",
      genericError: "로그인 중 문제가 발생했습니다. 잠시 후 다시 시도해 주세요.",
    },
  ),
  "auth.signup": page(
    "회원가입 · 농협지원센터",
    "농협 선택, 사용자 인증, 소속 검증 요청을 진행합니다.",
    [
      section({
        id: "hero",
        title: "회원가입",
        description: "소속 농협을 인증하고 우리 농협 포인트 지갑을 사용해 보세요.",
        text: { progressAriaLabel: "회원가입 단계" },
        items: [
          item("identity", "기본 정보"),
          item("organization", "소속 농협"),
          item("work", "담당자"),
          item("consents", "약관 동의"),
        ],
      }),
      section({
        id: "identity",
        title: "기본 정보 입력",
        text: {
          nameLabel: "이름",
          namePlaceholder: "이름을 입력하세요",
          phoneLabel: "휴대폰 번호",
          phonePlaceholder: "010-0000-0000",
          verifiedNotice: "인증이 완료되었습니다. 인증은 30분간 유지됩니다",
          verificationCodePlaceholder: "인증번호 6자리",
          verifyCodeLabel: "인증 확인",
          sendingLabel: "발송 중...",
          resendLabel: "인증번호 재발송",
          sendLabel: "인증번호 받기",
          phoneLimitHelp:
            "동일한 휴대폰 번호로는 최대 2개 계정까지만 가입할 수 있습니다.",
          codeSentHelp:
            "입력하신 번호로 인증번호가 발송되었어요. 받은 6자리 숫자를 입력해 주세요.",
          emailLabel: "농협 이메일",
          emailPlaceholder: "example@email.com",
          checkingEmailLabel: "확인 중...",
          checkEmailLabel: "중복확인",
          emailAvailable: "사용 가능한 이메일입니다.",
          passwordLabel: "비밀번호",
          passwordPlaceholder: "8자 이상 입력하세요",
          passwordConfirmLabel: "비밀번호 확인",
          passwordConfirmPlaceholder: "비밀번호를 한 번 더 입력하세요",
          showPasswordLabel: "비밀번호 보기",
          hidePasswordLabel: "비밀번호 숨기기",
        },
        locked: true,
      }),
      section({
        id: "phoneVerification",
        title: "휴대폰 인증",
        description:
          "휴대폰 인증의 유효시간과 계정 수 제한은 보안을 위해 코드에서 보호됩니다.",
        locked: true,
      }),
      section({
        id: "organization",
        title: "소속 농협 선택",
        text: {
          searchLabel: "농협명 검색",
          searchPlaceholder: "예: 상주농협, 서울중앙농협",
          resultsAriaLabel: "농협 검색 결과",
          emptyPrefix: "",
          emptySuffix:
            "(으)로 검색된 농협이 없습니다. 마스터 목록에 있는 농협명으로 다시 검색해 주세요.",
          selectedPrefix: "선택한 농협:",
        },
        locked: true,
      }),
      section({
        id: "work",
        title: "담당자 정보 입력",
        text: {
          positionLabel: "직책",
          positionPlaceholder: "예: 과장, 팀장",
          dutyLabel: "담당업무",
          dutyPlaceholder: "담당업무 선택",
        },
        items: [
          item("accounting", "회계"),
          item("tax", "세무"),
          item("general", "총무"),
          item("hr", "인사"),
          item("audit", "감사"),
          item("member", "조합원 관리"),
          item("other", "기타"),
        ],
        locked: true,
      }),
      section({
        id: "businessCard",
        title: "명함 첨부",
        description: "직원 인증 및 관리자 승인 시 확인합니다.",
        text: {
          changeLabel: "변경",
          deleteLabel: "삭제",
          uploadTitle: "명함 이미지를 업로드하세요",
          uploadHelp: "JPG, PNG, PDF · 최대 10MB",
          selectLabel: "파일 선택",
          bytesUnit: "B",
          kilobytesUnit: "KB",
          megabytesUnit: "MB",
        },
      }),
      section({
        id: "consents",
        title: "약관 및 동의",
        text: {
          allLabel: "전체 동의",
          allHelp: "필수 및 선택 항목에 모두 동의합니다.",
          requiredBadge: "필수",
          optionalBadge: "선택",
          termsLabel: "이용약관 동의",
          termsLinkLabel: "보기",
          privacyLabel: "개인정보 수집·이용 동의",
          privacyLinkLabel: "보기",
          marketingTitle: "마케팅 및 수신 동의",
          marketingHelp:
            "아래 항목은 가입 후 마이페이지에서 언제든 변경할 수 있어요.",
          marketingLabel: "마케팅 정보 수신",
          emailLabel: "이메일 수신",
          smsLabel: "문자/SMS 수신",
          kakaoLabel: "카카오톡 수신",
        },
        actions: [
          action("terms", "이용약관", "/terms", "text"),
          action("privacy", "개인정보처리방침", "/privacy", "text"),
        ],
        locked: true,
      }),
      section({
        id: "benefits",
        title: "가입 혜택",
        items: [
          item(
            "first",
            "농협 최초 가입 시 전문 상담에 사용할 수 있는 100,000P를 지급합니다.",
          ),
          item("member", "이후 임직원 1인당 10,000P를 지급합니다."),
        ],
      }),
      section({
        id: "submit",
        title: "가입 신청",
        text: {
          submitLabel: "가입 신청 완료",
          submittingLabel: "가입 신청 저장 중...",
        },
        locked: true,
      }),
    ],
    {
      submitting: "가입 신청을 처리하고 있습니다.",
      success: "가입 신청이 접수되었습니다.",
      nameRequired: "이름을 입력해 주세요.",
      phoneRequired: "휴대폰 번호를 입력해 주세요.",
      phoneInvalid: "휴대폰 번호는 010-0000-0000 형식으로 입력해 주세요.",
      phoneVerificationRequired: "휴대폰 문자 인증을 먼저 진행해 주세요.",
      phoneCodeRequired: "문자로 받은 인증번호를 입력해 주세요.",
      phoneConfirmRequired: "휴대폰 인증 확인을 완료해 주세요.",
      phoneReceiveFirst: "먼저 '인증번호 받기'로 인증번호를 받아 주세요.",
      phoneCodeSixDigits: "문자로 받은 6자리 인증번호를 입력해 주세요.",
      phoneVerificationExpired:
        "휴대폰 인증이 만료되었습니다. 인증번호를 다시 받아 주세요.",
      phoneVerificationRetry:
        "회원가입을 완료하지 못해 휴대폰 인증을 다시 진행해 주세요.",
      phoneAccountLimit:
        "동일한 휴대폰 번호로는 최대 2개 계정까지만 가입할 수 있습니다.",
      phoneCodeInvalid:
        "인증번호가 올바르지 않습니다. 문자로 받은 번호를 다시 확인해 주세요.",
      phoneCodeExpired:
        "인증번호가 만료되었습니다. 인증번호를 다시 받아 주세요.",
      phoneTooMany:
        "인증 요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.",
      phoneQuota:
        "문자 인증 발송 한도를 초과했습니다. 잠시 후 다시 시도해 주세요.",
      phoneUnauthorizedDomain:
        "현재 접속한 주소가 휴대폰 인증 허용 도메인에 등록되지 않았습니다. 관리자에게 문의해 주세요.",
      phoneDisabled:
        "휴대폰 인증 서비스가 활성화되지 않았습니다. 관리자에게 문의해 주세요.",
      phoneCaptcha:
        "보안 인증에 실패했습니다. 페이지를 새로고침한 후 다시 시도해 주세요.",
      networkError: "네트워크 연결을 확인한 후 다시 시도해 주세요.",
      phoneGenericError:
        "휴대폰 문자 인증 중 문제가 발생했습니다. 잠시 후 다시 시도해 주세요.",
      emailRequired: "농협 이메일을 입력해 주세요.",
      emailInvalid: "이메일 형식이 올바르지 않습니다.",
      emailCheckRequired: "이메일 중복확인을 먼저 진행해 주세요.",
      emailDuplicate: "이미 가입된 이메일입니다. 로그인해 주세요.",
      emailCheckError:
        "이메일 중복확인 중 문제가 발생했습니다. 다시 시도해 주세요.",
      passwordRequired: "비밀번호를 입력해 주세요.",
      passwordMin: "비밀번호는 8자 이상 입력해 주세요.",
      passwordPolicyError:
        "비밀번호가 보안 정책 조건을 충족하지 않습니다. 다른 비밀번호를 입력해 주세요.",
      passwordConfirmRequired: "비밀번호 확인을 입력해 주세요.",
      passwordMismatch: "비밀번호가 일치하지 않습니다.",
      cooperativeRequired: "소속 농협을 선택해 주세요.",
      positionRequired: "직책을 입력해 주세요.",
      dutyRequired: "담당업무를 선택해 주세요.",
      consentsRequired:
        "필수 약관과 개인정보 수집·이용에 동의해 주세요.",
      businessCardType:
        "명함 파일은 JPG, PNG, PDF 형식만 첨부할 수 있습니다.",
      businessCardSize: "명함 파일은 최대 10MB까지 첨부할 수 있습니다.",
      missingFields:
        "필수 입력값이 누락되었습니다. 입력 내용을 다시 확인해 주세요.",
      invalidToken:
        "로그인 인증 정보가 만료되었습니다. 새로고침 후 다시 시도해 주세요.",
      emailMismatch: "가입 이메일과 인증 이메일이 일치하지 않습니다.",
      invalidCooperative:
        "선택한 농협 정보를 확인할 수 없습니다. 농협명을 다시 검색해 선택해 주세요.",
      invalidPhoneVerification:
        "휴대폰 인증 정보가 일치하지 않습니다. 인증번호를 다시 받아 주세요.",
      permissionError:
        "회원가입 정보를 저장할 수 없습니다. 잠시 후 다시 시도해 주세요.",
      genericError:
        "회원가입 저장 중 문제가 발생했습니다. 잠시 후 다시 시도해 주세요.",
    },
  ),
  "auth.pendingApproval": page(
    "가입 승인 대기 | 농협지원센터",
    "회원 승인 대기 상태를 안내합니다.",
    [
      section({
        id: "hero",
        eyebrow: "Approval pending",
        title: "관리자가 가입 신청을\n빠르게 확인 중이에요",
        description:
          "가입 신청 정보와 소속 농협을 확인하고 있어요.\n확인이 끝나면 상담·견적 요청과 마이페이지를 바로 이용하실 수 있습니다.",
        text: { highlight: "빠르게 확인 중이에요" },
      }),
      section({
        id: "status",
        eyebrow: "가입 승인 대기",
        title: "확인이 완료되면 다시 로그인해 주세요.",
        description: "관리자가 빠르게 확인 후 승인해 드릴 예정이에요.",
        actions: [action("login", "로그인 화면으로 이동", "/login")],
      }),
    ],
  ),
  "legal.terms": page(
    "이용약관 | 농협지원센터",
    "농협지원센터 서비스 이용 조건과 운영 원칙을 안내합니다.",
    [
      section({
        id: "intro",
        eyebrow: "Terms of Service",
        title: "농협지원센터 이용약관",
        description:
          "농협지원센터를 이용하기 전에 서비스의 범위와 이용 조건을 확인해 주세요.",
        locked: true,
        text: { effectiveDate: "시행일: 2026년 7월 21일" },
      }),
      section({
        id: "service",
        title: "서비스의 목적과 범위",
        description:
          "농협지원센터는 농협 업무 관련 문의를 접수·분류하고 답변 또는 전문가 연결을 지원합니다. 개별 전문가 업무의 계약과 수행 조건은 별도 안내와 계약에 따릅니다.",
        locked: true,
      }),
      section({
        id: "account",
        title: "회원 가입과 계정 관리",
        description:
          "회원은 정확한 본인·소속 정보를 제공해야 하며 계정과 인증정보를 안전하게 관리해야 합니다. 소속 확인과 관리자 승인 전에는 일부 기능 이용이 제한될 수 있습니다.",
        locked: true,
      }),
      section({
        id: "content",
        title: "문의 작성과 공개 범위",
        description:
          "회원은 문의에 개인정보나 비밀정보가 불필요하게 포함되지 않도록 확인하고 전체공개·우리농협공개·비공개 중 적절한 범위를 선택해야 합니다.",
        locked: true,
      }),
      section({
        id: "responsibility",
        title: "책임과 면책",
        description:
          "서비스의 안내는 일반적인 업무 지원 정보이며 개별 사안의 최종 의사결정이나 전문 업무 결과를 보증하지 않습니다. 정식 업무가 필요한 경우 별도의 전문가 검토와 계약이 필요합니다.",
        locked: true,
      }),
      section({
        id: "changes",
        title: "약관 변경과 문의",
        description:
          "약관이 변경되는 경우 적용 시점과 주요 변경 내용을 서비스에서 안내합니다. 이용 관련 문의는 고객지원 화면을 이용해 주세요.",
        actions: [action("support", "고객지원으로 이동", "/support")],
        locked: true,
      }),
    ],
  ),
  "legal.privacy": page(
    "개인정보처리방침 | 농협지원센터",
    "농협지원센터의 개인정보 처리 기준과 이용자 권리를 안내합니다.",
    [
      section({
        id: "intro",
        eyebrow: "Privacy Policy",
        title: "개인정보처리방침",
        description:
          "주식회사 프리고는 농협지원센터 운영에 필요한 범위에서 개인정보를 처리하고 안전하게 보호합니다.",
        locked: true,
        text: { effectiveDate: "시행일: 2026년 7월 21일" },
      }),
      section({
        id: "collection",
        title: "처리하는 개인정보",
        description:
          "회원가입과 소속 확인을 위해 이름, 이메일, 휴대폰 번호, 소속 농협, 담당 업무와 선택적으로 첨부한 명함 정보를 처리합니다. 상담 이용 시 문의 내용과 첨부파일, 처리 이력과 접속 기록이 생성될 수 있습니다.",
        locked: true,
      }),
      section({
        id: "purpose",
        title: "처리 목적",
        description:
          "회원 식별과 소속 확인, 상담 접수·답변·전문가 연결, 서비스 운영과 보안, 법적 의무 이행 및 이용자 문의 처리를 위해 개인정보를 이용합니다.",
        locked: true,
      }),
      section({
        id: "retention",
        title: "보유 및 이용 기간",
        description:
          "개인정보는 수집 목적 달성 또는 관계 법령상 보존기간 종료 후 지체 없이 파기합니다. 개별 동의 화면에서 별도 기간을 안내한 경우 해당 기준을 따릅니다.",
        locked: true,
      }),
      section({
        id: "sharing",
        title: "제3자 제공과 처리위탁",
        description:
          "상담 또는 견적 진행에 필요한 경우 사전 안내와 동의 범위에서 담당 전문가 또는 업무 수행 기관에 필요한 최소 정보가 전달될 수 있습니다. 처리위탁과 제공 현황은 변경 시 이 방침에서 안내합니다.",
        locked: true,
      }),
      section({
        id: "rights",
        title: "이용자의 권리",
        description:
          "이용자는 개인정보 열람·정정·삭제·처리정지와 동의 철회를 요청할 수 있습니다. 법령상 제한 사유가 없는 경우 확인 후 필요한 조치를 안내합니다.",
        locked: true,
      }),
      section({
        id: "safeguards",
        title: "안전성 확보 조치",
        description:
          "접근 권한 최소화, 인증과 권한 검증, 전송 구간 보호, 접속 기록과 보안 점검 등 개인정보 보호를 위한 관리적·기술적 조치를 적용합니다.",
        locked: true,
      }),
      section({
        id: "officer",
        title: "개인정보 보호책임자와 문의",
        description:
          "개인정보 보호책임자 김지혜 · 개인정보 관련 문의는 고객지원 화면을 이용해 주세요.",
        actions: [action("support", "개인정보 문의하기", "/support")],
        locked: true,
      }),
    ],
  ),
  "public.consult": page(
    "상담 신청 · 농협지원센터",
    "농협 업무에 필요한 세무·노무·감사·회계 전문가를 쉽고 신뢰감 있게 연결합니다.",
    [
      section({
        id: "steps",
        eyebrow: "Process",
        title: "상담 진행 절차",
        text: { ariaLabel: "상담 진행 절차", stepPrefix: "STEP" },
        items: [
          item(
            "register",
            "문의 등록",
            "궁금한 업무 분야와 내용을 작성하고 공개 범위를 선택합니다",
            "edit",
          ),
          item(
            "review",
            "답변 확인",
            "마이페이지에서 등록된 답변을 확인합니다",
            "eye",
          ),
          item(
            "followup",
            "추가 문의",
            "더 궁금한 내용이 있으면 이어서 질문합니다",
            "link",
          ),
          item(
            "connection",
            "전문가 연결",
            "추가상담·견적진행이 필요하면 연결 절차를 안내받습니다",
            "check",
          ),
        ],
      }),
      section({
        id: "hero",
        eyebrow: "농협지원센터 문의",
        title: "문의 작성하기",
      }),
      section({
        id: "categorySelector",
        title: "문의 유형",
        description:
          "어떤 분야인지 잘 모르겠다면 자동 배정을 선택해 주세요. 문의 내용을 보고 알맞은 담당자가 확인해 드립니다.",
        text: { ariaLabel: "문의 유형" },
        items: [
          item("auto", "자동 배정"),
          item("tax", "세무"),
          item("accounting", "회계"),
          item("legal", "법률"),
          item("labor", "노무"),
          item("registration", "등기"),
          item("appraisal", "감정평가"),
          item("ip", "지식재산"),
          item("customs", "관세·통관"),
          item("audit", "감사"),
        ],
        locked: true,
      }),
      section({
        id: "visibilitySelector",
        title: "공개 유형",
        text: { ariaLabel: "공개 유형" },
        items: [
          item("public", "전체 공개", "다른 농협 사용자도 볼 수 있어요."),
          item(
            "organization",
            "우리 농협 공개",
            "같은 소속 농협 사용자만 볼 수 있어요.",
          ),
          item("private", "비공개", "작성자와 관리자만 볼 수 있어요."),
        ],
        locked: true,
      }),
      section({
        id: "requestFields",
        title: "문의 내용",
        text: {
          followupNotice: "기존 문의와 연결된 후속 문의로 접수됩니다.",
          subjectLabel: "제목",
          subjectPlaceholder: "문의 제목을 입력해 주세요",
          messageLabel: "내용",
          messagePlaceholder: "궁금한 내용을 편하게 적어주세요.",
          photoLabel: "사진 첨부",
          optionalLabel: "선택",
          photoButtonTitle: "사진을 추가해 주세요",
          photoHelp: "JPG, PNG, GIF · 한 장당 10MB 이하 · 최대 6장",
          photoListAriaLabel: "첨부한 사진",
          deleteSuffix: "삭제",
          bytesUnit: "B",
          kilobytesUnit: "KB",
          megabytesUnit: "MB",
          submitLabel: "문의 등록하기",
          submittingLabel: "등록 중...",
        },
        locked: true,
      }),
      section({
        id: "success",
        title: "문의가 접수되었습니다",
        description: "답변은 마이페이지에서 확인할 수 있어요.",
        text: {
          requestNumberLabel: "접수번호",
          resetLabel: "새 문의 작성",
        },
      }),
    ],
    {
      submitting: "상담 신청을 등록하고 있습니다.",
      subjectRequired: "문의 제목을 입력해 주세요.",
      messageRequired: "문의 내용을 입력해 주세요.",
      authRequired: "로그인 후 상담·견적 요청을 등록해 주세요.",
      organizationRequired:
        "회원가입 소속 농협 정보가 없어 문의를 등록할 수 없습니다.",
      invalidAttachment:
        "사진은 이미지 파일만 가능하며 한 장당 10MB 이하로 첨부해 주세요.",
      tooManyAttachments: "사진은 최대 6장까지 첨부할 수 있어요.",
      imageOnly: "이미지 파일만 첨부할 수 있어요.",
      imageTooLarge: "사진 한 장은 최대 10MB까지 업로드할 수 있어요.",
      genericError: "전송 중 문제가 발생했습니다. 잠시 후 다시 시도해 주세요.",
    },
  ),
  "public.inquiries": page(
    "문의 게시판 · 농협지원센터",
    "농협지원센터 문의 게시판에서 비슷한 사례를 찾아보고, 공개 범위에 맞춰 상담 내용을 확인할 수 있습니다.",
    [
      section({
        id: "hero",
        eyebrow: "Inquiry Board",
        title: "궁금한 문의,\n게시판에서 바로 확인하세요",
        description:
          "비슷한 업무 사례를 먼저 찾아보고, 선택한 공개 범위에 맞춰 본문과 답변을 편하게 확인할 수 있습니다.",
        text: { highlight: "게시판에서 바로" },
      }),
      section({
        id: "filters",
        title: "검색과 필터",
        text: {
          boardAriaLabel: "문의 게시판",
          countPrefix: "게시판 문의",
          countSuffix: "건",
          allFilter: "전체문의",
          organizationFilter: "우리농협문의",
          mineFilter: "나의문의",
          searchLabel: "문의 검색",
          searchPlaceholder: "제목 또는 접수번호 검색",
          filtersAriaLabel: "문의 목록 필터",
          allGuestSummary: "전체공개 문의는 로그인 없이 바로 열어볼 수 있어요.",
          allMemberSummary:
            "선택하신 공개 범위에 맞춰 본문과 답변을 보여드려요.",
          organizationSummary: "우리 농협에 공유된 문의만 모아 보여드려요.",
          mineSummary: "내가 작성한 문의만 모아 보여드려요.",
        },
      }),
      section({
        id: "list",
        title: "상담 목록",
        text: {
          missingRequestNumber: "접수번호 없음",
          requestHeading: "문의 내용",
          answerHeading: "답변",
          answerPending: "아직 등록된 답변이 없습니다.",
          lockedTitle: "이 문의는 선택한 공개 범위로 보호되고 있어요.",
          lockedDescription:
            "로그인 상태와 소속 농협, 작성자 여부에 따라 열람 범위가 제한됩니다.",
          loginLabel: "로그인하고 내용 확인하기",
          visibilityPublic: "전체공개",
          visibilityOrganization: "우리농협공개",
          visibilityPrivate: "비공개",
          statusReceived: "접수 완료",
          statusAnswered: "답변 완료",
          statusCompleted: "완료",
          statusFollowup: "추가 문의",
          previewPublicSubject: "업무 상담 진행 절차가 궁금합니다",
          previewPublicMessage:
            "상담을 신청한 뒤 답변을 확인하는 절차를 알고 싶습니다.",
          previewPublicAnswer:
            "문의가 접수되면 담당자가 내용을 확인하고 마이페이지에 답변을 등록합니다.",
          previewLockedSubject: "우리 농협 공개 문의 예시",
        },
      }),
    ],
    {
      loading: "상담 목록을 불러오고 있습니다.",
      empty: "조건에 맞는 상담이 없습니다.",
      denied: "이 상담을 볼 권한이 없습니다.",
      genericError: "상담 목록을 불러오지 못했습니다.",
    },
  ),
  "public.faq": page(
    "FAQ · 농협지원센터",
    "농협지원센터 FAQ 게시판에서 자주 묻는 질문을 유형별로 찾고 검색할 수 있습니다.",
    [
      section({
        id: "hero",
        eyebrow: "FAQ Board",
        title: "자주 묻는 질문을\n유형별로 확인하세요",
        description:
          "회원가입, 문의 진행, 포인트 등 자주 찾는 안내를 한곳에서 검색하고 확인할 수 있습니다.",
        text: { highlight: "유형별로" },
      }),
      section({
        id: "filters",
        title: "질문 검색",
        text: {
          boardAriaLabel: "FAQ 게시판",
          countPrefix: "FAQ",
          countSuffix: "건",
          summary:
            "유형을 선택하거나 키워드를 검색해 필요한 안내를 빠르게 확인하세요.",
          categoryLabel: "유형 선택",
          allCategoriesLabel: "전체 유형",
          searchLabel: "FAQ 검색",
          searchPlaceholder: "질문, 답변, 유형 검색",
        },
      }),
      section({
        id: "list",
        title: "질문과 답변",
        items: DEFAULT_PUBLIC_FAQS.map((faq) => ({
          id: faq.id.replaceAll("-", "_"),
          label: faq.category,
          title: faq.question,
          description: faq.answer,
          visible: true,
          deleted: false,
        })),
      }),
    ],
    {
      loading: "질문을 불러오고 있습니다.",
      empty: "검색 결과가 없습니다.",
      fallback: "기본 안내 내용을 표시하고 있습니다.",
    },
  ),
  "public.support": page(
    "고객지원 | 농협지원센터",
    "농협지원센터 이용 문의 방법을 안내합니다.",
    [
      section({
        id: "hero",
        eyebrow: "Support",
        title: "농협지원센터\n고객지원",
        description: "서비스 이용 중 궁금한 점이 있다면 문의를 남겨 주세요.",
        text: { highlight: "고객지원" },
      }),
      section({
        id: "channels",
        eyebrow: "CS",
        title: "상담 문의 안내",
        description:
          "로그인한 회원은 문의 작성 화면에서 상담 요청을 등록할 수 있습니다. 계정이나 승인 상태 관련 문의는 운영자 확인 후 안내됩니다.",
        actions: [
          action("consult", "문의 작성하기", "/consult"),
          action("mypage", "마이페이지로 이동", "/mypage", "secondary"),
        ],
      }),
    ],
  ),
  "event.auditQuote": page(
    "FY27 회계감사 견적 요청 · 농협지원센터",
    "지역농협 회계감사 견적을 한 번 요청으로 비교할 수 있도록 지원하는 FY27 임시 이벤트 페이지입니다.",
    [
      section({
        id: "hero",
        eyebrow: "FY27 회계감사 견적",
        title: "회계법인 견적,\n한 번에 비교하세요",
        description:
          "한 번만 신청하면 동일 조건으로 2곳 이상의\n비교 가능한 견적을 받아볼 수 있어요.",
        text: { highlight: "한 번에 비교하세요" },
      }),
      section({
        id: "intakeForm",
        title: "견적 신청 영역",
        locked: true,
        text: {
          formTitle: "",
          formDescription: "",
          formAriaLabel: "견적 신청",
          emailLabel: "농협 이메일",
          emailPlaceholder: "example@nonghyup.com",
          emailHelp: "",
          nameLabel: "담당자 이름",
          namePlaceholder: "홍길동",
          nameHelp: "",
          phoneLabel: "휴대폰 번호",
          phonePlaceholder: "010-0000-0000",
          phoneHelp: "",
          privacyConsentLabel: "[필수] 개인정보 수집·이용 동의",
          privacyConsentLinkLabel: "보기",
          marketingConsentLabel: "[선택] 이벤트·혜택 정보 수신 동의",
          submitLabel: "견적 요청하기",
          freeNotice: "무료 신청 · 비교 후에도 계약 의무 없음",
        },
      }),
      section({
        id: "benefits",
        title: "이런 걸 도와드려요",
        text: { ariaLabel: "제공 혜택" },
        items: [
          item(
            "multipleQuotes",
            "2곳 이상 견적",
            "동일 조건으로 복수 회계법인에 견적을 요청해요.",
          ),
          item(
            "comparison",
            "한눈에 비교",
            "보수·수임실적·투입인력·일정을 한 표로 정리해요.",
          ),
          item(
            "reviewReport",
            "선정 검토보고서",
            "견적서를 올리면 내부 보고용 검토자료를 드려요.",
          ),
        ],
      }),
      section({
        id: "steps",
        title: "이렇게 진행돼요",
        text: { ariaLabel: "진행 순서" },
        items: [
          item("request", "신청", "이메일과 담당자 정보만 남겨 주세요."),
          item(
            "quoteRequest",
            "견적 요청",
            "프리고가 필수정보를 확인하고 2곳 이상에 요청해요.",
          ),
          item(
            "comparisonDelivery",
            "비교표 전달",
            "비교 가능한 견적을 이메일로 보내드려요.",
          ),
        ],
      }),
      section({
        id: "faq",
        title: "자주 묻는 질문",
        text: { ariaLabel: "자주 묻는 질문" },
        items: [
          item(
            "contractRequired",
            "신청하면 꼭 계약해야 하나요?",
            "아니요. 비교 후에도 계약 의무는 없고, 최종 선정은 우리 농협이 결정해요.",
          ),
          item(
            "lowestPrice",
            "가장 저렴한 곳을 추천해 주나요?",
            "최저가 추천 서비스가 아니에요. 동일 조건의 비교 가능한 견적을 정리해 드려요.",
          ),
          item(
            "informationUse",
            "입력한 정보는 어디에 쓰이나요?",
            "견적 진행에 필요한 범위에서만 담당 운영자와 견적 대상 회계법인에 전달돼요. 자세한 내용은 개인정보처리방침을 확인해 주세요.",
          ),
        ],
      }),
      section({
        id: "legalNotice",
        title: "운영 주체와 면책문구",
        description:
          "가 운영하는 견적지원 서비스로, 농협중앙회 공식 서비스가 아닙니다. 감사인의 수임 여부와 독립성 확인, 감사계획·절차·의견 결정은 각 회계법인이 관련 기준에 따라 독립적으로 수행하며, 프리고는 감사의견이나 감사결과에 관여하지 않습니다.",
        text: {
          ariaLabel: "운영 안내",
          operatorName: "주식회사 프리고",
        },
        locked: true,
      }),
    ],
    {
      closedTitle: "지금은 접수 기간이 아니에요",
      closedDescription:
        "현재 FY27 회계감사 견적 접수 기간이 아닙니다. 접수 가능 시 이 페이지에서 다시 안내드립니다.",
      submitting: "접수 중…",
      submittingStatus: "견적 요청을 전송하고 있어요.",
      successTitle: "신청이 완료됐어요",
      successDescription:
        "담당자가 확인 후 입력하신 이메일로 다음 절차를 안내드려요.",
      publicReferenceLabel: "접수번호",
      resetLabel: "다른 담당자로 신청하기",
      emailRequired: "농협 이메일을 입력해 주세요.",
      emailInvalid: "농협 이메일(@nonghyup.com)만 신청할 수 있어요.",
      nameRequired: "담당자 이름을 입력해 주세요.",
      nameInvalid: "이름을 정확히 입력해 주세요.",
      phoneRequired: "휴대폰 번호를 입력해 주세요.",
      phoneInvalid: "올바른 휴대폰 번호를 입력해 주세요.",
      consentRequired: "개인정보 수집·이용에 동의해 주세요.",
      privacyVersionMismatch:
        "동의 버전이 갱신되었습니다. 페이지를 새로고침한 뒤 다시 시도해 주세요.",
      eventDisabled: "현재 접수 기간이 아닙니다.",
      rateLimited: "요청이 많아 잠시 후 다시 시도해 주세요.",
      requestRejected:
        "요청을 처리할 수 없습니다. 페이지를 새로고침한 뒤 다시 시도해 주세요.",
      genericError:
        "전송 중 문제가 발생했습니다. 잠시 후 다시 시도해 주세요.",
    },
  ),
  "member.mypage": page(
    "마이페이지 · 농협지원센터",
    "내 문의, 답변 공개범위, 농협별 통합 포인트 지갑을 확인합니다.",
    [
      section({
        id: "navigation",
        title: "마이페이지 메뉴",
        text: {
          navigationAriaLabel: "마이페이지 내비게이션",
          brandMark: "N",
          serviceName: "농협지원센터",
          brandSubtitle: "마이페이지",
          breadcrumbPrefix: "마이페이지",
          fallbackMemberName: "회원",
          avatarFallback: "회",
          profileIncomplete: "프로필 미완료",
          organizationPending: "소속 확인 중",
          missingValue: "정보 없음",
          unknownValue: "확인 필요",
          pointUnit: "P",
          homeLabel: "홈으로",
          logoutLabel: "로그아웃",
          lastSyncPrefix: "마지막 동기화",
          refreshLabel: "새로고침",
          refreshingLabel: "새로고침 중...",
          newInquiryLabel: "+ 새 문의 등록",
          incompleteNotice:
            "소속 농협 정보를 등록하지 않았어요. 회원가입을 마무리하면 농협 통합 지갑과 답변 열람을 사용할 수 있어요.",
          continueSignupLabel: "회원가입 이어가기",
          closeLabel: "닫기",
        },
        items: [
          item("overview", "이용 현황", "내 활동과 보유 포인트 요약"),
          item("inquiries", "문의 내역", "내가 등록한 문의와 답변"),
          item("points", "포인트", "농협 지갑 포인트 사용 내역"),
          item("profile", "내 정보", "내 소속과 계정 정보"),
        ],
        locked: true,
      }),
      section({
        id: "overview",
        title: "이용 현황",
        text: {
          inquiriesTopbarTitle: "문의 내역",
          inquiriesTopbarDescription:
            "등록한 문의와 답변 내역을 상세하게 확인할 수 있습니다.",
          balanceLabel: "보유 포인트",
          organizationFallback: "소속 농협",
          walletSuffix: "통합 지갑",
          inquiryCountLabel: "등록 문의",
          inquiryCountHelp: "내가 등록한 전체 문의",
          unreadAnswersLabel: "미열람 답변",
          unreadAnswersHelp: "아직 확인하지 않은 답변",
          viewedAnswersLabel: "확인한 답변",
          viewedAnswersHelp: "열람을 완료한 답변",
          recentInquiriesTitle: "최근 내 문의",
          recentInquiriesDescription: "최근 등록한 문의 5건입니다.",
          recentPointsTitle: "최근 포인트 이력",
          recentPointsDescription: "최근 적립과 사용 내역 5건입니다.",
          viewAllLabel: "전체 보기",
          countSuffix: "건",
          requestNumberHeading: "문의번호",
          subjectHeading: "제목",
          visibilityHeading: "공개범위",
          statusHeading: "상태",
          createdHeading: "등록일",
          emptyInquiriesLink: "새 문의를 작성해 보세요.",
          ledgerFallback: "포인트 변동",
          visibilityPublic: "전체 공개",
          visibilityOrganization: "농협 공개",
          visibilityPrivate: "비공개",
          statusSubmitted: "답변 대기",
          statusAnswered: "답변 완료",
          statusPublished: "답변 열람",
          statusFollowup: "추가 문의",
          statusCompleted: "상담 종료",
          ledgerFirstSignup: "농협 최초 가입 보너스",
          ledgerUserSignup: "회원 가입 적립",
          ledgerAnswerView: "답변 열람 사용",
          ledgerManual: "수동 조정",
          ledgerAdminCredit: "운영자 적립",
          ledgerAdminDebit: "운영자 차감",
        },
        locked: true,
      }),
      section({
        id: "inquiries",
        title: "문의 내역",
        description:
          "등록한 문의와 답변 내역을 상세하게 확인할 수 있습니다.",
        text: {
          newInquiryLabel: "+ 새 문의 등록",
          requestNumberHeading: "문의번호",
          subjectHeading: "제목",
          visibilityHeading: "공개범위",
          statusHeading: "상태",
          answerHeading: "답변",
          createdHeading: "등록일",
          viewedAnswerLabel: "확인 완료",
          viewAnswerLabel: "답변 확인",
          answerPendingLabel: "답변 대기",
          detailLabel: "상세 보기",
          emptyLinkLabel: "새 문의를 작성해 보세요.",
          actionsHeading: "문의 작업",
        },
        locked: true,
      }),
      section({
        id: "points",
        title: "포인트 내역",
        text: {
          balanceLabel: "현재 잔액",
          walletSuffix: "통합 지갑",
          earnedLabel: "총 적립 포인트",
          earnedHelp: "가입 보너스와 운영자 적립 포함",
          usedLabel: "총 사용 포인트",
          usedHelp: "답변 열람과 운영자 차감 포함",
          countLabel: "포인트 이력",
          countHelp: "전체 포인트 내역 기준",
          guideTitle: "포인트 안내",
          guideDescription:
            "농협 통합 지갑 포인트는 상담 답변을 열람할 때 사용됩니다.",
          historyTitle: "포인트 사용 내역",
          historyDescription: "적립과 사용 내역을 시간 순으로 보여드려요.",
          dateHeading: "일시",
          eventHeading: "이벤트",
          descriptionHeading: "설명",
          changeHeading: "변동",
          balanceHeading: "잔액",
        },
        items: [
          item(
            "approval",
            "최초 승인 시 농협 지갑에 가입 보너스가 적립됩니다.",
          ),
          item(
            "singleCharge",
            "답변을 처음 열람할 때만 포인트가 차감되고, 다시 보기는 중복 차감되지 않습니다.",
          ),
          item(
            "contact",
            "포인트가 부족하면 운영자에게 충전 또는 조정을 요청해 주세요.",
          ),
        ],
        locked: true,
      }),
      section({
        id: "profile",
        title: "내 정보",
        description: "회원가입 정보와 소속 농협을 확인할 수 있어요.",
        text: {
          nameLabel: "이름",
          emailLabel: "이메일",
          phoneLabel: "연락처",
          organizationLabel: "소속 농협",
          organizationMissing: "등록되지 않음",
          organizationPending: "확인 중",
          positionLabel: "직책",
          dutyLabel: "담당 업무",
          joinedLabel: "가입일",
          businessCardLabel: "명함 첨부",
          businessCardView: "첨부 파일 보기",
          businessCardEmpty: "첨부 없음",
          walletTitle: "소속 농협 지갑",
          walletDescription:
            "회원가입으로 연결된 농협 통합 지갑 정보입니다.",
          walletOrganizationLabel: "농협명",
          walletBalanceLabel: "지갑 잔액",
          walletEarnedLabel: "누적 적립",
          walletUsedLabel: "누적 사용",
          walletMemberCountLabel: "조직 회원 수",
          memberSuffix: "명",
          walletCreatedLabel: "조직 생성일",
          walletUpdatedLabel: "최근 업데이트",
          consentsTitle: "계정 동의 항목",
          consentsDescription:
            "회원가입 시 동의한 항목을 확인하고, 선택 수신 항목은 토글로 변경할 수 있습니다.",
          requiredConsentsTitle: "필수 동의",
          termsLabel: "이용약관",
          privacyLabel: "개인정보 수집·이용",
          optionalConsentsTitle: "선택 수신 동의",
          optionalConsentsDescription:
            "마케팅·이메일·SMS·카카오 알림 수신 여부를 직접 변경할 수 있습니다.",
          marketingLabel: "마케팅 정보 수신",
          consentEmailLabel: "이메일 수신",
          smsLabel: "SMS 수신",
          kakaoLabel: "카카오 알림 수신",
          agreedLabel: "동의",
          disagreedLabel: "미동의",
          savingLabel: "저장 중",
          incompleteTitle: "회원가입 마무리",
          incompleteDescription:
            "소속 농협 정보를 입력하면 통합 지갑과 답변 열람 기능을 이용할 수 있어요.",
          continueSignupLabel: "회원가입 이어가기",
        },
        locked: true,
      }),
    ],
    {
      loading: "마이페이지를 준비하고 있습니다",
      loadingDescription: "로그인 정보와 농협 지갑을 확인하고 있습니다.",
      loginRequired: "로그인이 필요합니다.",
      loadFailed: "마이페이지 데이터를 불러오지 못했습니다.",
      retryDescription: "잠시 후 다시 시도해 주세요.",
      retryLabel: "다시 시도",
      otherLoginLabel: "다른 계정으로 로그인",
      refreshed: "데이터를 새로 불러왔습니다.",
      refreshFailed: "새로고침에 실패했습니다.",
      logoutFailed: "로그아웃에 실패했습니다.",
      consentLoginRequired:
        "로그인 후 동의 항목을 변경할 수 있습니다.",
      consentSaved: "수신 동의 항목을 저장했습니다.",
      consentSaveFailed:
        "동의 항목을 저장하지 못했습니다. 잠시 후 다시 시도해 주세요.",
      emptyInquiries: "등록한 상담이 없습니다.",
      emptyPoints: "포인트 내역이 없습니다.",
      genericError: "마이페이지 정보를 불러오지 못했습니다.",
      relativeNow: "방금 전",
      relativeMinutes: "{count}분 전",
      relativeHours: "{count}시간 전",
      relativeDays: "{count}일 전",
    },
  ),
  "member.requestDetail": page(
    "문의 상세 · 농협지원센터",
    "마이페이지에서 선택한 문의의 상태와 공개범위를 확인합니다.",
    [
      section({
        id: "summary",
        title: "상담 요약",
        eyebrow: "문의 상세",
        text: {
          backLabel: "← 문의 내역으로 돌아가기",
          backHint: "문의 내역으로 돌아갑니다.",
          statusLabel: "상태",
          visibilityLabel: "공개범위",
          pointsLabel: "농협 포인트",
          pointUnit: "P",
          missingValue: "정보 없음",
          visibilityPublic: "전체공개",
          visibilityOrganization: "우리농협공개",
          visibilityPrivate: "미공개",
          statusSubmitted: "답변 대기",
          statusAnswered: "답변 완료",
          statusPublished: "답변 열람",
          statusFollowup: "추가 문의",
          statusCompleted: "상담 종료",
        },
        locked: true,
      }),
      section({
        id: "requestBody",
        eyebrow: "문의 내용",
        title: "문의 내용",
        text: { receivedPrefix: "접수일:" },
        locked: true,
      }),
      section({
        id: "attachments",
        eyebrow: "첨부 사진",
        title: "등록한 사진",
        text: { countSuffix: "장" },
        locked: true,
      }),
      section({
        id: "answer",
        eyebrow: "답변 내용",
        title: "답변이 등록되었습니다.",
        description: "운영자가 답변을 준비 중입니다.",
        text: {
          emptyBody:
            "등록된 답변 본문이 없습니다. 운영자에게 문의해 주세요.",
          pointPrefix: "답변을 열람하면",
          pointSuffix: "P가 차감됩니다.",
          noDuplicateCharge: "이미 열람한 답변은 추가 차감되지 않습니다.",
          loadingLabel: "답변을 여는 중...",
          openLabel: "답변 열람하기",
          pendingDescription:
            "답변이 완료되면 이 화면에서 바로 확인할 수 있습니다.",
        },
        locked: true,
      }),
      section({
        id: "followupActions",
        eyebrow: "후속 액션",
        title: "답변 확인 후 다음 단계를 선택해 주세요.",
        description:
          "답변으로 해결되지 않은 내용은 후속 문의나 상담 요청으로 이어가고, 해결된 문의는 평가를 남긴 뒤 완료할 수 있습니다.",
        text: {
          followupTitle: "추가 문의 작성",
          followupDescription: "답변과 연결된 후속 문의를 남깁니다.",
          estimateTitle: "추가상담·견적진행 요청",
          estimateDescription: "전문가 연결이나 견적이 필요한 경우 요청합니다.",
          completedTitle: "문의 완료됨",
          completedDescription: "평가 작성 후 상담이 종료되었습니다.",
          completeTitle: "문의 완료하기",
          completeDescription:
            "문제가 해결되었다면 답변 평가를 작성하고 문의를 종료합니다.",
        },
        locked: true,
      }),
      section({
        id: "rating",
        title: "답변 평가",
        description:
          "문의 완료 전 답변 평가를 작성해 주세요. 평가는 운영자가 답변 품질과 후속 지원 필요 여부를 확인하는 데 사용됩니다.",
        text: {
          completedBadge: "(작성 완료)",
          requiredBadge: "(필수)",
          scoreAriaLabel: "답변 점수",
          scoreSuffix: "점",
          helpfulLabel: "도움이 되었어요",
          needsWorkLabel: "보완이 필요해요",
          commentPlaceholder:
            "답변에 대한 의견이나 추가로 필요한 도움을 적어주세요.",
          savingLabel: "평가 저장 중...",
          updateLabel: "평가 수정하기",
          saveLabel: "답변 평가 저장",
          completingLabel: "완료 처리 중...",
          completeLabel: "문의 완료 처리",
        },
        locked: true,
      }),
      section({
        id: "dialogs",
        title: "열람과 완료 확인 창",
        text: {
          completeEyebrow: "문의 완료",
          completeTitle: "상담을 종료하시겠습니까?",
          completeDescription:
            "완료 처리 후에는 이 문의의 상담이 종료됩니다. 추가 지원이 필요하면 완료 전에 추가 문의나 후속 상담 요청을 먼저 진행해 주세요.",
          continueLabel: "계속 진행",
          completingLabel: "완료 처리 중...",
          endLabel: "상담 종료하기",
          viewTitle: "답변을 열람하시겠습니까?",
          pointPrefix: "답변을 열람하면",
          pointSuffix: "P가 차감됩니다.",
          noDuplicateCharge: "이미 열람한 답변은 추가 차감되지 않습니다.",
          costLabel: "차감 예정 포인트",
          balanceLabel: "현재 보유 포인트",
          insufficient:
            "보유 포인트가 부족하여 답변을 열람할 수 없습니다.",
          cancelLabel: "취소",
          processingLabel: "열람 처리 중...",
          viewLabel: "답변 열람하기",
        },
        locked: true,
      }),
    ],
    {
      loading: "문의 내용을 불러오는 중입니다.",
      loadFailed: "문의 상세를 불러오지 못했습니다.",
      notFound: "조회할 수 없는 문의입니다.",
      notFoundDescription: "공개범위 또는 소속 농협 권한을 확인해 주세요.",
      insufficientPoints:
        "포인트가 부족하여 답변을 열람할 수 없습니다.",
      viewFailed: "답변을 열람하지 못했습니다.",
      ratingSaved:
        "답변 평가를 저장했습니다. 이제 문의를 완료할 수 있습니다.",
      ratingRequiresView: "답변 열람 후 평가를 남길 수 있습니다.",
      ratingFailed:
        "답변 평가를 저장하지 못했습니다. 잠시 후 다시 시도해 주세요.",
      completeRequiresView:
        "답변을 먼저 열람한 뒤 문의를 완료할 수 있습니다.",
      completeRequiresRating: "문의 완료 전 답변 평가를 작성해 주세요.",
      completeSuccess: "문의가 완료 처리되었습니다.",
      completeFailed:
        "문의 완료 처리에 실패했습니다. 잠시 후 다시 시도해 주세요.",
      genericError: "문의 상세를 불러오지 못했습니다.",
    },
  ),
  "partner.portal": page(
    "협력 전문가 포털 | 농협지원센터",
    "권한이 있는 협력 전문가를 위한 업무 화면입니다.",
    [
      section({
        id: "accessNotice",
        eyebrow: "Partner access",
        title: "협력 전문가 전용 화면입니다",
        description:
          "현재 공개된 파트너 시제품은 운영 정보 보호를 위해 비활성화했습니다. 배정된 협력 전문가 계정과 접근 권한이 준비된 뒤 이용할 수 있습니다.",
        actions: [
          action("home", "홈으로 이동", "/"),
          action("support", "접근 문의", "/support", "secondary"),
        ],
        locked: true,
      }),
    ],
    { denied: "협력 전문가 권한이 필요합니다." },
  ),
  "admin.console": page(
    "콘텐츠 관리자 | 농협지원센터",
    "관리자가 화면 콘텐츠와 게시 상태를 관리하는 화면입니다.",
    [
      section({
        id: "navigation",
        title: "콘텐츠 관리 메뉴",
        description: "관리자 화면의 메뉴 이름과 짧은 설명을 관리합니다.",
        text: {
          ariaLabel: "콘텐츠 관리 메뉴",
        },
        items: [
          item("dashboard", "대시보드", "운영 현황 한눈에 보기"),
          item("pages", "페이지 관리", "화면별 내용과 게시 상태"),
          item("globals", "공통 영역", "상단·하단과 공통 안내"),
          item("design", "디자인 설정", "색상·글자·간격 기본값"),
          item("assets", "이미지·파일", "공용 자료와 사용 상태"),
          item("history", "수정·게시 이력", "최근 변경과 게시 기록"),
        ],
        locked: true,
      }),
      section({
        id: "shell",
        title: "관리자 공통 화면",
        description: "서비스 이름, 계정 영역과 새로고침 안내를 관리합니다.",
        text: {
          homeAriaLabel: "콘텐츠 관리자 홈",
          brandMark: "N",
          brandName: "농협지원센터",
          brandSubtitle: "콘텐츠 관리자",
          operationsLink: "회원·상담 운영",
          userFallback: "관리자",
          userInitialFallback: "관",
          permissionLabel: "콘텐츠 관리 권한",
          logout: "로그아웃",
          breadcrumb: "콘텐츠 관리",
          lastChecked: "마지막 확인",
          refresh: "새로고침",
          refreshing: "불러오는 중...",
          noticeCloseAriaLabel: "안내 닫기",
          recordMissing: "기록 없음",
          activityEmptyDescription:
            "새로운 작업이 생기면 이곳에서 바로 확인할 수 있습니다.",
        },
        locked: true,
      }),
      section({
        id: "dashboard",
        title: "대시보드",
        description: "콘텐츠 운영 상태와 확인할 일을 한눈에 살펴보세요.",
        text: {
          summaryAriaLabel: "콘텐츠 운영 요약",
          recentChangesTitle: "최근 수정",
          recentChangesDescription: "초안 수정과 복원 작업을 확인합니다.",
          recentChangesEmpty: "최근 수정 기록이 없습니다.",
          recentPublishesTitle: "최근 게시",
          recentPublishesDescription: "실제 화면에 반영된 작업을 확인합니다.",
          recentPublishesEmpty: "최근 게시 기록이 없습니다.",
          viewAll: "전체 보기",
          issuesTitle: "확인이 필요한 항목",
          issuesDescription: "오류와 경고를 확인한 뒤 게시해 주세요.",
          issueReview: "확인",
          noIssuesTitle: "확인이 필요한 문제가 없습니다.",
          noIssuesDescription: "게시 전 검토 항목이 생기면 이곳에 표시됩니다.",
        },
        items: [
          item(
            "editablePages",
            "편집 가능한 페이지",
            "현재 관리할 수 있는 전체 화면",
            "개",
          ),
          item(
            "unpublishedDrafts",
            "미게시 초안",
            "아직 고객 화면에 반영되지 않은 변경",
            "건",
          ),
          item(
            "recentlyModified",
            "최근 수정",
            "최근 7일 동안의 수정 작업",
            "건",
          ),
          item(
            "recentlyPublished",
            "최근 게시",
            "최근 7일 동안 실제 반영된 작업",
            "건",
          ),
          item(
            "reviewRequired",
            "검토 필요",
            "게시 전에 확인할 오류와 경고",
            "건",
          ),
        ],
        locked: true,
      }),
      section({
        id: "pages",
        title: "페이지 관리",
        description: "고객과 회원에게 보이는 화면을 찾고 상태를 확인합니다.",
        text: {
          searchAriaLabel: "화면 검색",
          searchPlaceholder: "화면 이름이나 주소 검색",
          filterAriaLabel: "화면 분류",
          countSuffix: "개 화면",
          emptyTitle: "조건에 맞는 화면이 없습니다.",
          emptyDescription: "검색어나 화면 분류를 바꿔 다시 확인해 주세요.",
          previewAriaSuffix: "미리보기",
          detailsAriaSuffix: "편집 정보 보기",
          audienceLabel: "공개 범위",
          modifiedLabel: "최종 수정",
          edit: "편집",
          preview: "미리보기",
          publish: "게시",
          publishAvailableTitle: "게시 전 확인 창을 엽니다.",
          publishUnavailableTitle: "게시할 변경사항이 없습니다.",
        },
        items: [
          item("filter.all", "전체 분류"),
          item("filter.public", "공개 화면"),
          item("filter.auth", "로그인·가입"),
          item("filter.member", "회원 화면"),
          item("filter.event", "행사 화면"),
          item("filter.admin", "관리자 화면"),
          item("filter.other", "기타 화면"),
        ],
        locked: true,
      }),
      section({
        id: "commonAreas",
        title: "공통 영역",
        description:
          "여러 화면에 함께 적용되는 상단, 하단과 공통 안내를 관리합니다.",
        text: {
          statusLabel: "상태",
          modifiedLabel: "최종 수정",
          edit: "내용 편집",
          comingSoon: "준비 중",
        },
        locked: true,
      }),
      section({
        id: "design",
        title: "디자인 설정",
        description: "승인된 선택지 안에서 전체 화면의 기본 모양을 관리합니다.",
        text: {
          calloutTitle: "안전한 디자인 선택지만 제공합니다.",
          calloutDescription:
            "전체 화면에 영향을 주는 설정입니다. 변경 기능은 영향 범위와 미리보기를 함께 제공한 뒤 활성화됩니다.",
          change: "설정 변경",
          sampleText: "가나다",
        },
        items: [
          item(
            "palette",
            "기본 색상",
            "버튼, 링크와 강조 영역에 사용하는 색상입니다.",
          ),
          item(
            "textScale",
            "글자 크기",
            "전체 화면에서 사용하는 기본 글자 크기입니다.",
          ),
          item(
            "spacing",
            "요소 간격",
            "카드와 문단 사이의 여백 정도입니다.",
          ),
          item(
            "radius",
            "모서리 모양",
            "버튼과 카드의 둥근 정도입니다.",
          ),
          item(
            "alignment",
            "기본 정렬",
            "페이지 제목과 주요 소개 영역의 기본 정렬입니다.",
          ),
        ],
        locked: true,
      }),
      section({
        id: "assets",
        title: "이미지·파일",
        description: "화면에서 사용하는 이미지와 문서의 상태를 확인합니다.",
        text: {
          listTitle: "이미지·파일 목록",
          listDescription: "파일 이름, 사용 상태와 대체 설명을 확인합니다.",
          add: "파일 추가",
          emptyTitle: "등록된 이미지나 파일이 없습니다.",
          emptyDescription:
            "화면별 편집 도구에서 파일을 추가하면 이곳에 모아서 표시됩니다.",
          pdfBadge: "PDF",
          imageBadge: "IMG",
          pdfKind: "PDF 문서",
          statusLabel: "상태",
          modifiedLabel: "최종 수정",
        },
        locked: true,
      }),
      section({
        id: "history",
        title: "수정·게시 이력",
        description: "누가 언제 어떤 내용을 수정하거나 게시했는지 확인합니다.",
        text: {
          listTitle: "최근 작업 기록",
          listDescription:
            "콘텐츠 원문이나 개인정보 없이 작업 종류만 기록합니다.",
          empty: "아직 작업 기록이 없습니다.",
        },
        locked: true,
      }),
      section({
        id: "pageInfoDialog",
        title: "페이지 정보 창",
        description: "페이지 구성과 안전한 초안 편집 안내를 관리합니다.",
        text: {
          eyebrow: "화면 편집 준비",
          closeAriaLabel: "편집 정보 닫기",
          addressLabel: "페이지 주소",
          audienceLabel: "보는 사람",
          statusLabel: "게시 상태",
          sectionsTitle: "화면 구성",
          sectionsDescription: "이 화면에서 관리할 영역을 확인합니다.",
          sectionCountSuffix: "개 영역",
          visible: "화면에 표시",
          hidden: "현재 숨김",
          itemCountPrefix: "목록",
          itemCountSuffix: "개",
          required: "필수 영역",
          advanced: "고급 정보",
          draftVersion: "초안 번호",
          publishedVersion: "게시 번호",
          none: "없음",
          safetyTitle: "안전한 초안 편집",
          safetyDescription:
            "편집한 내용은 초안으로 자동 저장되며, 게시하기 전에는 고객 화면에 반영되지 않습니다.",
          preview: "미리보기",
          openEditor: "페이지 편집기 열기",
        },
        locked: true,
      }),
      section({
        id: "publishDialog",
        title: "게시 확인 창",
        description: "게시 영향 범위와 확인 버튼 안내를 관리합니다.",
        text: {
          titleSuffix: "을 게시할까요?",
          description:
            "게시하면 이 화면의 초안이 고객에게 보이는 실제 내용으로 바뀝니다. 다른 화면과 공통 영역에는 영향을 주지 않습니다.",
          impactLabel: "영향받는 화면",
          cancel: "취소",
          publishing: "게시하는 중...",
          confirm: "확인하고 게시",
        },
        locked: true,
      }),
    ],
    {
      loading: "관리자 콘솔을 준비하고 있습니다.",
      loadingDescription: "화면과 게시 상태를 안전하게 불러오는 중입니다.",
      denied: "관리자 권한이 필요합니다.",
      deniedDescription:
        "콘텐츠를 관리할 수 있는 계정으로 다시 로그인해 주세요.",
      loginAgain: "로그인 화면으로",
      genericError: "관리자 정보를 불러오지 못했습니다.",
      genericErrorDescription:
        "잠시 후 다시 시도해 주세요. 공개 화면은 기존 내용으로 계속 운영됩니다.",
      retry: "다시 불러오기",
      refreshed: "최신 상태를 불러왔습니다.",
      refreshFailed:
        "새로 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.",
      publishSuccessSuffix: "게시가 완료되었습니다.",
      publishConflict:
        "다른 관리자가 먼저 수정했습니다. 최신 상태를 불러온 뒤 다시 확인해 주세요.",
      publishFailed: "게시하지 못했습니다. 내용을 확인한 뒤 다시 시도해 주세요.",
    },
  ),
  "admin.operations": page(
    "회원·상담 운영 | 농협지원센터",
    "관리자가 회원, 상담, 포인트와 운영 업무를 처리하는 화면입니다.",
    [
      section({
        id: "navigation",
        title: "운영 업무 메뉴",
        description: "운영 화면의 메뉴 이름과 공통 안내를 관리합니다.",
        locked: true,
        text: {
          overviewDescription: "운영 지표 한눈에 보기",
          membersDescription: "회원 및 운영자 계정 관리",
          inquiriesDescription: "문의 접수와 답변 처리",
          auditQuotesDescription: "FY27 회계감사 견적 접수 운영",
          pointsDescription: "농협 지갑과 포인트 정산",
          auditDescription: "주요 변경 이력",
          navigationAriaLabel: "관리자 콘솔 내비게이션",
          brandName: "농협지원센터",
          brandSubtitle: "회원·상담 운영",
          operatorRole: "운영자 · 슈퍼관리자",
          backToContent: "콘텐츠 관리로 돌아가기",
          logout: "로그아웃",
          breadcrumbPrefix: "운영 관리",
          lastSynced: "마지막 동기화",
          refresh: "새로고침",
          refreshing: "새로고침 중...",
          closeAriaLabel: "닫기",
          justNow: "방금 전",
          minuteAgoSuffix: "분 전",
          hourAgoSuffix: "시간 전",
          dayAgoSuffix: "일 전",
        },
        items: [
          item("overview", "운영 대시보드"),
          item("members", "회원 관리"),
          item("inquiries", "상담 관리"),
          item("auditQuotes", "회계감사 견적"),
          item("points", "포인트 관리"),
          item("audit", "운영 작업 기록"),
        ],
      }),
      section({
        id: "overview",
        title: "운영 현황",
        description: "주요 운영 지표와 최근 활동을 표시합니다.",
        locked: true,
        text: {
          memberKpi: "가입 회원",
          requestKpi: "문의 접수",
          answerKpi: "등록 답변",
          ratingKpi: "고객 평가",
          peopleUnit: "명",
          countUnit: "건",
          helpfulPrefix: "도움됨",
          trendTitle: "운영 추이",
          trendDescription: "최근 14일간 회원가입 · 문의 · 답변 흐름",
          signupLegend: "가입",
          inquiryLegend: "문의",
          answerLegend: "답변",
          metricsTitle: "주요 지표",
          metricsDescription: "응답률과 포인트 사용을 한눈에",
          answerRate: "답변률",
          activeOrganizations: "활성 농협",
          walletOrganizations: "지갑 보유 조직",
          totalWalletBalance: "전체 지갑 잔액",
          organizationTotalSuffix: "개 조직 합계",
          recentSpend: "최근 30일 사용",
          recentSpendHelp: "답변 열람 · 운영자 차감",
          recentActivityTitle: "최근 활동",
          recentActivityDescription: "운영자 작업 · 시스템 변경 이력",
          viewAll: "전체 보기 →",
          targetLabel: "대상",
          actorLabel: "작업자",
          occurredAtLabel: "발생 시각",
          noActivity: "기록된 활동이 없습니다.",
          topOrganizationsTitle: "문의 상위 농협",
          topOrganizationsDescription: "접수 건수 기준 Top 6",
          noData: "데이터 없음",
          recentPeriod: "최근 7일",
          previousPeriod: "이전",
        },
      }),
      section({
        id: "members",
        title: "회원 관리",
        description: "회원과 운영자 목록, 상세 정보와 상태 변경 안내를 관리합니다.",
        locked: true,
        text: {
          subtabsAriaLabel: "회원 및 운영자 관리 보기",
          memberTabDescription: "가입 승인, 회원 상태, 소속 농협과 포인트 정보를 관리합니다.",
          operatorTabDescription: "운영자 계정, 권한, 비밀번호와 삭제 이력을 관리합니다.",
          memberListTitle: "회원 목록",
          memberListSuffix: "명 · 최근 가입 순",
          memberSearchPlaceholder: "이름, 이메일, 농협, 직책 검색",
          memberColumn: "회원",
          organizationColumn: "소속 농협",
          roleColumn: "직책 · 담당",
          statusColumn: "상태",
          marketingColumn: "마케팅",
          joinedColumn: "가입일",
          memberDetailAriaSuffix: "회원 상세 보기",
          unnamed: "이름 미입력",
          unspecified: "미지정",
          organizationCode: "농협 코드",
          organizationCodeMissing: "농협 코드 미지정",
          optedOut: "수신 거부",
          memberEmpty: "조건에 맞는 회원이 없습니다.",
          operatorListTitle: "운영자 목록",
          operatorListSuffix: "명 · 권한 상태 관리",
          operatorSearchPlaceholder: "이름, 이메일, 역할 검색",
          addOperator: "운영자 추가",
          operatorColumn: "운영자",
          permissionColumn: "권한 상태",
          updatedColumn: "최근 수정",
          operatorDetailAriaSuffix: "운영자 상세 보기",
          operatorRoleFallback: "운영자",
          administratorFallback: "관리자",
          permissionGranted: "권한 부여",
          permissionRevoked: "권한 회수",
          operatorEmpty: "조건에 맞는 운영자가 없습니다.",
          memberDetailTitle: "회원 상세",
          selectMember: "왼쪽 목록에서 회원을 선택하세요.",
          noMemberSelected: "선택된 회원이 없습니다.",
          operatorDetailTitle: "운영자 상세",
          selectOperator: "왼쪽 목록에서 운영자를 선택하세요.",
          noOperatorSelected: "선택된 운영자가 없습니다.",
          basicInfoTitle: "회원 기본 정보",
          organizationInfoTitle: "소속 농협 정보",
          walletInfoTitle: "포인트/지갑 정보",
          consentInfoTitle: "동의 및 마케팅 수신 상태",
          relatedHistoryTitle: "관련 운영 이력",
          noRelatedHistory: "관련 이력이 없습니다.",
          approveMember: "가입 승인하기",
          rejectMember: "가입 거절",
          deactivateMember: "회원 비활성화",
          reactivateMember: "회원 재활성화",
          editOperator: "정보 수정",
          resetPassword: "비밀번호 재설정",
          deleteAccount: "계정 삭제",
          memberFallback: "회원",
          statusActive: "활성",
          statusPending: "가입 승인 대기",
          statusPendingShort: "승인 대기",
          statusInactive: "비활성",
          emailChannel: "이메일",
          smsChannel: "SMS",
          kakaoChannel: "카카오톡",
          marketingChannel: "마케팅",
          termsConsent: "이용약관",
          privacyConsent: "개인정보",
          receivedChannelsLabel: "수신 채널",
          nameLabel: "이름",
          emailLabel: "이메일",
          phoneLabel: "휴대폰",
          positionLabel: "직책",
          dutyLabel: "담당업무",
          createdAtLabel: "생성일",
          joinedAtLabel: "가입일",
          modifiedAtLabel: "수정일",
          businessCardLabel: "명함",
          approvalTitle: "가입 처리",
          approvalDescription: "소속 농협과 가입 정보를 확인한 뒤 승인하면 로그인 및 문의 작성이 가능해지고 가입 혜택 포인트가 지급됩니다. 정보가 부적절한 경우 가입을 거절하면 회원이 비활성 상태로 전환됩니다.",
          approvalCardTitle: "가입 승인 명함",
          approvalCardDescription: "회원가입 시 업로드한 직원 인증 파일입니다.",
          memberStatusTitle: "회원 상태 관리",
          memberStatusDescription: "퇴사·문제 계정·오등록 등 즉시 접근을 차단해야 하는 경우 회원을 비활성으로 전환할 수 있습니다. 처리 전 확인 창이 표시됩니다.",
          inactiveMemberTitle: "비활성 회원",
          inactiveMemberDescription: "관리자가 비활성으로 전환한 회원입니다.",
          reasonPrefix: "사유",
          organizationNameLabel: "농협명",
          organizationCodeLabel: "농협 코드",
          organizationIdLabel: "조직 코드",
          organizationMemberCountLabel: "조직 회원 수",
          organizationCreatedAtLabel: "조직 등록일",
          walletBalanceLabel: "지갑 잔액",
          signupPointsLabel: "가입 지급 포인트",
          recentTransactionLabel: "최근 거래",
          noTransaction: "내역 없음",
          recentPointsTitle: "최근 포인트 내역",
          noPoints: "포인트 내역이 없습니다.",
          operatorAccountTitle: "운영자 계정 정보",
          permissionGroupLabel: "권한 그룹",
          operatorActionsTitle: "운영자 계정 작업",
          operatorActionsDescription: "계정 정보, 권한, 비밀번호, 삭제 작업은 감사 로그에 기록됩니다.",
          protectedOperatorDescription: "현재 계정 또는 기본 관리자 계정은 권한 회수와 삭제가 제한됩니다.",
          noBusinessCard: "첨부 없음",
          businessCardLoading: "명함 불러오는 중...",
          businessCardError: "명함을 불러오지 못했습니다.",
          businessCardAltSuffix: "명함",
          pdfBusinessCard: "PDF 명함 파일",
          viewOriginal: "원본 보기",
          openPdf: "PDF 열기",
          operatorEditorAriaLabel: "운영자 계정 편집",
          operatorEditorEyebrow: "운영자 관리",
          operatorEditorCreateTitle: "운영자 추가",
          operatorEditorEditTitle: "운영자 정보 수정",
          permissionStatusLabel: "권한 상태",
          temporaryPasswordLabel: "임시 비밀번호",
          newPasswordLabel: "새 비밀번호",
          temporaryPasswordPlaceholder: "8자 이상 입력",
          newPasswordPlaceholder: "변경 시에만 입력",
          operatorRequiredError: "이름과 이메일을 입력해 주세요.",
          operatorCreatePasswordError: "새 운영자의 임시 비밀번호는 8자 이상이어야 합니다.",
          operatorEditPasswordError: "비밀번호를 변경하려면 8자 이상 입력해 주세요.",
          memberActionEyebrow: "회원 상태 변경",
          targetMemberTitle: "대상 회원",
          accountRestrictionWarning: "계정 접근이 즉시 제한됩니다. 변경 내역은 감사 로그에 기록됩니다.",
          reasonLabel: "사유",
          approveTitle: "가입 승인",
          approveIntro: "이 회원의 가입을 승인하면 로그인 및 문의 작성이 가능해지고 가입 혜택 포인트가 지급됩니다.",
          approveConfirm: "가입 승인",
          rejectTitle: "가입 거절",
          rejectIntro: "이 회원의 가입을 거절하면 회원 상태가 비활성으로 전환됩니다. 변경 즉시 서비스 이용이 제한됩니다.",
          rejectConfirm: "가입 거절",
          rejectReasonLabel: "거절 사유 (선택)",
          rejectReasonPlaceholder: "예) 소속 농협 정보 확인 불가",
          deactivateTitle: "회원 비활성화",
          deactivateIntro: "이 회원을 비활성으로 전환하면 즉시 로그인·문의 작성·마이페이지 이용이 제한됩니다. 실수로 처리하지 않도록 내용을 확인한 뒤 진행해 주세요.",
          deactivateConfirm: "비활성으로 전환",
          deactivateReasonLabel: "비활성 사유 (선택)",
          deactivateReasonPlaceholder: "예) 퇴사 처리, 오등록 계정 정리",
          reactivateTitle: "회원 재활성화",
          reactivateIntro: "비활성 상태를 해제하고 활성 회원으로 되돌립니다. 재활성화 후 다시 로그인하여 서비스를 이용할 수 있습니다.",
          reactivateConfirm: "재활성화",
        },
        items: [
          item("members", "회원 관리"),
          item("operators", "운영자 관리"),
        ],
      }),
      section({
        id: "inquiries",
        title: "문의와 FAQ 관리",
        description: "상담 답변과 FAQ 노출 내용을 관리합니다.",
        locked: true,
        text: {
          subtabsAriaLabel: "문의 영역 보기",
          requestTabDescription: "접수된 상담을 확인하고 답변을 등록합니다.",
          faqTabDescription: "홈페이지에 노출되는 자주 묻는 질문을 관리합니다.",
          requestListTitle: "상담 · 견적 요청",
          totalPrefix: "전체",
          filteredPrefix: "필터 적용 결과",
          searchPrefix: "검색",
          sortHint: "정렬: 답변 대기 우선, 접수일 오래된 순",
          unifiedSearch: "통합 검색",
          requestSearchPlaceholder: "접수번호 / 문의 제목 / 작성자 / 담당자 검색",
          requestSearchAriaLabel: "접수번호, 문의 제목, 작성자, 담당자 통합 검색",
          clearSearchAriaLabel: "검색어 지우기",
          clearSearch: "지우기",
          allOrganizations: "전체 농협",
          referenceTitleColumn: "접수번호 · 제목",
          authorOrganizationColumn: "작성자 · 농협",
          visibilityColumn: "공개범위",
          statusColumn: "상태",
          assigneeColumn: "담당자",
          usedPointsColumn: "사용 포인트",
          ratingColumn: "고객 평가",
          receivedAtColumn: "접수일",
          answeredAtColumn: "답변일",
          actionColumnAriaLabel: "작업",
          attachmentPrefix: "첨부",
          followupPrefix: "추가 질문 · 원 문의",
          additionalAssigneePrefix: "외",
          unassigned: "미배정",
          finalAnswer: "최종 답변",
          answerComplete: "답변 완료",
          editAnswer: "답변 수정",
          writeAnswer: "답변 작성",
          inquiryEmpty: "조건에 맞는 문의가 없습니다.",
          faqTitle: "FAQ 관리",
          faqDescription: "홈페이지 자주 묻는 질문 영역에 노출되는 콘텐츠를 관리합니다.",
          faqSearchPlaceholder: "제목, 카테고리, 본문 검색",
          faqSearchAriaLabel: "FAQ 검색",
          faqCategoryAriaLabel: "FAQ 카테고리",
          faqPublicAriaLabel: "FAQ 공개 여부",
          faqDisplayAriaLabel: "FAQ 노출 상태",
          addFaq: "+ FAQ 추가",
          faqQuestionColumn: "제목",
          faqCategoryColumn: "카테고리",
          faqPublicColumn: "공개 여부",
          faqDisplayColumn: "노출 상태",
          faqUpdatedColumn: "최종 수정일",
          faqManagerColumn: "담당자",
          faqLoading: "FAQ를 불러오는 중입니다...",
          faqEmpty: "등록된 FAQ가 없습니다. 우측 상단의 “+ FAQ 추가” 버튼으로 작성해 주세요.",
          faqFilteredEmpty: "검색 조건에 맞는 FAQ가 없습니다.",
          edit: "수정",
          delete: "삭제",
          countUnit: "건",
          attachmentUnit: "장",
          peopleUnit: "명",
          detailAriaSuffix: "문의와 답변 상세 보기",
          allCategories: "전체 카테고리",
          ratingWaitingAriaLabel: "고객 평가 대기 · 상세 보기",
          ratingWaiting: "평가 대기",
          ratingCompleteAriaPrefix: "고객 평가 상세 보기 · 평가완료",
          ratingComplete: "평가완료",
          ratingDetailTitle: "고객 평가 상세",
          ratingEmpty: "아직 고객 평가가 등록되지 않았습니다.",
          satisfactionLabel: "만족도",
          satisfactionGood: "만족",
          satisfactionAverage: "보통",
          satisfactionLow: "불만족",
          consultationStatusLabel: "상담 종료",
          consultationCompleted: "완료 (평가 후 종료)",
          consultationInProgress: "진행 중",
          helpfulLabel: "도움 여부",
          helpfulYes: "도움 됨",
          helpfulNo: "도움 안 됨",
          noResponse: "미응답",
          additionalCommentTitle: "추가 의견",
          noAdditionalComment: "등록된 추가 의견이 없습니다.",
          answerSummaryTitle: "답변 요약",
          noAnswer: "등록된 답변이 없습니다.",
          answerDetailAriaLabel: "문의 및 답변 상세",
          answerDetailTitle: "문의 · 답변 상세",
          authorLabel: "작성자",
          customerInquiryTitle: "고객 문의",
          supportFieldLabel: "지원 분야",
          answerBodyTitle: "답변 내용",
          inquiryTypeLabel: "고객 문의 유형",
          autoInquiryDescription: "자동 배정 문의입니다. 답변 등록 시 실제 지원 분야를 선택해 주세요.",
          selectedInquiryDescription: "고객이 선택한 유형입니다. 필요 시 아래에서 지원 분야를 조정할 수 있습니다.",
          supportAssignmentLabel: "지원 분야 배정",
          selectAutoSupportField: "지원 분야를 선택해 주세요",
          selectSupportField: "지원 분야 선택",
          legacySupportSuffix: "(기존 지정)",
          supportAssignmentHelp: "실제 상담·견적 처리 분야를 지정합니다. 담당자 정보와 별도로 관리됩니다.",
          assigneePlaceholder: "답변 담당자명을 입력하세요",
          assigneeHelp: "이력 추적을 위해 필수입니다. 복수 담당자는 쉼표(,)로 구분해 입력해 주세요.",
          answerPointsLabel: "답변 포인트",
          pointMinimumJoin: "이상",
          pointMaximumJoin: "이하",
          pointRangeErrorPrefix: "답변 포인트는",
          pointRangeErrorSuffix: "범위로 입력해 주세요.",
          pointRangeHelpSuffix: "로 입력해 주세요. 숫자 입력 시 천 단위마다 자동으로 콤마가 표시됩니다.",
          answerPlaceholder: "고객에게 제공할 답변을 입력하세요.",
          updateAnswer: "답변 업데이트",
          registerAnswer: "답변 등록",
          ratingScaleSuffix: "/ 5.0",
        },
        items: [
          item("requests", "문의 관리"),
          item("faq", "FAQ 관리"),
          item("visibility.all", "전체 공개범위"),
          item("visibility.public", "전체 공개"),
          item("visibility.organization", "농협 공개"),
          item("visibility.private", "비공개"),
          item("requestStatus.all", "전체 상태"),
          item("requestStatus.submitted", "답변 대기"),
          item("requestStatus.answered", "답변 완료"),
          item("requestStatus.published", "답변 열람"),
          item("requestStatus.followup", "추가 문의"),
          item("requestStatus.completed", "상담 종료"),
          item("faqPublic.all", "전체 공개 여부"),
          item("faqPublic.public", "공개"),
          item("faqPublic.private", "비공개"),
          item("faqDisplay.all", "전체 노출 상태"),
          item("faqDisplay.published", "노출 중"),
          item("faqDisplay.draft", "임시 저장"),
          item("faqCategory.general", "일반"),
          item("faqCategory.signup", "회원가입"),
          item("faqCategory.inquiry", "문의 진행"),
          item("faqCategory.points", "포인트"),
          item("faqCategory.settlement", "정산"),
          item("faqCategory.other", "기타"),
        ],
      }),
      section({
        id: "auditQuotes",
        title: "회계감사 견적 관리",
        description: "회계감사 견적 접수 목록과 권한 있는 상세 화면의 표시 문구입니다.",
        locked: true,
        text: {
          receivedPrefix: "미처리",
          receivedSuffix: "건 · 목록은 이메일 마스킹, 상세에서만 원문 확인",
          statusFilter: "상태 필터",
          refresh: "새로고침",
          refreshing: "불러오는 중...",
          referenceColumn: "접수번호",
          contactColumn: "담당자",
          emailColumn: "이메일",
          statusColumn: "상태",
          quoteCountColumn: "견적수",
          assigneeColumn: "담당",
          receivedAtColumn: "접수시각",
          empty: "조건에 맞는 접수가 없습니다.",
          detailTitle: "상세",
          detailDescription: "권한 있는 운영자만 원문 이메일을 확인합니다.",
          selectDetail: "목록에서 접수를 선택하세요.",
          detailLoading: "상세를 불러오는 중...",
          contactName: "담당자 이름",
          phone: "휴대폰 번호",
          originalEmail: "원문 이메일",
          campaign: "캠페인",
          marketingConsent: "마케팅 동의",
          agreed: "동의",
          notAgreed: "미동의",
          status: "상태",
          assignee: "담당자",
          assigneePlaceholder: "담당자 이메일 또는 이름",
          quoteCount: "견적 수",
          save: "저장",
          saving: "저장 중...",
          retryNotification: "알림 재시도",
        },
        items: [
          item("status.all", "전체"),
          item("status.received", "접수"),
          item("status.contacting", "연락 중"),
          item("status.qualified", "요건 확인"),
          item("status.infoComplete", "정보 완료"),
          item("status.quotesRequested", "견적 요청"),
          item("status.delivered", "견적 전달"),
          item("status.reportDelivered", "검토보고서 전달"),
          item("status.closed", "종료"),
          item("status.invalid", "무효"),
        ],
      }),
      section({
        id: "points",
        title: "포인트 관리",
        description: "농협 지갑, 수동 조정과 거래 내역 표시 문구입니다.",
        locked: true,
        text: {
          walletListTitle: "농협 지갑 목록",
          searchPrefix: "검색",
          totalBalancePrefix: "합계",
          allTransactions: "전체 거래 내역 보기",
          walletSearchPlaceholder: "농협명 또는 조직 ID 검색",
          walletSearchAriaLabel: "농협 지갑 검색",
          organizationColumn: "농협",
          memberCountColumn: "회원 수",
          balanceColumn: "잔액",
          updatedColumn: "최근 업데이트",
          pointDetailAriaSuffix: "포인트 상세 보기",
          organizationCode: "농협 코드",
          walletEmpty: "등록된 농협 지갑이 없습니다.",
          walletFilteredEmpty: "검색 조건에 맞는 농협이 없습니다.",
          selectedDetailTitle: "선택 농협 상세",
          selectedDetailSuffix: "잔액 확인 · 조정 · 거래 내역",
          selectOrganization: "왼쪽 목록에서 농협을 선택하세요.",
          currentBalance: "현재 잔액",
          organizationMembers: "소속 회원",
          manualAdjustmentTitle: "포인트 수동 조정",
          adjustmentHelp: "적립은 양수, 차감은 음수로 입력해 주세요.",
          targetOrganization: "대상 농협",
          searchResultsAriaLabel: "농협 검색 결과",
          currentWalletBalance: "현재 지갑 잔액",
          adjustmentPoints: "조정 포인트",
          adjustmentPlaceholder: "예: 10,000 또는 -10,000",
          commaHelp: "천 단위 콤마가 자동으로 표시됩니다.",
          reason: "사유",
          reasonPlaceholder: "조정 사유를 입력하세요",
          expectedBalance: "조정 후 예상 잔액",
          reviewAdjustment: "조정 내용 확인",
          recentTransactions: "최근 거래 내역",
          moreTransactions: "이 농협 거래 더 보기",
          transactionTimeColumn: "발생 시각",
          targetColumn: "대상 농협",
          eventColumn: "이벤트",
          changeColumn: "변화",
          transactionBalanceColumn: "잔액",
          reasonColumn: "사유",
          transactionEmpty: "거래 내역이 없습니다.",
          allTransactionsAriaLabel: "전체 포인트 거래 내역",
          transactionLogEyebrow: "포인트 거래 로그",
          allTransactionsTitle: "전체 거래 내역",
          displayedPrefix: "표시",
          transactionFilterAriaLabel: "농협별 거래 필터",
          organizationUnit: "개",
          peopleUnit: "명",
          countUnit: "건",
          negativeBalanceWarning: "조정 후 잔액이 0 미만입니다. 금액을 다시 확인해 주세요.",
          adjustmentReasonTitle: "조정 사유",
          pointUnit: "P",
        },
        items: [
          item("ledger.firstOrgSignup", "농협 최초 가입 보너스"),
          item("ledger.userSignup", "회원 가입 적립"),
          item("ledger.answerView", "답변 열람 사용"),
          item("ledger.questionAnswerUsage", "답변 열람 사용"),
          item("ledger.manualAdjustment", "수동 조정"),
          item("ledger.adminCredit", "운영자 적립"),
          item("ledger.adminDebit", "운영자 차감"),
        ],
      }),
      section({
        id: "auditLog",
        title: "운영 기록",
        description: "운영자가 수행한 작업 기록을 표시합니다.",
        locked: true,
        text: {
          title: "감사 로그",
          recentPrefix: "최근",
          recentSuffix: "건의 운영자 활동",
          activityColumn: "활동명",
          targetColumn: "대상",
          actorColumn: "작업자",
          occurredAtColumn: "발생 시각",
          empty: "기록된 로그가 없습니다.",
        },
      }),
      section({
        id: "dialogs",
        title: "확인 창과 작업 안내",
        description: "상세, 편집, 확인 창에서 사용하는 공통 표시 문구입니다.",
        locked: true,
        text: {
          close: "닫기",
          cancel: "취소",
          save: "저장",
          saving: "저장 중...",
          processing: "처리 중...",
          confirm: "확인",
          faqEditorTitle: "자주 묻는 질문 콘텐츠 관리",
          faqEditorDescription: "홈페이지 FAQ 영역에 노출되는 내용을 작성합니다. 노출 상태를 임시 저장으로 두면 고객 화면에는 표시되지 않습니다.",
          faqCreate: "FAQ 등록",
          faqEdit: "FAQ 수정",
          faqQuestion: "제목",
          faqQuestionPlaceholder: "예) 회원가입할 때 농협은 어떻게 선택하나요?",
          faqCategory: "카테고리",
          faqPublic: "공개 여부",
          faqDisplay: "노출 상태",
          faqBody: "본문",
          faqBodyPlaceholder: "고객에게 보여줄 답변 본문을 입력하세요.",
          faqValidation: "제목과 본문을 모두 입력해 주세요.",
          faqSaveChanges: "변경 저장",
          pointConfirmAriaLabel: "포인트 조정 확인",
          pointConfirmTitle: "포인트 조정 확인",
          pointConfirmDescription: "아래 내용으로 지갑 잔액을 조정합니다. 실행 후 포인트 원장과 감사 로그에 기록됩니다.",
          adjustmentAmount: "조정 금액",
          executeAdjustment: "포인트 조정 실행",
          passwordDialogTitle: "운영자 비밀번호 재설정",
          passwordDialogDescription: "새 임시 비밀번호를 입력하세요. 8자 이상이어야 합니다.",
          passwordLabel: "새 임시 비밀번호",
          passwordPlaceholder: "8자 이상 입력",
          resetPassword: "비밀번호 재설정",
          permissionDialogTitle: "운영자 권한 변경",
          deleteOperatorDialogTitle: "운영자 계정 삭제",
          deleteFaqDialogTitle: "FAQ 삭제",
          irreversibleWarning: "이 작업은 되돌릴 수 없습니다.",
        },
      }),
    ],
    {
      loading: "관리자 운영 화면을 준비하고 있습니다.",
      loadingDescription: "인증 정보와 운영 자료 접근 권한을 확인 중입니다.",
      denied: "관리자 권한이 필요합니다.",
      deniedDescription: "관리자 권한이 부여된 계정으로만 접근할 수 있습니다.",
      loginAgain: "관리자 계정으로 다시 로그인",
      empty: "표시할 운영 자료가 없습니다.",
      genericError: "운영 정보를 불러오지 못했습니다.",
      retry: "다시 시도",
      saved: "변경사항을 저장했습니다.",
      authRequired: "로그인이 필요합니다.",
      refreshed: "데이터를 새로 불러왔습니다.",
      refreshFailed: "새로고침에 실패했습니다.",
      faqLoadFailed: "FAQ를 불러오지 못했습니다.",
      faqSaved: "FAQ를 등록했습니다.",
      faqUpdated: "FAQ를 수정했습니다.",
      faqSaveFailed: "FAQ 저장에 실패했습니다.",
      faqDeleted: "FAQ를 삭제했습니다.",
      faqDeleteFailed: "FAQ 삭제에 실패했습니다.",
      answerSaved: "답변이 저장되었습니다.",
      answerSaveFailed: "답변 등록에 실패했습니다.",
      assigneeRequired: "담당자를 입력해야 답변을 등록할 수 있습니다.",
      pointFieldsRequired: "조정 포인트와 사유를 입력해 주세요.",
      negativeBalance: "조정 후 잔액이 음수가 될 수 없습니다.",
      pointAdjusted: "포인트가 조정되었습니다.",
      pointAdjustmentFailed: "포인트 조정에 실패했습니다.",
      memberStatusFailed: "회원 상태 변경에 실패했습니다.",
      memberAlreadyActive: "이미 활성화된 회원입니다.",
      memberReactivated: "회원이 활성 상태로 재활성화되었습니다.",
      memberApproved: "회원 승인이 완료되었습니다.",
      memberAlreadyInactive: "이미 비활성 상태인 회원입니다.",
      memberDeactivated: "회원을 비활성 상태로 전환했습니다.",
      memberRejected: "가입을 거절했습니다. 회원 상태가 비활성으로 전환되었습니다.",
      operatorSaved: "운영자 계정을 추가했습니다.",
      operatorUpdated: "운영자 정보를 수정했습니다.",
      operatorSaveFailed: "운영자 계정 저장에 실패했습니다.",
      operatorPermissionGranted: "운영자 권한을 부여했습니다.",
      operatorPermissionRevoked: "운영자 권한을 회수했습니다.",
      operatorPermissionFailed: "운영자 권한 변경에 실패했습니다.",
      passwordTooShort: "비밀번호는 8자 이상이어야 합니다.",
      passwordReset: "운영자 비밀번호를 재설정했습니다.",
      passwordResetFailed: "비밀번호 재설정에 실패했습니다.",
      operatorDeleted: "운영자 계정을 삭제했습니다.",
      operatorDeleteFailed: "운영자 계정 삭제에 실패했습니다.",
      auditQuoteListFailed: "견적 접수 목록을 불러오지 못했습니다.",
      auditQuoteDetailFailed: "상세 정보를 불러오지 못했습니다.",
      auditQuoteSaved: "접수 정보를 저장했습니다.",
      auditQuoteConflict: "다른 담당자가 먼저 수정했습니다. 다시 불러온 뒤 저장해 주세요.",
      auditQuoteInvalidTransition: "허용되지 않은 상태 변경입니다.",
      auditQuoteSaveFailed: "저장에 실패했습니다.",
      auditQuoteNotifySuccess: "알림 상태: {status} (시도 {attempts})",
      auditQuoteNotifyFailed: "알림 재시도에 실패했습니다.",
    },
  ),
  "framework.notFound": page(
    "페이지를 찾을 수 없습니다 | 농협지원센터",
    "요청한 페이지를 찾을 수 없습니다.",
    [
      section({
        id: "notFound",
        eyebrow: "404",
        title: "페이지를 찾을 수 없습니다",
        description: "주소를 확인하거나 홈으로 이동해 주세요.",
        actions: [action("home", "홈으로 이동", "/")],
      }),
    ],
  ),
};

export const CMS_REQUIRED_PAGE_SECTIONS: Record<CmsPageKey, readonly string[]> =
  CMS_PAGE_KEYS.reduce<Record<CmsPageKey, readonly string[]>>(
    (result, pageKey) => {
      result[pageKey] = CMS_PAGE_DEFAULTS[pageKey].sections
        .filter((value) => value.locked)
        .map((value) => value.id);
      return result;
    },
    {} as Record<CmsPageKey, readonly string[]>,
  );

export const CMS_PROTECTED_PAGE_ITEM_IDS: Partial<
  Record<CmsPageKey, Record<string, readonly string[]>>
> = {
  "auth.signup": {
    work: [
      "accounting",
      "tax",
      "general",
      "hr",
      "audit",
      "member",
      "other",
    ],
  },
  "public.consult": {
    categorySelector: [
      "auto",
      "tax",
      "accounting",
      "legal",
      "labor",
      "registration",
      "appraisal",
      "ip",
      "customs",
      "audit",
    ],
    visibilitySelector: ["public", "organization", "private"],
  },
};

export const CMS_PROTECTED_PAGE_ACTION_IDS: Partial<
  Record<CmsPageKey, Record<string, readonly string[]>>
> = {
  "auth.signup": {
    consents: ["terms", "privacy"],
  },
};

const globalContent = (
  input: Partial<CmsGlobalContent>,
): CmsGlobalContent => ({
  text: {},
  links: {},
  navigation: [],
  sections: [],
  ...input,
});

export const CMS_GLOBAL_DEFAULTS: Record<CmsGlobalKey, CmsGlobalContent> = {
  siteIdentity: globalContent({
    text: {
      serviceName: "농협지원센터",
      poweredBy: "Powered by Prego",
      logoAlt: "프리고",
      homeAriaLabel: "농협지원센터 홈",
    },
    sections: [
      section({
        id: "brand",
        title: "서비스 로고",
        locked: true,
      }),
    ],
  }),
  header: globalContent({
    navigation: [
      { ...action("about", "센터소개", "/#about", "text"), children: [] },
      { ...action("expertise", "전문성", "/#expertise", "text"), children: [] },
      { ...action("services", "지원분야", "/#services", "text"), children: [] },
      { ...action("process", "상담흐름", "/#process", "text"), children: [] },
      { ...action("inquiries", "문의게시판", "/inquiries", "text"), children: [] },
      { ...action("faq", "FAQ", "/#faq", "text"), children: [] },
    ],
    links: {
      consult: action("consult", "상담·견적 요청", "/consult"),
      login: action("login", "로그인", "/login", "text"),
      signup: action("signup", "회원가입", "/signup", "secondary"),
      mypage: action("mypage", "마이페이지", "/mypage", "text"),
    },
    text: {
      mainNavigationLabel: "주요 메뉴",
      mobileNavigationLabel: "모바일 메뉴",
      openMenuLabel: "메뉴 열기",
      closeMenuLabel: "메뉴 닫기",
    },
  }),
  footer: globalContent({
    text: {
      brandName: "농협지원센터 · 주식회사 프리고",
      brandTagline: "농협 전문 상담 · 전문가 연결 플랫폼",
      operatorHeading: "운영 주체",
      operatorName: "주식회사 프리고",
      serviceLabel: "서비스명: 농협지원센터",
      policyHeading: "정책",
      privacyOfficer: "개인정보 보호책임자 김지혜",
      contactHeading: "문의",
      copyright: "© 2026 Prego Inc. · 농협지원센터.",
    },
    links: {
      terms: action("terms", "이용약관", "/terms", "text"),
      privacy: action("privacy", "개인정보처리방침", "/privacy", "text"),
      consult: action("consult", "고객문의", "/consult", "text"),
      inquiries: action("inquiries", "문의게시판", "/inquiries", "text"),
      about: action("about", "소개", "/#about", "text"),
      signup: action("signup", "회원가입", "/signup", "text"),
      mypage: action("mypage", "마이페이지", "/mypage", "text"),
    },
  }),
  support: globalContent({
    text: {
      title: "고객지원",
      ariaLabel: "고객지원",
      description: "농협 업무 상담과 서비스 이용 문의를 도와드립니다.",
    },
    links: {
      support: action("support", "고객지원", "/support"),
    },
  }),
  defaultSeo: globalContent({
    text: {
      title: "농협지원센터 · 주식회사 프리고",
      description:
        "농협 대상 상담 접수·분류·전문가 연결 플랫폼. 세무·노무·감사·회계 일반 문의를 안전하게 분류하고 필요한 전문가에게 연결합니다.",
    },
  }),
  theme: globalContent({
    theme: {
      palette: "default",
      textScale: "default",
      spacing: "default",
      radius: "default",
      alignment: "left",
    },
  }),
  statusMessages: globalContent({
    text: {
      loading: "잠시만 기다려 주세요.",
      empty: "표시할 내용이 없습니다.",
      error: "정보를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.",
      denied: "이 화면을 볼 권한이 없습니다.",
      saved: "저장되었습니다.",
    },
  }),
  adminPresentation: globalContent({
    text: {
      title: "관리자 콘솔",
      loading: "관리자 콘솔을 준비하고 있습니다.",
      denied: "관리자 권한이 필요합니다.",
      recovery: "기본 관리자 화면으로 열기",
    },
  }),
};

for (const pageKey of CMS_PAGE_KEYS) {
  cmsPageContentSchema.parse(CMS_PAGE_DEFAULTS[pageKey]);
}
for (const globalKey of CMS_GLOBAL_KEYS) {
  cmsGlobalContentSchema.parse(CMS_GLOBAL_DEFAULTS[globalKey]);
}

export function validatePageIdentity(
  pageKey: CmsPageKey,
  route: string,
  content: CmsPageContent,
) {
  if (route !== CMS_PAGE_ROUTES[pageKey]) {
    return { success: false as const, reason: "route_mismatch" as const };
  }
  const sectionIds = new Set(content.sections.map(({ id }) => id));
  const missingRequiredSection = CMS_REQUIRED_PAGE_SECTIONS[pageKey].find(
    (sectionId) => !sectionIds.has(sectionId),
  );
  if (missingRequiredSection) {
    return {
      success: false as const,
      reason: "required_section_missing" as const,
      sectionId: missingRequiredSection,
    };
  }
  const invalidRequiredSection = CMS_REQUIRED_PAGE_SECTIONS[pageKey].find(
    (sectionId) => {
      const section = content.sections.find(
        (candidate) => candidate.id === sectionId,
      );
      return !section?.visible || !section.locked;
    },
  );
  if (invalidRequiredSection) {
    return {
      success: false as const,
      reason: "required_section_unlocked_or_hidden" as const,
      sectionId: invalidRequiredSection,
    };
  }
  return { success: true as const };
}
