import type { CmsPageKey } from "@/lib/cms/constants";
import { CMS_PAGE_DEFAULTS } from "@/lib/cms/defaults";
import type { CmsHomeSectionPresentation } from "@/lib/cms/home-presentation";

const field = (label: string, help = "공개 화면에 표시되는 문구입니다.") => ({
  label,
  help,
});

export const CMS_ROUTE_SECTION_PRESENTATION: Partial<
  Record<CmsPageKey, Record<string, CmsHomeSectionPresentation>>
> = {
  "auth.login": {
    hero: {
      name: "로그인 첫 안내",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "큰 제목",
      descriptionLabel: "설명",
      textFields: { highlight: field("강조 문구") },
    },
    loginForm: {
      name: "로그인 입력 영역",
      eyebrowLabel: "카드 배지",
      titleLabel: "카드 제목",
      descriptionLabel: "카드 설명",
      textFields: {
        emailLabel: field("이메일 표시 이름"),
        emailPlaceholder: field("이메일 입력 예시"),
        passwordLabel: field("비밀번호 표시 이름"),
        passwordPlaceholder: field("비밀번호 입력 안내"),
        showPasswordLabel: field("비밀번호 보기 접근성 이름"),
        hidePasswordLabel: field("비밀번호 숨기기 접근성 이름"),
        showLabel: field("비밀번호 보기 버튼"),
        hideLabel: field("비밀번호 숨기기 버튼"),
        autoLoginLabel: field("자동 로그인 문구"),
        signupLabel: field("회원가입 링크 문구"),
        submitLabel: field("로그인 버튼"),
        submittingLabel: field("로그인 처리 중 문구"),
        hint: field("로그인 도움말"),
      },
    },
    recovery: {
      name: "아이디·비밀번호 찾기",
      titleLabel: "관리자 목록 이름",
      textFields: {
        ariaLabel: field("계정 찾기 접근성 이름"),
        findEmailLabel: field("아이디 찾기 버튼"),
        resetPasswordLabel: field("비밀번호 찾기 버튼"),
        nameLabel: field("이름 표시 이름"),
        namePlaceholder: field("이름 입력 예시"),
        phoneLabel: field("휴대폰 표시 이름"),
        phonePlaceholder: field("휴대폰 입력 예시"),
        findSubmitLabel: field("아이디 확인 버튼"),
        findingLabel: field("아이디 확인 중 문구"),
        resetEmailLabel: field("가입 이메일 표시 이름"),
        resetEmailPlaceholder: field("가입 이메일 입력 예시"),
        resetSubmitLabel: field("재설정 메일 버튼"),
        resettingLabel: field("메일 발송 중 문구"),
      },
    },
  },
  "auth.pendingApproval": {
    hero: {
      name: "승인 대기 첫 안내",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "큰 제목",
      descriptionLabel: "설명",
      textFields: { highlight: field("강조 문구") },
    },
    status: {
      name: "다시 로그인 안내",
      eyebrowLabel: "카드 배지",
      titleLabel: "카드 제목",
      descriptionLabel: "카드 설명",
    },
  },
  "auth.signup": {
    hero: {
      name: "회원가입 첫 안내와 단계",
      titleLabel: "큰 제목",
      descriptionLabel: "설명",
      textFields: { progressAriaLabel: field("가입 단계 접근성 이름") },
      itemFields: { title: "단계 이름" },
    },
    identity: {
      name: "기본 정보와 인증",
      titleLabel: "영역 제목",
      textFields: {
        nameLabel: field("이름 표시 이름"),
        namePlaceholder: field("이름 입력 안내"),
        phoneLabel: field("휴대폰 표시 이름"),
        phonePlaceholder: field("휴대폰 입력 안내"),
        verifiedNotice: field("휴대폰 인증 완료 안내"),
        verificationCodePlaceholder: field("인증번호 입력 안내"),
        verifyCodeLabel: field("인증 확인 버튼"),
        sendingLabel: field("인증번호 발송 중 문구"),
        resendLabel: field("인증번호 재발송 버튼"),
        sendLabel: field("인증번호 받기 버튼"),
        phoneLimitHelp: field("휴대폰 계정 제한 안내"),
        codeSentHelp: field("인증번호 발송 완료 도움말"),
        emailLabel: field("농협 이메일 표시 이름"),
        emailPlaceholder: field("농협 이메일 입력 안내"),
        checkingEmailLabel: field("이메일 확인 중 문구"),
        checkEmailLabel: field("이메일 중복확인 버튼"),
        emailAvailable: field("사용 가능한 이메일 안내"),
        passwordLabel: field("비밀번호 표시 이름"),
        passwordPlaceholder: field("비밀번호 입력 안내"),
        passwordConfirmLabel: field("비밀번호 확인 표시 이름"),
        passwordConfirmPlaceholder: field("비밀번호 확인 입력 안내"),
        showPasswordLabel: field("비밀번호 보기 접근성 이름"),
        hidePasswordLabel: field("비밀번호 숨기기 접근성 이름"),
      },
    },
    phoneVerification: {
      name: "휴대폰 인증 보호 설정",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "보호 안내",
    },
    organization: {
      name: "소속 농협 검색",
      titleLabel: "영역 제목",
      textFields: {
        searchLabel: field("농협 검색 표시 이름"),
        searchPlaceholder: field("농협 검색 입력 예시"),
        resultsAriaLabel: field("검색 결과 접근성 이름"),
        emptyPrefix: field("검색 결과 없음 앞 문구"),
        emptySuffix: field("검색 결과 없음 뒤 문구"),
        selectedPrefix: field("선택한 농협 앞 문구"),
      },
    },
    work: {
      name: "담당자 정보",
      titleLabel: "영역 제목",
      textFields: {
        positionLabel: field("직책 표시 이름"),
        positionPlaceholder: field("직책 입력 예시"),
        dutyLabel: field("담당업무 표시 이름"),
        dutyPlaceholder: field("담당업무 첫 선택 문구"),
      },
      itemFields: { title: "담당업무 표시 이름" },
    },
    businessCard: {
      name: "명함 첨부",
      titleLabel: "입력 표시 이름",
      descriptionLabel: "첨부 도움말",
      textFields: {
        changeLabel: field("파일 변경 버튼"),
        deleteLabel: field("파일 삭제 버튼"),
        uploadTitle: field("업로드 안내 제목"),
        uploadHelp: field("파일 형식·용량 안내"),
        selectLabel: field("파일 선택 버튼"),
        bytesUnit: field("바이트 단위"),
        kilobytesUnit: field("킬로바이트 단위"),
        megabytesUnit: field("메가바이트 단위"),
      },
    },
    consents: {
      name: "약관과 개인정보 동의",
      titleLabel: "영역 제목",
      legalWarning:
        "필수 약관과 개인정보 동의 여부, 내부 저장 키는 변경할 수 없습니다. 표시 문구 변경은 이력에 남습니다.",
      textFields: {
        allLabel: field("전체 동의 제목"),
        allHelp: field("전체 동의 설명"),
        requiredBadge: field("필수 배지"),
        optionalBadge: field("선택 배지"),
        termsLabel: field("이용약관 동의 문구"),
        termsLinkLabel: field("이용약관 보기 링크"),
        privacyLabel: field("개인정보 동의 문구"),
        privacyLinkLabel: field("개인정보 보기 링크"),
        marketingTitle: field("선택 수신 동의 제목"),
        marketingHelp: field("선택 수신 동의 설명"),
        marketingLabel: field("마케팅 수신 문구"),
        emailLabel: field("이메일 수신 문구"),
        smsLabel: field("문자 수신 문구"),
        kakaoLabel: field("카카오톡 수신 문구"),
      },
    },
    benefits: {
      name: "가입 혜택",
      titleLabel: "혜택 제목",
      itemFields: { title: "혜택 문구" },
    },
    submit: {
      name: "가입 신청 버튼",
      titleLabel: "관리자 목록 이름",
      textFields: {
        submitLabel: field("가입 신청 버튼"),
        submittingLabel: field("가입 처리 중 버튼"),
      },
    },
  },
  "legal.terms": {
    intro: {
      name: "약관 제목과 시행일",
      eyebrowLabel: "영문 안내",
      titleLabel: "약관 제목",
      descriptionLabel: "첫 안내",
      textFields: { effectiveDate: field("시행일") },
      legalWarning:
        "법적 필수 안내입니다. 숨기거나 삭제할 수 없으며 변경사항은 게시 이력에 남습니다.",
    },
    service: {
      name: "서비스 목적과 범위",
      titleLabel: "항목 제목",
      descriptionLabel: "약관 본문",
      legalWarning: "약관 본문 변경 전 운영·법률 검토를 권장합니다.",
    },
    account: {
      name: "회원 가입과 계정",
      titleLabel: "항목 제목",
      descriptionLabel: "약관 본문",
      legalWarning: "약관 본문 변경 전 운영·법률 검토를 권장합니다.",
    },
    content: {
      name: "문의와 공개 범위",
      titleLabel: "항목 제목",
      descriptionLabel: "약관 본문",
      legalWarning: "약관 본문 변경 전 운영·법률 검토를 권장합니다.",
    },
    responsibility: {
      name: "책임과 면책",
      titleLabel: "항목 제목",
      descriptionLabel: "약관 본문",
      legalWarning:
        "면책 문구는 숨기거나 삭제할 수 없습니다. 변경 전 법률 검토를 권장합니다.",
    },
    changes: {
      name: "약관 변경과 문의",
      titleLabel: "항목 제목",
      descriptionLabel: "약관 본문",
      legalWarning: "약관 본문 변경 전 운영·법률 검토를 권장합니다.",
    },
  },
  "legal.privacy": Object.fromEntries(
    [
      ["intro", "방침 제목과 시행일"],
      ["collection", "처리하는 개인정보"],
      ["purpose", "처리 목적"],
      ["retention", "보유 및 이용 기간"],
      ["sharing", "제3자 제공과 처리위탁"],
      ["rights", "이용자의 권리"],
      ["safeguards", "안전성 확보 조치"],
      ["officer", "보호책임자와 문의"],
    ].map(([id, name]) => [
      id,
      {
        name,
        eyebrowLabel: id === "intro" ? "영문 안내" : undefined,
        titleLabel: "항목 제목",
        descriptionLabel: "개인정보처리방침 본문",
        textFields:
          id === "intro" ? { effectiveDate: field("시행일") } : undefined,
        legalWarning:
          "개인정보 법적 안내입니다. 숨기거나 삭제할 수 없으며 변경사항은 게시 이력에 남습니다.",
      },
    ]),
  ),
  "public.support": {
    hero: {
      name: "고객지원 첫 안내",
      eyebrowLabel: "영문 안내",
      titleLabel: "큰 제목",
      descriptionLabel: "설명",
      textFields: { highlight: field("강조 문구") },
    },
    channels: {
      name: "문의 방법",
      eyebrowLabel: "카드 배지",
      titleLabel: "카드 제목",
      descriptionLabel: "이용 안내",
    },
  },
  "partner.portal": {
    accessNotice: {
      name: "협력 전문가 접근 안내",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "접근 제한 제목",
      descriptionLabel: "접근 제한 설명",
      legalWarning:
        "실제 파트너 인증과 배정 권한이 구현되기 전에는 운영 정보 화면을 공개할 수 없습니다.",
    },
  },
  "framework.notFound": {
    notFound: {
      name: "페이지 없음 안내",
      eyebrowLabel: "상태 번호",
      titleLabel: "안내 제목",
      descriptionLabel: "안내 설명",
    },
  },
  "public.consult": {
    steps: {
      name: "상담 진행 순서",
      eyebrowLabel: "영문 안내",
      titleLabel: "접근성 목록 이름",
      textFields: {
        ariaLabel: field("진행 순서 접근성 이름"),
        stepPrefix: field("단계 앞 문구"),
      },
      itemFields: {
        title: "단계 이름",
        description: "단계 설명",
      },
    },
    hero: {
      name: "문의 작성 첫 안내",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "큰 제목",
    },
    categorySelector: {
      name: "문의 유형 선택",
      titleLabel: "입력 표시 이름",
      descriptionLabel: "선택 도움말",
      textFields: { ariaLabel: field("접근성 이름") },
      itemFields: { title: "화면 표시 이름" },
    },
    visibilitySelector: {
      name: "공개 범위 선택",
      titleLabel: "입력 표시 이름",
      textFields: { ariaLabel: field("접근성 이름") },
      itemFields: {
        title: "화면 표시 이름",
        description: "선택 시 안내",
      },
    },
    requestFields: {
      name: "문의 내용과 첨부",
      titleLabel: "관리자 목록 이름",
      textFields: {
        followupNotice: field("후속 문의 안내"),
        subjectLabel: field("제목 표시 이름"),
        subjectPlaceholder: field("제목 입력 안내"),
        messageLabel: field("내용 표시 이름"),
        messagePlaceholder: field("내용 입력 안내"),
        photoLabel: field("사진 첨부 표시 이름"),
        optionalLabel: field("선택 배지"),
        photoButtonTitle: field("사진 추가 버튼"),
        photoHelp: field("사진 형식·용량 안내"),
        photoListAriaLabel: field("첨부 목록 접근성 이름"),
        deleteSuffix: field("첨부 삭제 접근성 문구"),
        bytesUnit: field("바이트 단위"),
        kilobytesUnit: field("킬로바이트 단위"),
        megabytesUnit: field("메가바이트 단위"),
        submitLabel: field("문의 등록 버튼"),
        submittingLabel: field("등록 처리 중 문구"),
      },
    },
    success: {
      name: "문의 접수 완료",
      titleLabel: "완료 제목",
      descriptionLabel: "완료 설명",
      textFields: {
        requestNumberLabel: field("접수번호 표시 이름"),
        resetLabel: field("새 문의 작성 버튼"),
      },
    },
  },
  "public.inquiries": {
    hero: {
      name: "문의 게시판 첫 안내",
      eyebrowLabel: "영문 안내",
      titleLabel: "큰 제목",
      descriptionLabel: "설명",
      textFields: { highlight: field("강조 문구") },
    },
    filters: {
      name: "검색과 목록 필터",
      titleLabel: "관리자 목록 이름",
      textFields: {
        boardAriaLabel: field("게시판 접근성 이름"),
        countPrefix: field("건수 앞 문구"),
        countSuffix: field("건수 뒤 문구"),
        allFilter: field("전체 문의 필터"),
        organizationFilter: field("우리 농협 문의 필터"),
        mineFilter: field("나의 문의 필터"),
        searchLabel: field("검색 표시 이름"),
        searchPlaceholder: field("검색 입력 안내"),
        filtersAriaLabel: field("필터 접근성 이름"),
        allGuestSummary: field("비회원 전체 목록 설명"),
        allMemberSummary: field("회원 전체 목록 설명"),
        organizationSummary: field("우리 농협 목록 설명"),
        mineSummary: field("나의 문의 목록 설명"),
      },
    },
    list: {
      name: "문의와 답변 목록",
      titleLabel: "관리자 목록 이름",
      textFields: {
        missingRequestNumber: field("접수번호 없음 안내"),
        requestHeading: field("문의 본문 제목"),
        answerHeading: field("답변 제목"),
        answerPending: field("답변 준비 중 안내"),
        lockedTitle: field("권한 제한 제목"),
        lockedDescription: field("권한 제한 설명"),
        loginLabel: field("로그인 이동 버튼"),
        visibilityPublic: field("전체 공개 배지"),
        visibilityOrganization: field("우리 농협 공개 배지"),
        visibilityPrivate: field("비공개 배지"),
        statusReceived: field("접수 완료 배지"),
        statusAnswered: field("답변 완료 배지"),
        statusCompleted: field("완료 배지"),
        statusFollowup: field("추가 문의 배지"),
        previewPublicSubject: field("미리보기 전체 공개 문의 제목"),
        previewPublicMessage: field("미리보기 전체 공개 문의 내용"),
        previewPublicAnswer: field("미리보기 답변 내용"),
        previewLockedSubject: field("미리보기 권한 제한 문의 제목"),
      },
    },
  },
  "public.faq": {
    hero: {
      name: "FAQ 첫 안내",
      eyebrowLabel: "영문 안내",
      titleLabel: "큰 제목",
      descriptionLabel: "설명",
      textFields: { highlight: field("강조 문구") },
    },
    filters: {
      name: "FAQ 검색과 유형",
      titleLabel: "관리자 목록 이름",
      textFields: {
        boardAriaLabel: field("FAQ 접근성 이름"),
        countPrefix: field("건수 앞 문구"),
        countSuffix: field("건수 뒤 문구"),
        summary: field("검색 도움말"),
        categoryLabel: field("유형 선택 표시 이름"),
        allCategoriesLabel: field("전체 유형 선택 문구"),
        searchLabel: field("검색 표시 이름"),
        searchPlaceholder: field("검색 입력 안내"),
      },
    },
    list: {
      name: "질문과 답변",
      titleLabel: "목록 이름",
      itemFields: {
        label: "질문 유형",
        title: "질문",
        description: "답변",
      },
    },
  },
  "member.mypage": {
    navigation: {
      name: "마이페이지 메뉴와 공통 안내",
      titleLabel: "관리자 목록 이름",
      legalWarning:
        "메뉴 연결값, 로그인 상태 확인과 이동 주소는 변경할 수 없습니다. 회원에게 보이는 이름과 안내만 편집됩니다.",
      textFields: Object.fromEntries(
        [
          ["navigationAriaLabel", "메뉴 접근성 이름"],
          ["brandMark", "서비스 상징 글자"],
          ["serviceName", "서비스 이름"],
          ["brandSubtitle", "회원 화면 이름"],
          ["breadcrumbPrefix", "현재 위치 앞 문구"],
          ["fallbackMemberName", "회원 이름 기본값"],
          ["avatarFallback", "회원 사진 기본 글자"],
          ["profileIncomplete", "프로필 미완료 상태"],
          ["organizationPending", "소속 확인 중 상태"],
          ["missingValue", "정보 없음 표시"],
          ["unknownValue", "알 수 없는 값 표시"],
          ["pointUnit", "포인트 단위"],
          ["homeLabel", "홈 이동 버튼"],
          ["logoutLabel", "로그아웃 버튼"],
          ["lastSyncPrefix", "마지막 동기화 앞 문구"],
          ["refreshLabel", "새로고침 버튼"],
          ["refreshingLabel", "새로고침 처리 중 문구"],
          ["newInquiryLabel", "새 문의 버튼"],
          ["incompleteNotice", "회원가입 미완료 안내"],
          ["continueSignupLabel", "회원가입 이어가기 버튼"],
          ["closeLabel", "알림 닫기 접근성 이름"],
        ].map(([key, label]) => [
          key,
          field(label, "마이페이지 공통 영역에서 회원에게 표시됩니다."),
        ]),
      ),
      itemFields: {
        title: "메뉴 표시 이름",
        description: "메뉴에서 확인할 수 있는 내용",
      },
    },
    overview: {
      name: "이용 현황 요약",
      titleLabel: "영역 제목",
      textFields: Object.fromEntries(
        [
          ["inquiriesTopbarTitle", "문의 탭 상단 제목"],
          ["inquiriesTopbarDescription", "문의 탭 상단 설명"],
          ["balanceLabel", "보유 포인트 제목"],
          ["organizationFallback", "소속 농협 기본값"],
          ["walletSuffix", "지갑 이름 뒤 문구"],
          ["inquiryCountLabel", "등록 문의 수 제목"],
          ["inquiryCountHelp", "등록 문의 수 설명"],
          ["unreadAnswersLabel", "미열람 답변 수 제목"],
          ["unreadAnswersHelp", "미열람 답변 수 설명"],
          ["viewedAnswersLabel", "열람 답변 수 제목"],
          ["viewedAnswersHelp", "열람 답변 수 설명"],
          ["recentInquiriesTitle", "최근 문의 제목"],
          ["recentInquiriesDescription", "최근 문의 설명"],
          ["recentPointsTitle", "최근 포인트 제목"],
          ["recentPointsDescription", "최근 포인트 설명"],
          ["viewAllLabel", "전체 보기 버튼"],
          ["countSuffix", "건수 단위"],
          ["requestNumberHeading", "문의번호 열 이름"],
          ["subjectHeading", "제목 열 이름"],
          ["visibilityHeading", "공개범위 열 이름"],
          ["statusHeading", "상태 열 이름"],
          ["createdHeading", "등록일 열 이름"],
          ["emptyInquiriesLink", "문의 없음 이동 링크"],
          ["ledgerFallback", "포인트 항목 기본 이름"],
          ["visibilityPublic", "전체 공개 표시"],
          ["visibilityOrganization", "우리 농협 공개 표시"],
          ["visibilityPrivate", "비공개 표시"],
          ["statusSubmitted", "답변 대기 상태"],
          ["statusAnswered", "답변 완료 상태"],
          ["statusPublished", "답변 열람 상태"],
          ["statusFollowup", "추가 문의 상태"],
          ["statusCompleted", "상담 종료 상태"],
          ["ledgerFirstSignup", "농협 최초 가입 적립 이름"],
          ["ledgerUserSignup", "회원 가입 적립 이름"],
          ["ledgerAnswerView", "답변 열람 차감 이름"],
          ["ledgerManual", "수동 조정 이름"],
          ["ledgerAdminCredit", "운영자 적립 이름"],
          ["ledgerAdminDebit", "운영자 차감 이름"],
        ].map(([key, label]) => [
          key,
          field(label, "이용 현황 카드와 최근 내역에 표시됩니다."),
        ]),
      ),
    },
    inquiries: {
      name: "내 문의 목록",
      titleLabel: "목록 제목",
      descriptionLabel: "목록 설명",
      textFields: Object.fromEntries(
        [
          ["newInquiryLabel", "새 문의 버튼"],
          ["requestNumberHeading", "문의번호 열 이름"],
          ["subjectHeading", "제목 열 이름"],
          ["visibilityHeading", "공개범위 열 이름"],
          ["statusHeading", "상태 열 이름"],
          ["answerHeading", "답변 열 이름"],
          ["createdHeading", "등록일 열 이름"],
          ["viewedAnswerLabel", "열람 완료 표시"],
          ["viewAnswerLabel", "답변 확인 표시"],
          ["answerPendingLabel", "답변 대기 표시"],
          ["detailLabel", "상세 보기 버튼"],
          ["emptyLinkLabel", "문의 없음 이동 링크"],
          ["actionsHeading", "작업 열 접근성 이름"],
        ].map(([key, label]) => [
          key,
          field(label, "내 문의 목록에서 회원에게 표시됩니다."),
        ]),
      ),
    },
    points: {
      name: "포인트 내역과 이용 안내",
      titleLabel: "영역 제목",
      legalWarning:
        "포인트 적립·차감 계산과 이벤트 저장값은 변경할 수 없습니다. 표시 문구와 이용 안내만 편집됩니다.",
      textFields: Object.fromEntries(
        [
          ["balanceLabel", "현재 잔액 제목"],
          ["walletSuffix", "지갑 이름 뒤 문구"],
          ["earnedLabel", "총 적립 제목"],
          ["earnedHelp", "총 적립 설명"],
          ["usedLabel", "총 사용 제목"],
          ["usedHelp", "총 사용 설명"],
          ["countLabel", "포인트 이력 수 제목"],
          ["countHelp", "포인트 이력 수 설명"],
          ["guideTitle", "포인트 안내 제목"],
          ["guideDescription", "포인트 안내 설명"],
          ["historyTitle", "사용 내역 제목"],
          ["historyDescription", "사용 내역 설명"],
          ["dateHeading", "일시 열 이름"],
          ["eventHeading", "이벤트 열 이름"],
          ["descriptionHeading", "설명 열 이름"],
          ["changeHeading", "변동 열 이름"],
          ["balanceHeading", "잔액 열 이름"],
        ].map(([key, label]) => [
          key,
          field(label, "포인트 요약과 사용 내역에서 표시됩니다."),
        ]),
      ),
      itemFields: { title: "포인트 이용 안내 문구" },
    },
    profile: {
      name: "회원 정보와 수신 동의",
      titleLabel: "회원 정보 제목",
      descriptionLabel: "회원 정보 설명",
      legalWarning:
        "필수 동의 여부와 계정 저장값은 변경할 수 없습니다. 선택 수신 항목의 표시 문구만 편집됩니다.",
      textFields: Object.fromEntries(
        [
          ["nameLabel", "이름 항목"],
          ["emailLabel", "이메일 항목"],
          ["phoneLabel", "연락처 항목"],
          ["organizationLabel", "소속 농협 항목"],
          ["organizationMissing", "소속 미등록 표시"],
          ["organizationPending", "소속 확인 중 표시"],
          ["positionLabel", "직책 항목"],
          ["dutyLabel", "담당 업무 항목"],
          ["joinedLabel", "가입일 항목"],
          ["businessCardLabel", "명함 항목"],
          ["businessCardView", "명함 보기 링크"],
          ["businessCardEmpty", "명함 없음 표시"],
          ["walletTitle", "소속 농협 지갑 제목"],
          ["walletDescription", "소속 농협 지갑 설명"],
          ["walletOrganizationLabel", "지갑 농협명 항목"],
          ["walletBalanceLabel", "지갑 잔액 항목"],
          ["walletEarnedLabel", "누적 적립 항목"],
          ["walletUsedLabel", "누적 사용 항목"],
          ["walletMemberCountLabel", "조직 회원 수 항목"],
          ["memberSuffix", "회원 수 단위"],
          ["walletCreatedLabel", "조직 생성일 항목"],
          ["walletUpdatedLabel", "최근 업데이트 항목"],
          ["consentsTitle", "동의 항목 제목"],
          ["consentsDescription", "동의 항목 설명"],
          ["requiredConsentsTitle", "필수 동의 제목"],
          ["termsLabel", "이용약관 동의 이름"],
          ["privacyLabel", "개인정보 동의 이름"],
          ["optionalConsentsTitle", "선택 수신 동의 제목"],
          ["optionalConsentsDescription", "선택 수신 동의 설명"],
          ["marketingLabel", "마케팅 수신 이름"],
          ["consentEmailLabel", "이메일 수신 이름"],
          ["smsLabel", "문자 수신 이름"],
          ["kakaoLabel", "카카오 알림 수신 이름"],
          ["agreedLabel", "동의 상태"],
          ["disagreedLabel", "미동의 상태"],
          ["savingLabel", "동의 저장 중 문구"],
          ["incompleteTitle", "회원가입 미완료 제목"],
          ["incompleteDescription", "회원가입 미완료 설명"],
          ["continueSignupLabel", "회원가입 이어가기 버튼"],
        ].map(([key, label]) => [
          key,
          field(label, "회원 정보와 수신 동의 영역에 표시됩니다."),
        ]),
      ),
    },
  },
  "member.requestDetail": {
    summary: {
      name: "문의 상세 요약",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "관리자 목록 이름",
      textFields: Object.fromEntries(
        [
          ["backLabel", "문의 목록 이동 링크"],
          ["backHint", "목록 이동 도움말"],
          ["statusLabel", "상태 항목"],
          ["visibilityLabel", "공개범위 항목"],
          ["pointsLabel", "보유 포인트 항목"],
          ["pointUnit", "포인트 단위"],
          ["missingValue", "정보 없음 표시"],
          ["visibilityPublic", "전체 공개 표시"],
          ["visibilityOrganization", "우리 농협 공개 표시"],
          ["visibilityPrivate", "비공개 표시"],
          ["statusSubmitted", "답변 대기 상태"],
          ["statusAnswered", "답변 완료 상태"],
          ["statusPublished", "답변 열람 상태"],
          ["statusFollowup", "추가 문의 상태"],
          ["statusCompleted", "상담 종료 상태"],
        ].map(([key, label]) => [
          key,
          field(label, "문의 상세 상단 요약에 표시됩니다."),
        ]),
      ),
    },
    requestBody: {
      name: "문의 본문",
      eyebrowLabel: "영역 배지",
      titleLabel: "영역 제목",
      textFields: { receivedPrefix: field("접수일 앞 문구") },
    },
    attachments: {
      name: "첨부 사진",
      eyebrowLabel: "영역 배지",
      titleLabel: "영역 제목",
      textFields: { countSuffix: field("첨부 수 단위") },
    },
    answer: {
      name: "답변과 포인트 열람",
      eyebrowLabel: "영역 배지",
      titleLabel: "답변 등록 제목",
      descriptionLabel: "답변 준비 중 제목",
      legalWarning:
        "답변 열람 API, 포인트 차감과 중복 차감 방지 로직은 변경할 수 없습니다. 안내 문구만 편집됩니다.",
      textFields: Object.fromEntries(
        [
          ["emptyBody", "답변 본문 없음 안내"],
          ["pointPrefix", "포인트 차감 앞 문구"],
          ["pointSuffix", "포인트 차감 뒤 문구"],
          ["noDuplicateCharge", "중복 차감 방지 안내"],
          ["loadingLabel", "답변 열람 처리 중 버튼"],
          ["openLabel", "답변 열람 버튼"],
          ["pendingDescription", "답변 준비 중 설명"],
        ].map(([key, label]) => [
          key,
          field(label, "답변 열람 영역에서 회원에게 표시됩니다."),
        ]),
      ),
    },
    followupActions: {
      name: "답변 확인 후 다음 단계",
      eyebrowLabel: "영역 배지",
      titleLabel: "영역 제목",
      descriptionLabel: "영역 설명",
      legalWarning:
        "후속 문의 종류, 연결되는 문의 ID와 입력값은 변경할 수 없습니다. 버튼 이름과 설명만 편집됩니다.",
      textFields: Object.fromEntries(
        [
          ["followupTitle", "추가 문의 버튼 제목"],
          ["followupDescription", "추가 문의 버튼 설명"],
          ["estimateTitle", "추가상담·견적 버튼 제목"],
          ["estimateDescription", "추가상담·견적 버튼 설명"],
          ["completedTitle", "문의 완료 상태 제목"],
          ["completedDescription", "문의 완료 상태 설명"],
          ["completeTitle", "문의 완료 버튼 제목"],
          ["completeDescription", "문의 완료 버튼 설명"],
        ].map(([key, label]) => [
          key,
          field(label, "답변 확인 후 선택할 다음 단계에 표시됩니다."),
        ]),
      ),
    },
    rating: {
      name: "답변 평가",
      titleLabel: "평가 제목",
      descriptionLabel: "평가 도움말",
      legalWarning:
        "평가 점수 범위, 저장 항목과 문의 완료 순서는 변경할 수 없습니다. 표시 문구만 편집됩니다.",
      textFields: Object.fromEntries(
        [
          ["completedBadge", "평가 작성 완료 표시"],
          ["requiredBadge", "평가 필수 표시"],
          ["scoreAriaLabel", "점수 선택 접근성 이름"],
          ["scoreSuffix", "점수 단위"],
          ["helpfulLabel", "도움됨 선택 문구"],
          ["needsWorkLabel", "보완 필요 선택 문구"],
          ["commentPlaceholder", "평가 의견 입력 안내"],
          ["savingLabel", "평가 저장 중 버튼"],
          ["updateLabel", "평가 수정 버튼"],
          ["saveLabel", "평가 저장 버튼"],
          ["completingLabel", "문의 완료 처리 중 버튼"],
          ["completeLabel", "문의 완료 버튼"],
        ].map(([key, label]) => [
          key,
          field(label, "답변 평가 입력 영역에 표시됩니다."),
        ]),
      ),
    },
    dialogs: {
      name: "답변 열람과 문의 완료 확인 창",
      titleLabel: "관리자 목록 이름",
      legalWarning:
        "포인트 계산, 열람·완료 API와 처리 순서는 변경할 수 없습니다. 확인 창의 설명과 버튼 문구만 편집됩니다.",
      textFields: Object.fromEntries(
        [
          ["completeEyebrow", "문의 완료 확인 배지"],
          ["completeTitle", "문의 완료 확인 제목"],
          ["completeDescription", "문의 완료 확인 설명"],
          ["continueLabel", "계속 상담 버튼"],
          ["completingLabel", "문의 완료 처리 중 버튼"],
          ["endLabel", "상담 종료 버튼"],
          ["viewTitle", "답변 열람 확인 제목"],
          ["pointPrefix", "포인트 차감 앞 문구"],
          ["pointSuffix", "포인트 차감 뒤 문구"],
          ["noDuplicateCharge", "중복 차감 방지 안내"],
          ["costLabel", "차감 예정 포인트 항목"],
          ["balanceLabel", "현재 보유 포인트 항목"],
          ["insufficient", "포인트 부족 안내"],
          ["cancelLabel", "취소 버튼"],
          ["processingLabel", "열람 처리 중 버튼"],
          ["viewLabel", "답변 열람 확인 버튼"],
        ].map(([key, label]) => [
          key,
          field(label, "답변 열람 또는 상담 종료 확인 창에 표시됩니다."),
        ]),
      ),
    },
  },
  "admin.operations": {
    navigation: {
      name: "운영 메뉴와 공통 상단",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "관리 안내",
      legalWarning:
        "메뉴 ID와 연결되는 관리자 기능은 변경할 수 없습니다. 화면에 표시되는 이름과 설명만 편집됩니다.",
      textFields: {
        overviewDescription: field("운영 대시보드 설명"),
        membersDescription: field("회원 관리 설명"),
        inquiriesDescription: field("상담 관리 설명"),
        auditQuotesDescription: field("회계감사 견적 설명"),
        pointsDescription: field("포인트 관리 설명"),
        auditDescription: field("운영 기록 설명"),
        navigationAriaLabel: field("메뉴 접근성 이름"),
        brandName: field("서비스 이름"),
        brandSubtitle: field("운영 화면 이름"),
        operatorRole: field("관리자 역할 표시"),
        backToContent: field("콘텐츠 관리 이동 버튼"),
        logout: field("로그아웃 버튼"),
        breadcrumbPrefix: field("현재 위치 앞 문구"),
        lastSynced: field("마지막 동기화 문구"),
        refresh: field("새로고침 버튼"),
        refreshing: field("새로고침 처리 중"),
        closeAriaLabel: field("알림 닫기 접근성 이름"),
      },
      itemFields: { title: "메뉴 표시 이름" },
    },
    overview: {
      name: "운영 대시보드",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      textFields: {
        memberKpi: field("가입 회원 지표"),
        requestKpi: field("문의 접수 지표"),
        answerKpi: field("등록 답변 지표"),
        ratingKpi: field("고객 평가 지표"),
        trendTitle: field("운영 추이 제목"),
        trendDescription: field("운영 추이 설명"),
        metricsTitle: field("주요 지표 제목"),
        metricsDescription: field("주요 지표 설명"),
        recentActivityTitle: field("최근 활동 제목"),
        recentActivityDescription: field("최근 활동 설명"),
        topOrganizationsTitle: field("문의 상위 농협 제목"),
        topOrganizationsDescription: field("문의 상위 농협 설명"),
        noActivity: field("활동 없음 안내"),
        noData: field("자료 없음 안내"),
      },
    },
    members: {
      name: "회원과 운영자 관리",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      legalWarning:
        "회원·운영자 상태 값, 권한과 개인정보 조회 범위는 고정되어 있습니다. 표시 문구만 편집됩니다.",
      textFields: {
        subtabsAriaLabel: field("하위 메뉴 접근성 이름"),
        memberTabDescription: field("회원 관리 설명"),
        operatorTabDescription: field("운영자 관리 설명"),
        memberListTitle: field("회원 목록 제목"),
        memberSearchPlaceholder: field("회원 검색 안내"),
        operatorListTitle: field("운영자 목록 제목"),
        operatorSearchPlaceholder: field("운영자 검색 안내"),
        addOperator: field("운영자 추가 버튼"),
        memberEmpty: field("회원 검색 결과 없음"),
        operatorEmpty: field("운영자 검색 결과 없음"),
        memberDetailTitle: field("회원 상세 제목"),
        operatorDetailTitle: field("운영자 상세 제목"),
        noMemberSelected: field("회원 미선택 안내"),
        noOperatorSelected: field("운영자 미선택 안내"),
      },
      itemFields: { title: "하위 메뉴 표시 이름" },
    },
    inquiries: {
      name: "상담과 FAQ 관리",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      legalWarning:
        "문의 상태·공개 범위·FAQ 저장 값은 고정되어 있습니다. 선택지의 표시 이름만 편집됩니다.",
      textFields: {
        subtabsAriaLabel: field("하위 메뉴 접근성 이름"),
        requestTabDescription: field("문의 관리 설명"),
        faqTabDescription: field("FAQ 관리 설명"),
        requestListTitle: field("문의 목록 제목"),
        unifiedSearch: field("통합 검색 이름"),
        requestSearchPlaceholder: field("문의 검색 안내"),
        requestSearchAriaLabel: field("문의 검색 접근성 이름"),
        clearSearchAriaLabel: field("검색어 지우기 접근성 이름"),
        inquiryEmpty: field("문의 검색 결과 없음"),
        faqTitle: field("FAQ 관리 제목"),
        faqDescription: field("FAQ 관리 설명"),
        faqSearchPlaceholder: field("FAQ 검색 안내"),
        faqLoading: field("FAQ 불러오는 중"),
        faqEmpty: field("등록 FAQ 없음"),
        faqFilteredEmpty: field("FAQ 검색 결과 없음"),
        addFaq: field("FAQ 추가 버튼"),
      },
      itemFields: { title: "선택지 표시 이름" },
    },
    auditQuotes: {
      name: "회계감사 견적 접수",
      titleLabel: "목록 제목",
      descriptionLabel: "목록 설명",
      legalWarning:
        "접수 상태 값과 전환 규칙, 원문 개인정보 조회 권한은 변경할 수 없습니다.",
      textFields: {
        statusFilter: field("상태 필터 이름"),
        refresh: field("새로고침 버튼"),
        refreshing: field("불러오는 중 문구"),
        empty: field("접수 없음 안내"),
        detailTitle: field("상세 제목"),
        detailDescription: field("개인정보 조회 안내"),
        selectDetail: field("접수 미선택 안내"),
        detailLoading: field("상세 불러오는 중"),
        assigneePlaceholder: field("담당자 입력 안내"),
        save: field("저장 버튼"),
        saving: field("저장 처리 중"),
        retryNotification: field("알림 재시도 버튼"),
      },
      itemFields: { title: "상태 표시 이름" },
    },
    points: {
      name: "농협 지갑과 포인트",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      legalWarning:
        "포인트 이벤트 값, 잔액 계산과 조정 요청 항목은 변경할 수 없습니다. 표시 문구만 편집됩니다.",
      textFields: {
        walletListTitle: field("지갑 목록 제목"),
        allTransactions: field("전체 거래 보기 버튼"),
        walletSearchPlaceholder: field("지갑 검색 안내"),
        walletSearchAriaLabel: field("지갑 검색 접근성 이름"),
        walletEmpty: field("등록 지갑 없음"),
        walletFilteredEmpty: field("지갑 검색 결과 없음"),
        selectedDetailTitle: field("선택 농협 상세 제목"),
        selectOrganization: field("농협 미선택 안내"),
        manualAdjustmentTitle: field("수동 조정 제목"),
        adjustmentHelp: field("수동 조정 도움말"),
        adjustmentPlaceholder: field("조정 포인트 입력 예시"),
        reasonPlaceholder: field("조정 사유 입력 안내"),
        reviewAdjustment: field("조정 확인 버튼"),
        recentTransactions: field("최근 거래 제목"),
        transactionEmpty: field("거래 내역 없음"),
      },
      itemFields: { title: "포인트 이벤트 표시 이름" },
    },
    auditLog: {
      name: "운영 작업 기록",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      textFields: {
        title: field("감사 로그 제목"),
        activityColumn: field("활동 열 이름"),
        targetColumn: field("대상 열 이름"),
        actorColumn: field("작업자 열 이름"),
        occurredAtColumn: field("시각 열 이름"),
        empty: field("기록 없음 안내"),
      },
    },
    dialogs: {
      name: "확인·편집 창",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      legalWarning:
        "확인 창 문구는 작업의 의미만 설명합니다. 실제 API 요청과 저장 항목에는 영향을 주지 않습니다.",
      textFields: {
        close: field("닫기 버튼"),
        cancel: field("취소 버튼"),
        save: field("저장 버튼"),
        saving: field("저장 처리 중"),
        processing: field("작업 처리 중"),
        faqEditorTitle: field("FAQ 편집 창 제목"),
        faqEditorDescription: field("FAQ 편집 창 설명"),
        pointConfirmTitle: field("포인트 조정 확인 제목"),
        pointConfirmDescription: field("포인트 조정 확인 설명"),
        passwordDialogTitle: field("비밀번호 재설정 제목"),
        passwordDialogDescription: field("비밀번호 재설정 설명"),
        permissionDialogTitle: field("권한 변경 확인 제목"),
        deleteOperatorDialogTitle: field("운영자 삭제 확인 제목"),
        deleteFaqDialogTitle: field("FAQ 삭제 확인 제목"),
        irreversibleWarning: field("되돌릴 수 없음 안내"),
      },
    },
  },
  "admin.console": {
    navigation: {
      name: "콘텐츠 관리 메뉴",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      legalWarning:
        "메뉴 ID와 연결되는 화면 전환 값은 변경할 수 없습니다. 표시 이름과 설명만 편집됩니다.",
      textFields: {
        ariaLabel: field("메뉴 접근성 이름"),
      },
      itemFields: {
        title: "메뉴 표시 이름",
        description: "메뉴 짧은 설명",
      },
    },
    shell: {
      name: "관리자 공통 화면",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      legalWarning:
        "로그인, 권한 확인, 로그아웃과 이동 주소는 코드로 보호됩니다. 화면 문구만 편집됩니다.",
      textFields: Object.fromEntries(
        [
          ["homeAriaLabel", "관리자 홈 접근성 이름"],
          ["brandMark", "서비스 로고 글자"],
          ["brandName", "서비스 이름"],
          ["brandSubtitle", "관리자 화면 이름"],
          ["operationsLink", "회원·상담 운영 이동 문구"],
          ["userFallback", "관리자 이름 기본값"],
          ["userInitialFallback", "관리자 이름 첫 글자 기본값"],
          ["permissionLabel", "관리 권한 표시"],
          ["logout", "로그아웃 버튼"],
          ["breadcrumb", "현재 위치 앞 문구"],
          ["lastChecked", "마지막 확인 문구"],
          ["refresh", "새로고침 버튼"],
          ["refreshing", "새로고침 처리 중"],
          ["noticeCloseAriaLabel", "안내 닫기 접근성 이름"],
          ["recordMissing", "기록 없음 안내"],
          ["activityEmptyDescription", "작업 기록 없음 설명"],
        ].map(([key, label]) => [key, field(label)]),
      ),
    },
    dashboard: {
      name: "콘텐츠 운영 대시보드",
      titleLabel: "화면 제목",
      descriptionLabel: "화면 설명",
      textFields: Object.fromEntries(
        [
          ["summaryAriaLabel", "운영 요약 접근성 이름"],
          ["recentChangesTitle", "최근 수정 제목"],
          ["recentChangesDescription", "최근 수정 설명"],
          ["recentChangesEmpty", "최근 수정 없음"],
          ["recentPublishesTitle", "최근 게시 제목"],
          ["recentPublishesDescription", "최근 게시 설명"],
          ["recentPublishesEmpty", "최근 게시 없음"],
          ["viewAll", "전체 보기 버튼"],
          ["issuesTitle", "검토 항목 제목"],
          ["issuesDescription", "검토 항목 설명"],
          ["issueReview", "검토 항목 확인 버튼"],
          ["noIssuesTitle", "검토 문제 없음 제목"],
          ["noIssuesDescription", "검토 문제 없음 설명"],
        ].map(([key, label]) => [key, field(label)]),
      ),
      itemFields: {
        title: "지표 이름",
        description: "지표 설명",
        value: "건수 단위",
      },
    },
    pages: {
      name: "페이지 관리",
      titleLabel: "화면 제목",
      descriptionLabel: "화면 설명",
      legalWarning:
        "분류 필터 ID와 실제 분류 값, 편집·미리보기·게시 주소는 변경할 수 없습니다.",
      textFields: Object.fromEntries(
        [
          ["searchAriaLabel", "화면 검색 접근성 이름"],
          ["searchPlaceholder", "화면 검색 입력 안내"],
          ["filterAriaLabel", "화면 분류 접근성 이름"],
          ["countSuffix", "화면 개수 뒤 문구"],
          ["emptyTitle", "검색 결과 없음 제목"],
          ["emptyDescription", "검색 결과 없음 설명"],
          ["previewAriaSuffix", "미리보기 접근성 뒤 문구"],
          ["detailsAriaSuffix", "편집 정보 접근성 뒤 문구"],
          ["audienceLabel", "공개 범위 이름"],
          ["modifiedLabel", "최종 수정 이름"],
          ["edit", "편집 버튼"],
          ["preview", "미리보기 버튼"],
          ["publish", "게시 버튼"],
          ["publishAvailableTitle", "게시 가능 도움말"],
          ["publishUnavailableTitle", "게시 불가 도움말"],
        ].map(([key, label]) => [key, field(label)]),
      ),
      itemFields: { title: "분류 필터 표시 이름" },
    },
    commonAreas: {
      name: "공통 영역",
      titleLabel: "화면 제목",
      descriptionLabel: "화면 설명",
      textFields: {
        statusLabel: field("상태 이름"),
        modifiedLabel: field("최종 수정 이름"),
        edit: field("내용 편집 버튼"),
        comingSoon: field("준비 중 버튼"),
      },
    },
    design: {
      name: "디자인 설정",
      titleLabel: "화면 제목",
      descriptionLabel: "화면 설명",
      textFields: {
        calloutTitle: field("안전 안내 제목"),
        calloutDescription: field("안전 안내 설명"),
        change: field("설정 변경 버튼"),
        sampleText: field("글자 크기 보기 예시"),
      },
      itemFields: {
        title: "디자인 항목 이름",
        description: "디자인 항목 설명",
      },
    },
    assets: {
      name: "이미지와 파일",
      titleLabel: "화면 제목",
      descriptionLabel: "화면 설명",
      textFields: Object.fromEntries(
        [
          ["listTitle", "파일 목록 제목"],
          ["listDescription", "파일 목록 설명"],
          ["add", "파일 추가 버튼"],
          ["emptyTitle", "파일 없음 제목"],
          ["emptyDescription", "파일 없음 설명"],
          ["pdfBadge", "PDF 파일 배지"],
          ["imageBadge", "이미지 파일 배지"],
          ["pdfKind", "PDF 파일 종류 이름"],
          ["statusLabel", "상태 이름"],
          ["modifiedLabel", "최종 수정 이름"],
        ].map(([key, label]) => [key, field(label)]),
      ),
    },
    history: {
      name: "수정과 게시 이력",
      titleLabel: "화면 제목",
      descriptionLabel: "화면 설명",
      textFields: {
        listTitle: field("작업 기록 제목"),
        listDescription: field("작업 기록 설명"),
        empty: field("작업 기록 없음 안내"),
      },
    },
    pageInfoDialog: {
      name: "페이지 정보 창",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "창 설명",
      textFields: Object.fromEntries(
        [
          ["eyebrow", "창 상단 작은 문구"],
          ["closeAriaLabel", "창 닫기 접근성 이름"],
          ["addressLabel", "페이지 주소 이름"],
          ["audienceLabel", "보는 사람 이름"],
          ["statusLabel", "게시 상태 이름"],
          ["sectionsTitle", "화면 구성 제목"],
          ["sectionsDescription", "화면 구성 설명"],
          ["sectionCountSuffix", "영역 개수 뒤 문구"],
          ["visible", "표시 중 상태"],
          ["hidden", "숨김 상태"],
          ["itemCountPrefix", "목록 개수 앞 문구"],
          ["itemCountSuffix", "목록 개수 뒤 문구"],
          ["required", "필수 영역 배지"],
          ["advanced", "고급 정보 펼치기"],
          ["draftVersion", "초안 번호 이름"],
          ["publishedVersion", "게시 번호 이름"],
          ["none", "값 없음 안내"],
          ["safetyTitle", "초안 안전 안내 제목"],
          ["safetyDescription", "초안 안전 안내 설명"],
          ["preview", "미리보기 버튼"],
          ["openEditor", "페이지 편집기 버튼"],
        ].map(([key, label]) => [key, field(label)]),
      ),
    },
    publishDialog: {
      name: "게시 확인 창",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "창 설명",
      legalWarning:
        "실제 게시 대상, API 주소와 버전 확인 값은 변경할 수 없습니다. 확인 문구만 편집됩니다.",
      textFields: {
        titleSuffix: field("게시 확인 제목 뒤 문구"),
        description: field("게시 영향 안내"),
        impactLabel: field("영향받는 화면 이름"),
        cancel: field("취소 버튼"),
        publishing: field("게시 처리 중 버튼"),
        confirm: field("게시 확인 버튼"),
      },
    },
  },
};

const adminOperationsDefaults = CMS_PAGE_DEFAULTS["admin.operations"];
for (const section of adminOperationsDefaults.sections) {
  const presentation =
    CMS_ROUTE_SECTION_PRESENTATION["admin.operations"]?.[section.id];
  if (!presentation) continue;
  presentation.textFields ??= {};
  for (const [key, value] of Object.entries(section.text)) {
    presentation.textFields[key] ??= field(
      `“${value.length > 32 ? `${value.slice(0, 32)}…` : value}” 문구`,
      `${presentation.name}에서 고객과 운영자에게 표시되는 문구입니다.`,
    );
  }
}

export const CMS_ROUTE_MESSAGE_PRESENTATION: Partial<
  Record<CmsPageKey, Record<string, { label: string; help: string }>>
> = {
  "auth.signup": Object.fromEntries(
    [
      ["submitting", "가입 신청 처리 중"],
      ["success", "가입 신청 접수 완료"],
      ["nameRequired", "이름 미입력"],
      ["phoneRequired", "휴대폰 미입력"],
      ["phoneInvalid", "휴대폰 형식 오류"],
      ["phoneVerificationRequired", "휴대폰 인증 필요"],
      ["phoneCodeRequired", "인증번호 미입력"],
      ["phoneConfirmRequired", "인증 확인 필요"],
      ["phoneReceiveFirst", "인증번호 발송 선행"],
      ["phoneCodeSixDigits", "인증번호 여섯 자리 안내"],
      ["phoneVerificationExpired", "휴대폰 인증 만료"],
      ["phoneVerificationRetry", "휴대폰 인증 재시도"],
      ["phoneAccountLimit", "휴대폰 계정 수 제한"],
      ["phoneCodeInvalid", "인증번호 불일치"],
      ["phoneCodeExpired", "인증번호 만료"],
      ["phoneTooMany", "인증 요청 제한"],
      ["phoneQuota", "문자 발송 한도"],
      ["phoneUnauthorizedDomain", "인증 허용 주소 오류"],
      ["phoneDisabled", "휴대폰 인증 비활성"],
      ["phoneCaptcha", "보안 인증 오류"],
      ["networkError", "네트워크 오류"],
      ["phoneGenericError", "휴대폰 인증 일반 오류"],
      ["emailRequired", "농협 이메일 미입력"],
      ["emailInvalid", "이메일 형식 오류"],
      ["emailCheckRequired", "이메일 중복확인 필요"],
      ["emailDuplicate", "가입된 이메일"],
      ["emailCheckError", "이메일 중복확인 오류"],
      ["passwordRequired", "비밀번호 미입력"],
      ["passwordMin", "비밀번호 최소 조건"],
      ["passwordPolicyError", "비밀번호 보안 정책 오류"],
      ["passwordConfirmRequired", "비밀번호 확인 미입력"],
      ["passwordMismatch", "비밀번호 불일치"],
      ["cooperativeRequired", "소속 농협 미선택"],
      ["positionRequired", "직책 미입력"],
      ["dutyRequired", "담당업무 미선택"],
      ["consentsRequired", "필수 동의 누락"],
      ["businessCardType", "명함 파일 형식 오류"],
      ["businessCardSize", "명함 파일 용량 오류"],
      ["missingFields", "필수 입력 누락"],
      ["invalidToken", "인증 정보 만료"],
      ["emailMismatch", "인증 이메일 불일치"],
      ["invalidCooperative", "소속 농협 정보 오류"],
      ["invalidPhoneVerification", "휴대폰 인증 정보 불일치"],
      ["permissionError", "가입 정보 저장 권한 오류"],
      ["genericError", "회원가입 일반 오류"],
    ].map(([key, label]) => [key, field(`${label} 안내`)]),
  ),
  "auth.login": {
    loading: field("로그인 처리 중 안내"),
    emailRequired: field("이메일 미입력 안내"),
    passwordRequired: field("비밀번호 미입력 안내"),
    invalidCredentials: field("로그인 정보 불일치 안내"),
    tooManyRequests: field("로그인 시도 제한 안내"),
    networkError: field("네트워크 오류 안내"),
    findNameRequired: field("아이디 찾기 이름 미입력 안내"),
    findPhoneRequired: field("아이디 찾기 휴대폰 미입력 안내"),
    findInvalidPhone: field("휴대폰 형식 안내"),
    findNotFound: field("가입 정보 없음 안내"),
    findSuccessPrefix: field("아이디 찾기 성공 앞 문구"),
    findSuccessSuffix: field("아이디 찾기 성공 뒤 문구"),
    resetSuccess: field("재설정 메일 발송 성공 안내"),
    resetInvalidEmail: field("재설정 이메일 형식 안내"),
    resetFailed: field("재설정 메일 발송 실패 안내"),
    genericError: field("로그인 일반 오류 안내"),
  },
  "public.consult": {
    submitting: field("상담 등록 처리 중 안내"),
    subjectRequired: field("제목 미입력 안내"),
    messageRequired: field("내용 미입력 안내"),
    authRequired: field("로그인 필요 안내"),
    organizationRequired: field("소속 농협 정보 없음 안내"),
    invalidAttachment: field("첨부파일 형식 오류 안내"),
    tooManyAttachments: field("첨부 개수 초과 안내"),
    imageOnly: field("이미지 파일 전용 안내"),
    imageTooLarge: field("이미지 용량 초과 안내"),
    genericError: field("상담 등록 일반 오류 안내"),
  },
  "public.inquiries": {
    loading: field("문의 목록 불러오는 중 안내"),
    empty: field("검색 결과 없음 안내"),
    denied: field("열람 권한 없음 안내"),
    genericError: field("문의 목록 오류 안내"),
  },
  "public.faq": {
    loading: field("FAQ 불러오는 중 안내"),
    empty: field("검색 결과 없음 안내"),
    fallback: field("기본 안내 표시 문구"),
  },
  "partner.portal": {
    denied: field("협력 전문가 권한 없음 안내"),
  },
  "member.mypage": {
    loading: field("마이페이지 불러오는 중 안내"),
    loadingDescription: field("로그인과 지갑 확인 중 설명"),
    loginRequired: field("로그인 필요 안내"),
    loadFailed: field("마이페이지 불러오기 실패 제목"),
    retryDescription: field("다시 시도 도움말"),
    retryLabel: field("다시 시도 버튼"),
    otherLoginLabel: field("다른 계정 로그인 버튼"),
    refreshed: field("새로고침 완료 알림"),
    refreshFailed: field("새로고침 실패 알림"),
    logoutFailed: field("로그아웃 실패 알림"),
    consentLoginRequired: field("동의 변경 로그인 필요 알림"),
    consentSaved: field("수신 동의 저장 완료 알림"),
    consentSaveFailed: field("수신 동의 저장 실패 알림"),
    emptyInquiries: field("상담 내역 없음 안내"),
    emptyPoints: field("포인트 내역 없음 안내"),
    genericError: field("마이페이지 오류 안내"),
    relativeNow: field("방금 전 시간 표시"),
    relativeMinutes: field("분 단위 이전 시간 표시"),
    relativeHours: field("시간 단위 이전 시간 표시"),
    relativeDays: field("일 단위 이전 시간 표시"),
  },
  "member.requestDetail": {
    loading: field("문의 상세 불러오는 중 안내"),
    loadFailed: field("문의 상세 불러오기 실패 제목"),
    notFound: field("문의 없음·권한 없음 안내"),
    notFoundDescription: field("문의 접근 권한 확인 설명"),
    insufficientPoints: field("포인트 부족 안내"),
    viewFailed: field("답변 열람 실패 안내"),
    ratingSaved: field("답변 평가 저장 완료 안내"),
    ratingRequiresView: field("평가 전 답변 열람 안내"),
    ratingFailed: field("답변 평가 저장 실패 안내"),
    completeRequiresView: field("완료 전 답변 열람 안내"),
    completeRequiresRating: field("완료 전 답변 평가 안내"),
    completeSuccess: field("문의 완료 처리 안내"),
    completeFailed: field("문의 완료 처리 실패 안내"),
    genericError: field("문의 상세 오류 안내"),
  },
  "admin.operations": Object.fromEntries(
    [
      ["loading", "운영 화면 불러오는 중"],
      ["loadingDescription", "인증과 권한 확인 중"],
      ["denied", "관리자 권한 없음"],
      ["deniedDescription", "관리자 접근 제한"],
      ["loginAgain", "관리자 계정 다시 로그인"],
      ["empty", "운영 자료 없음"],
      ["genericError", "운영 화면 오류"],
      ["retry", "다시 시도"],
      ["saved", "저장 완료"],
      ["authRequired", "로그인 필요"],
      ["refreshed", "새로고침 완료"],
      ["refreshFailed", "새로고침 실패"],
      ["faqLoadFailed", "FAQ 불러오기 실패"],
      ["faqSaved", "FAQ 등록 완료"],
      ["faqUpdated", "FAQ 수정 완료"],
      ["faqSaveFailed", "FAQ 저장 실패"],
      ["faqDeleted", "FAQ 삭제 완료"],
      ["faqDeleteFailed", "FAQ 삭제 실패"],
      ["answerSaved", "답변 저장 완료"],
      ["answerSaveFailed", "답변 저장 실패"],
      ["assigneeRequired", "답변 담당자 누락"],
      ["pointFieldsRequired", "포인트 조정 입력 누락"],
      ["negativeBalance", "포인트 잔액 부족"],
      ["pointAdjusted", "포인트 조정 완료"],
      ["pointAdjustmentFailed", "포인트 조정 실패"],
      ["memberStatusFailed", "회원 상태 변경 실패"],
      ["operatorSaveFailed", "운영자 저장 실패"],
      ["operatorPermissionFailed", "운영자 권한 변경 실패"],
      ["passwordTooShort", "비밀번호 길이 안내"],
      ["passwordResetFailed", "비밀번호 재설정 실패"],
      ["operatorDeleteFailed", "운영자 삭제 실패"],
      ["auditQuoteListFailed", "견적 접수 목록 오류"],
      ["auditQuoteDetailFailed", "견적 접수 상세 오류"],
      ["auditQuoteSaved", "견적 접수 저장 완료"],
      ["auditQuoteConflict", "견적 접수 동시 수정"],
      ["auditQuoteInvalidTransition", "견적 상태 변경 제한"],
      ["auditQuoteSaveFailed", "견적 접수 저장 실패"],
      ["auditQuoteNotifySuccess", "견적 알림 재시도 결과"],
      ["auditQuoteNotifyFailed", "견적 알림 재시도 실패"],
    ].map(([key, label]) => [key, field(`${label} 안내`)]),
  ),
  "admin.console": Object.fromEntries(
    [
      ["loading", "콘텐츠 관리자 불러오는 중"],
      ["loadingDescription", "콘텐츠 상태 불러오는 중 설명"],
      ["denied", "관리자 권한 없음"],
      ["deniedDescription", "관리자 접근 제한 설명"],
      ["loginAgain", "다시 로그인 버튼"],
      ["genericError", "콘텐츠 관리자 오류"],
      ["genericErrorDescription", "콘텐츠 관리자 오류 설명"],
      ["retry", "다시 불러오기 버튼"],
      ["refreshed", "새로고침 완료"],
      ["refreshFailed", "새로고침 실패"],
      ["publishSuccessSuffix", "게시 완료 뒤 문구"],
      ["publishConflict", "동시 수정 충돌"],
      ["publishFailed", "게시 실패"],
    ].map(([key, label]) => [key, field(`${label} 안내`)]),
  ),
};

CMS_ROUTE_MESSAGE_PRESENTATION["admin.operations"] ??= {};
for (const [key, value] of Object.entries(adminOperationsDefaults.messages)) {
  CMS_ROUTE_MESSAGE_PRESENTATION["admin.operations"]![key] ??= field(
    `“${value.length > 32 ? `${value.slice(0, 32)}…` : value}” 안내`,
    "운영 작업의 상태, 완료 또는 오류 상황에 표시되는 안내입니다.",
  );
}
