import type { CmsPageKey } from "@/lib/cms/constants";
import { CMS_PAGE_DEFAULTS } from "@/lib/cms/defaults";
import type { CmsHomeSectionPresentation } from "@/lib/cms/home-presentation";

const field = (label: string, help = "공개 화면에 표시되는 문구입니다.") => ({
  label,
  help,
});

const PORTAL_LOGIN_SECTION_PRESENTATION: Record<
  string,
  CmsHomeSectionPresentation
> = {
  hero: {
    name: "로그인 첫 안내",
    eyebrowLabel: "상단 작은 문구",
    titleLabel: "큰 제목",
    descriptionLabel: "설명",
    textFields: { highlight: field("강조 문구") },
  },
  loginForm: {
    name: "로그인 입력 영역",
    eyebrowLabel: "카드 배지",
    titleLabel: "카드 제목",
    descriptionLabel: "카드 설명",
    textFields: {
      emailLabel: field("이메일 표시 이름"),
      emailPlaceholder: field("이메일 입력 예시"),
      passwordLabel: field("비밀번호 표시 이름"),
      passwordPlaceholder: field("비밀번호 입력 안내"),
      showPasswordLabel: field("비밀번호 보기 접근성 이름"),
      hidePasswordLabel: field("비밀번호 숨기기 접근성 이름"),
      showLabel: field("비밀번호 보기 버튼"),
      hideLabel: field("비밀번호 숨기기 버튼"),
      autoLoginLabel: field("자동 로그인 문구"),
      signupLabel: field("보조 링크 문구"),
      submitLabel: field("로그인 버튼"),
      submittingLabel: field("로그인 처리 중 문구"),
      hint: field("로그인 도움말"),
    },
  },
  recovery: {
    name: "계정 정보 찾기",
    titleLabel: "관리자 목록 이름",
    textFields: {
      ariaLabel: field("계정 찾기 접근성 이름"),
      findEmailLabel: field("아이디 찾기 버튼"),
      resetPasswordLabel: field("비밀번호 찾기 버튼"),
      nameLabel: field("이름 표시 이름"),
      namePlaceholder: field("이름 입력 예시"),
      phoneLabel: field("휴대폰 표시 이름"),
      phonePlaceholder: field("휴대폰 입력 예시"),
      findSubmitLabel: field("아이디 확인 버튼"),
      findingLabel: field("아이디 확인 중 문구"),
      resetEmailLabel: field("가입 이메일 표시 이름"),
      resetEmailPlaceholder: field("가입 이메일 입력 예시"),
      resetSubmitLabel: field("재설정 메일 버튼"),
      resettingLabel: field("메일 발송 중 문구"),
    },
  },
  promoFloat: {
    name: "우측 임시 안내 배너",
    eyebrowLabel: "배지 문구",
    titleLabel: "배너 제목",
    descriptionLabel: "배너 보조 설명",
  },
};

const PORTAL_LOGIN_MESSAGE_PRESENTATION = {
  loading: field("로그인 처리 중 안내"),
  emailRequired: field("이메일 미입력 안내"),
  passwordRequired: field("비밀번호 미입력 안내"),
  invalidCredentials: field("로그인 정보 불일치 안내"),
  tooManyRequests: field("로그인 시도 제한 안내"),
  networkError: field("네트워크 오류 안내"),
  findNameRequired: field("아이디 찾기 이름 미입력 안내"),
  findPhoneRequired: field("아이디 찾기 휴대폰 미입력 안내"),
  findInvalidPhone: field("휴대폰 형식 안내"),
  findNotFound: field("가입 정보 없음 안내"),
  findSuccessPrefix: field("아이디 찾기 성공 앞 문구"),
  findSuccessSuffix: field("아이디 찾기 성공 뒤 문구"),
  resetSuccess: field("재설정 메일 발송 성공 안내"),
  resetInvalidEmail: field("재설정 이메일 형식 안내"),
  resetFailed: field("재설정 메일 발송 실패 안내"),
  portalMismatch: field("로그인 포털 불일치 안내"),
  portalMoveLabel: field("계정 서비스 이동 링크"),
  accountUnavailable: field("계정 사용 불가 안내"),
  genericError: field("로그인 일반 오류 안내"),
};

export const CMS_ROUTE_SECTION_PRESENTATION: Partial<
  Record<CmsPageKey, Record<string, CmsHomeSectionPresentation>>
> = {
  "event.auditQuoteGuide": {
    hero: {
      name: "안내 첫 화면",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "큰 제목",
      descriptionLabel: "설명",
      textFields: {
        highlight: field("강조 문구"),
        badge: field("보조 배지 문구"),
        primaryCtaHelp: field("신청 버튼 도움말"),
      },
    },
    mandate: {
      name: "감사 의무 안내",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "영역 제목",
      descriptionLabel: "의무 안내 설명",
      textFields: {
        ariaLabel: field("영역 접근성 이름"),
      },
      itemFields: {
        title: "단계 제목",
        description: "단계 설명",
        value: "단계 번호",
      },
    },
    pain: {
      name: "실무자 부담",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "영역 제목",
      descriptionLabel: "실무 부담 설명",
      textFields: {
        ariaLabel: field("영역 접근성 이름"),
      },
      itemFields: {
        title: "부담 항목",
      },
    },
    hassleFree: {
      name: "검토보고서 자동 생성",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "영역 제목",
      descriptionLabel: "기능 설명",
      textFields: {
        ariaLabel: field("영역 접근성 이름"),
        tableCaption: field("보고서 예시 설명"),
        reportLabel: field("보고서 예시 라벨"),
        sampleDownloadLabel: field("보고서 예시 파일 버튼"),
      },
      itemFields: {
        title: "핵심 기능 제목",
        description: "핵심 기능 설명",
      },
    },
    steps: {
      name: "진행 방식",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "영역 제목",
      textFields: {
        ariaLabel: field("영역 접근성 이름"),
      },
      itemFields: {
        title: "단계 제목",
        description: "단계 설명",
        value: "단계 번호",
      },
    },
    benefits: {
      name: "실무자 혜택",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "영역 제목",
      textFields: {
        ariaLabel: field("영역 접근성 이름"),
      },
      itemFields: {
        title: "혜택 제목",
        description: "혜택 설명",
      },
    },
    faq: {
      name: "자주 묻는 질문",
      titleLabel: "FAQ 영역 제목",
      textFields: {
        ariaLabel: field("FAQ 접근성 이름"),
      },
      itemFields: {
        title: "질문",
        description: "답변",
      },
    },
    cta: {
      name: "하단 신청 유도",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "신청 유도 제목",
      descriptionLabel: "신청 유도 설명",
      textFields: {
        ctaHelp: field("신청 유도 도움말"),
      },
    },
    legalNotice: {
      name: "운영 주체와 면책문구",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "필수 면책문구",
      textFields: {
        operatorName: field("운영 주체"),
        ariaLabel: field("운영 안내 접근성 이름"),
        regulationNote: field("시행령 주석 제목"),
      },
      itemFields: {
        title: "시행령 주석 항목",
      },
      legalWarning:
        "법적·운영상 필수 안내입니다. 문구 변경은 이력에 남으며 게시 전 경고가 표시됩니다. 이 영역은 숨기거나 삭제할 수 없습니다.",
    },
  },
  "event.auditQuoteEvaluate": {
    hero: {
      name: "평가 접속 첫 안내",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "서비스 제목",
      descriptionLabel: "접속 방법 설명",
    },
    access: {
      name: "평가 접속",
      titleLabel: "영역 제목",
      descriptionLabel: "접속 방법 설명",
      textFields: {
        emailLabel: field("이메일 표시 이름"),
        emailPlaceholder: field("이메일 입력 예시"),
        referenceLabel: field("접수번호 표시 이름"),
        referencePlaceholder: field("접수번호 입력 예시"),
        requestLinkLabel: field("평가 시작 버튼"),
        requestingLabel: field("평가 시작 중 문구"),
        firebaseAccessLabel: field("로그인 계정 계속 버튼"),
      },
    },
    security: {
      name: "접근 보안 안내",
      titleLabel: "영역 제목",
      descriptionLabel: "세션과 URL 보호 안내",
    },
  },
  "event.auditQuoteEvaluation": {
    hero: {
      name: "평가 진행 첫 안내",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "서비스 제목",
      descriptionLabel: "평가 진행 설명",
    },
    overview: {
      name: "평가 준비 현황",
      titleLabel: "영역 제목",
      textFields: {
        fiscalYearLabel: field("대상 사업연도 이름"),
        currentQuoteCountLabel: field("등록 견적 수 이름"),
        minimumQuoteCountLabel: field("최소 견적 수 이름"),
        quoteUnit: field("견적 수 단위"),
        uploadLabel: field("파일 선택 버튼"),
        uploadHelp: field("업로드 형식·용량·개수 도움말"),
        dropzoneTitle: field("드래그앤드롭 영역 제목"),
        dropzoneDescription: field("드래그앤드롭 영역 설명"),
        fileListAriaLabel: field("파일 목록 접근성 이름"),
        deleteSuffix: field("삭제 버튼 접근성 접미"),
        retryLabel: field("재시도 버튼"),
        progressLabel: field("진행률 접근성 이름"),
        allowedTypeLabel: field("허용 형식 이름"),
        maximumSizeLabel: field("최대 용량 이름"),
        quoteRangeLabel: field("견적 수 범위 이름"),
        rangeSeparator: field("최소·최대 구분 기호"),
        bytesUnit: field("바이트 단위"),
        kilobytesUnit: field("킬로바이트 단위"),
        megabytesUnit: field("메가바이트 단위"),
        pendingLabel: field("업로드 대기 상태"),
        uploadingLabel: field("업로드 중 상태"),
        finalizingLabel: field("서버 확인 중 상태"),
        successLabel: field("업로드 성공 상태"),
        failedLabel: field("업로드 실패 상태"),
        reviewLabel: field("담당자 검토 필요 상태"),
        uploadedLabel: field("업로드 완료 상태"),
        verifyingLabel: field("확인 중 상태"),
        needsInfoLabel: field("정보 확인 필요 상태"),
        readyLabel: field("평가 준비 완료 상태"),
        verificationFailedLabel: field("확인 실패 상태"),
        reviewQuotesLabel: field("추출 견적정보 확인 버튼"),
      },
    },
    steps: {
      name: "예상 절차",
      titleLabel: "영역 제목",
      itemFields: {
        title: "절차 이름",
        description: "절차 설명",
      },
    },
    privacy: {
      name: "개인정보·문서 처리",
      titleLabel: "영역 제목",
      descriptionLabel: "문서 처리 안내",
    },
    disclaimer: {
      name: "의사결정 안내",
      titleLabel: "영역 제목",
      descriptionLabel: "보고서 활용 안내",
    },
  },
  "event.auditQuoteEvaluationReview": {
    hero: {
      name: "견적정보 확인 첫 안내",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "화면 제목",
      descriptionLabel: "확인·정정 안내",
    },
    progress: {
      name: "진행 단계",
      titleLabel: "영역 제목",
      itemFields: {
        title: "단계 이름",
        description: "단계 설명",
      },
    },
    documents: {
      name: "업로드 문서와 검증 상태",
      titleLabel: "영역 제목",
      textFields: {
        listAriaLabel: field("문서 목록 접근성 이름"),
        uploadedLabel: field("업로드 완료 상태"),
        checkingLabel: field("확인 중 상태"),
        needsInformationLabel: field("정보 확인 필요 상태"),
        readyLabel: field("평가 준비 완료 상태"),
        failedLabel: field("확인 실패 상태"),
        emptyLabel: field("문서 없음 안내"),
      },
    },
    keyCards: {
      name: "회계법인별 핵심 견적",
      titleLabel: "영역 제목",
      textFields: {
        firmNameLabel: field("회계법인명 항목"),
        auditFeeLabel: field("감사보수 항목"),
        vatLabel: field("부가세 항목"),
        vatIncludedLabel: field("부가세 포함 표시"),
        vatExcludedLabel: field("부가세 별도 표시"),
        revenueLabel: field("회계법인 매출액 항목"),
        auditCountLabel: field("최근 농협 감사건수 항목"),
        hoursLabel: field("총 예상 투입시간 항목"),
        wonUnit: field("원화 단위"),
        countUnit: field("건수 단위"),
        hourUnit: field("시간 단위"),
        missingLabel: field("값 확인 필요 표시"),
        trustedMismatchLabel: field("서버 원본 불일치 안내"),
        adminReviewLabel: field("관리자 확인 필요 안내"),
      },
    },
    comparison: {
      name: "전체 견적 비교",
      titleLabel: "영역 제목",
      textFields: {
        tableCaption: field("비교표 접근성 제목"),
        tableViewLabel: field("표 보기 버튼"),
        cardViewLabel: field("카드 보기 버튼"),
        expandLabel: field("긴 내용 펼치기 버튼"),
        collapseLabel: field("긴 내용 접기 버튼"),
        accountingFirmNameLabel: field("회계법인명 행"),
        auditFeeLabel: field("감사보수 행"),
        vatIncludedLabel: field("부가세 포함 여부 행"),
        accountingFirmRevenueLabel: field("회계법인 매출액 행"),
        recentNonghyupAuditCountLabel: field("최근 농협 감사건수 행"),
        auditedNonghyupTypesLabel: field("감사 수행 농협 종류 행"),
        taxAgencyExperienceLabel: field("세무대리 경험 행"),
        subsidySettlementExperienceLabel: field("보조금 정산 경험 행"),
        engagementPartnerLabel: field("책임회계사 행"),
        engagementTeamLabel: field("투입인력 행"),
        totalPlannedHoursLabel: field("총 예상 투입시간 행"),
        auditScheduleLabel: field("주요 감사 일정 행"),
        qualityControlPlanLabel: field("품질관리 계획 행"),
        requiredProposalItemsLabel: field("필수 제안항목 충족 여부 행"),
        vatIncludedValueLabel: field("부가세 포함 표시"),
        vatExcludedValueLabel: field("부가세 별도 표시"),
        presentLabel: field("충족 표시"),
        absentLabel: field("미충족 표시"),
        yesLabel: field("경험 있음 표시"),
        noLabel: field("경험 없음 표시"),
        missingLabel: field("값 확인 필요 표시"),
      },
    },
    corrections: {
      name: "확인이 필요한 항목과 정정",
      titleLabel: "영역 제목",
      textFields: {
        editLabel: field("정정 시작 버튼"),
        closeLabel: field("정정 닫기 버튼"),
        valueLabel: field("정정값 입력 이름"),
        reasonLabel: field("정정 사유 입력 이름"),
        reasonPlaceholder: field("정정 사유 입력 안내"),
        formatHelp: field("정정값 형식 안내"),
        autoSaveLabel: field("자동 저장 안내"),
        savingLabel: field("저장 중 상태"),
        savedLabel: field("저장 완료 상태"),
        conflictLabel: field("동시 수정 충돌 안내"),
        warningListLabel: field("확인 필요 목록 접근성 이름"),
        noWarningsLabel: field("확인 필요 없음 안내"),
      },
    },
    actions: {
      name: "최종 확인과 보고서 생성",
      titleLabel: "영역 제목",
      textFields: {
        finalCheckLabel: field("고객 최종 확인 동의"),
        confirmLabel: field("최종 확인 버튼"),
        confirmedLabel: field("최종 확인 완료 안내"),
        generateLabel: field("보고서 생성 요청 버튼"),
        generatingLabel: field("보고서 생성 요청 중"),
        reportRequestedLabel: field("보고서 생성 요청 완료"),
        reportOpenLabel: field("보고서 진행상태 링크"),
      },
    },
    guidance: {
      name: "비교·평가 안내",
      titleLabel: "영역 제목",
      descriptionLabel: "의사결정 안내",
    },
  },
  "event.auditQuoteEvaluationReport": {
    hero: {
      name: "평가보고서 첫 안내",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "보고서 제목",
      descriptionLabel: "보고서 설명",
    },
    report: {
      name: "보고서 제공 상태",
      titleLabel: "영역 제목",
      textFields: {
        fiscalYearLabel: field("대상 사업연도 이름"),
        readyLabel: field("보고서 준비 완료 안내"),
        pendingLabel: field("보고서 준비 중 안내"),
        downloadLabel: field("보고서 다운로드 버튼"),
        downloadingLabel: field("다운로드 준비 중 버튼"),
        downloadExpiredLabel: field("고객 다운로드 기간 만료 안내"),
        versionLabel: field("과거 보고서 버전 선택 이름"),
        retryLabel: field("보고서 생성 재시도 버튼"),
        retryingLabel: field("보고서 생성 재시도 중 버튼"),
        weightSettingsTitle: field("보고서별 평가배점 설정 제목"),
        weightSettingsDescription: field("보고서별 설정 범위 안내"),
        weightsFinalizedLabel: field("보고서 설정 확정 상태"),
        compositeWeightTitle: field("품질 가격 비중 제목"),
        qualityLabel: field("품질 비중 이름"),
        priceLabel: field("가격 비중 이름"),
        resetCompositeWeightsLabel: field("품질 가격 기본값 복원 버튼"),
        compositeWeightSliderAriaLabel: field("품질 가격 비중 조절 접근성 이름"),
        qualityWeightMinimumLabel: field("품질 비중 최솟값 안내"),
        qualityWeightMaximumLabel: field("품질 비중 최댓값 안내"),
        qualityCriterionWeightsTitle: field("품질항목별 배점 제목"),
        qualityWeightTotalLabel: field("품질항목 배점 합계 이름"),
        qualityWeightTotalValidLabel: field("품질항목 배점 합계 정상 안내"),
        qualityWeightShortageLabel: field("품질항목 배점 부족 안내"),
        qualityWeightExcessLabel: field("품질항목 배점 초과 안내"),
        pointUnitLabel: field("배점 단위"),
        resetQualityWeightsLabel: field("품질 기본 배점 복원 버튼"),
        auditCountWeightLabel: field("감사 수행 건수 배점 이름"),
        cpaCountWeightLabel: field("공인회계사 수 배점 이름"),
        revenueWeightLabel: field("회계법인 매출액 배점 이름"),
        typeDiversityWeightLabel: field("감사유형 다양성 배점 이름"),
        taxAgencyWeightLabel: field("세무대리 수행 배점 이름"),
        subsidyWeightLabel: field("보조금 정산 수행 배점 이름"),
        defaultValueLabel: field("기본 배점 이름"),
        allowedRangeLabel: field("허용 배점 범위 이름"),
        defaultWeightsGuidanceLabel: field("기본 평가배점 적용 안내"),
        customWeightsGuidanceLabel: field("고객 조정 배점 적용 안내"),
        applyWeightsLabel: field("보고서 배점 확정 버튼"),
        applyingWeightsLabel: field("보고서 배점 서버 계산 중 안내"),
        previewLoadingLabel: field("종합순위 미리보기 계산 중 안내"),
        invalidWeightsPreviewBlockedLabel: field("잘못된 배점 작업 차단 안내"),
        rankingPreviewTitle: field("회계법인 종합순위 미리보기 제목"),
        accountingFirmLabel: field("회계법인 이름"),
        totalBurdenLabel: field("예상 총부담액 이름"),
        qualityRawScoreLabel: field("품질 원점수 이름"),
        priceBaseScoreLabel: field("가격 원점수 이름"),
        weightedQualityScoreLabel: field("품질 환산점수 이름"),
        weightedPriceScoreLabel: field("가격 환산점수 이름"),
        overallScoreLabel: field("최종 종합점수 이름"),
        finalRankLabel: field("최종 순위 이름"),
        eligibilityStatusLabel: field("적격 상태 이름"),
        lowPriceEngagementRiskLabel: field("저가부실수임 우려 안내"),
        eligibleStatusLabel: field("적격 상태 안내"),
        eligibleLowPriceRiskStatusLabel: field("저가부실수임 우려 상태 안내"),
        ineligibleStatusLabel: field("부적격 상태 안내"),
        resubmissionRequiredStatusLabel: field("재제출 필요 상태 안내"),
        excludedStatusLabel: field("평가 제외 상태 안내"),
        notRankedLabel: field("순위 제외 안내"),
        rankUnitLabel: field("순위 단위"),
      },
    },
    disclaimer: {
      name: "의사결정 안내",
      titleLabel: "영역 제목",
      descriptionLabel: "보고서 활용 안내",
    },
  },
  "auth.login": PORTAL_LOGIN_SECTION_PRESENTATION,
  "auth.partnerLogin": PORTAL_LOGIN_SECTION_PRESENTATION,
  "auth.adminLogin": PORTAL_LOGIN_SECTION_PRESENTATION,
  "auth.pendingApproval": {
    hero: {
      name: "승인 대기 첫 안내",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "큰 제목",
      descriptionLabel: "설명",
      textFields: { highlight: field("강조 문구") },
    },
    status: {
      name: "다시 로그인 안내",
      eyebrowLabel: "카드 배지",
      titleLabel: "카드 제목",
      descriptionLabel: "카드 설명",
    },
  },
  "auth.portalAccessDenied": {
    hero: {
      name: "포털 접근 안내",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "큰 제목",
      descriptionLabel: "설명",
    },
    status: {
      name: "접근 제한 카드",
      eyebrowLabel: "카드 배지",
      titleLabel: "카드 제목",
      descriptionLabel: "카드 설명",
    },
  },
  "auth.signup": {
    hero: {
      name: "회원가입 첫 안내와 단계",
      titleLabel: "큰 제목",
      descriptionLabel: "설명",
      textFields: { progressAriaLabel: field("가입 단계 접근성 이름") },
      itemFields: { title: "단계 이름" },
    },
    identity: {
      name: "기본 정보와 인증",
      titleLabel: "영역 제목",
      textFields: {
        nameLabel: field("이름 표시 이름"),
        namePlaceholder: field("이름 입력 안내"),
        phoneLabel: field("휴대폰 표시 이름"),
        phonePlaceholder: field("휴대폰 입력 안내"),
        verifiedNotice: field("휴대폰 인증 완료 안내"),
        verificationCodePlaceholder: field("인증번호 입력 안내"),
        verifyCodeLabel: field("인증 확인 버튼"),
        sendingLabel: field("인증번호 발송 중 문구"),
        resendLabel: field("인증번호 재발송 버튼"),
        sendLabel: field("인증번호 받기 버튼"),
        phoneLimitHelp: field("휴대폰 계정 제한 안내"),
        codeSentHelp: field("인증번호 발송 완료 도움말"),
        emailLabel: field("농협 이메일 표시 이름"),
        emailPlaceholder: field("농협 이메일 입력 안내"),
        checkingEmailLabel: field("이메일 확인 중 문구"),
        checkEmailLabel: field("이메일 중복확인 버튼"),
        emailAvailable: field("사용 가능한 이메일 안내"),
        passwordLabel: field("비밀번호 표시 이름"),
        passwordPlaceholder: field("비밀번호 입력 안내"),
        passwordConfirmLabel: field("비밀번호 확인 표시 이름"),
        passwordConfirmPlaceholder: field("비밀번호 확인 입력 안내"),
        showPasswordLabel: field("비밀번호 보기 접근성 이름"),
        hidePasswordLabel: field("비밀번호 숨기기 접근성 이름"),
      },
    },
    phoneVerification: {
      name: "휴대폰 인증 보호 설정",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "보호 안내",
    },
    organization: {
      name: "소속 농협 검색",
      titleLabel: "영역 제목",
      textFields: {
        searchLabel: field("농협 검색 표시 이름"),
        searchPlaceholder: field("농협 검색 입력 예시"),
        resultsAriaLabel: field("검색 결과 접근성 이름"),
        searchLoading: field("농협 검색 중 안내"),
        searchFailed: field("농협 검색 실패 안내"),
        emptyPrefix: field("검색 결과 없음 앞 문구"),
        emptySuffix: field("검색 결과 없음 뒤 문구"),
        selectedPrefix: field("선택한 농협 앞 문구"),
        demoBadge: field(
          "테스트 농협 표시 문구",
          "둥기농협 검색 결과와 선택 완료 영역에 표시되는 보조 문구입니다.",
        ),
      },
    },
    work: {
      name: "담당자 정보",
      titleLabel: "영역 제목",
      textFields: {
        positionLabel: field("직책 표시 이름"),
        positionPlaceholder: field("직책 입력 예시"),
        dutyLabel: field("담당업무 표시 이름"),
        dutyPlaceholder: field("담당업무 첫 선택 문구"),
      },
      itemFields: { title: "담당업무 표시 이름" },
    },
    businessCard: {
      name: "명함 첨부",
      titleLabel: "입력 표시 이름",
      descriptionLabel: "첨부 도움말",
      textFields: {
        changeLabel: field("파일 변경 버튼"),
        deleteLabel: field("파일 삭제 버튼"),
        uploadTitle: field("업로드 안내 제목"),
        uploadHelp: field("파일 형식·용량 안내"),
        selectLabel: field("파일 선택 버튼"),
        bytesUnit: field("바이트 단위"),
        kilobytesUnit: field("킬로바이트 단위"),
        megabytesUnit: field("메가바이트 단위"),
      },
    },
    consents: {
      name: "약관과 개인정보 동의",
      titleLabel: "영역 제목",
      legalWarning:
        "필수 약관과 개인정보 동의 여부, 내부 저장 키는 변경할 수 없습니다. 표시 문구 변경은 이력에 남습니다.",
      textFields: {
        allLabel: field("전체 동의 제목"),
        allHelp: field("전체 동의 설명"),
        requiredBadge: field("필수 배지"),
        optionalBadge: field("선택 배지"),
        termsLabel: field("이용약관 동의 문구"),
        termsLinkLabel: field("이용약관 보기 링크"),
        privacyLabel: field("개인정보 동의 문구"),
        privacyLinkLabel: field("개인정보 보기 링크"),
        marketingTitle: field("선택 수신 동의 제목"),
        marketingHelp: field("선택 수신 동의 설명"),
        marketingLabel: field("마케팅 수신 문구"),
        emailLabel: field("이메일 수신 문구"),
        smsLabel: field("문자 수신 문구"),
        kakaoLabel: field("카카오톡 수신 문구"),
      },
    },
    benefits: {
      name: "가입 혜택",
      titleLabel: "혜택 제목",
      itemFields: { title: "혜택 문구" },
    },
    submit: {
      name: "가입 신청 버튼",
      titleLabel: "관리자 목록 이름",
      textFields: {
        submitLabel: field("가입 신청 버튼"),
        submittingLabel: field("가입 처리 중 버튼"),
        temporaryActivationTitle: field("임시회원 비밀번호 설정 제목"),
        temporaryActivationDescription: field(
          "임시회원 비밀번호 설정 설명",
        ),
        temporaryActivationSubmitLabel: field(
          "비밀번호 설정 후 견적 확인 버튼",
        ),
        temporaryActivationSubmittingLabel: field(
          "임시회원 계정 준비 중 버튼",
        ),
        temporaryConversionTitle: field("정회원 전환 제목"),
        temporaryConversionDescription: field("정회원 전환 설명"),
        temporaryConversionHelp: field("정회원 전환 보조 안내"),
        temporaryConversionQuotedCooperativeLabel: field(
          "견적 요청 농협 라벨",
        ),
        temporaryConversionQuotedNameLabel: field("견적 요청 이름 라벨"),
        temporaryConversionQuotedPhoneLabel: field(
          "견적 요청 전화번호 라벨",
        ),
        temporaryConversionQuotedEmailLabel: field(
          "견적 요청 이메일 라벨",
        ),
        temporaryConversionQuotedMissingValue: field(
          "견적 요청 정보 없음 표시",
        ),
        temporaryConversionConsentLabel: field("정회원 전환 동의 문구"),
        temporaryConversionConsentHelp: field("정회원 전환 동의 설명"),
        temporaryConversionConsentLinkLabel: field("이용약관 보기 링크"),
        temporaryConversionConsentRequired: field("정회원 전환 동의 오류"),
        temporaryConversionSubmitLabel: field("정회원 전환 버튼"),
        temporaryConversionSubmittingLabel: field(
          "정회원 혜택 적용 중 버튼",
        ),
      },
    },
  },
  "legal.terms": {
    intro: {
      name: "약관 제목과 시행일",
      eyebrowLabel: "영문 안내",
      titleLabel: "약관 제목",
      descriptionLabel: "첫 안내",
      textFields: { effectiveDate: field("시행일") },
      legalWarning:
        "법적 필수 안내입니다. 숨기거나 삭제할 수 없으며 변경사항은 게시 이력에 남습니다.",
    },
    service: {
      name: "서비스 목적과 범위",
      titleLabel: "항목 제목",
      descriptionLabel: "약관 본문",
      legalWarning: "약관 본문 변경 전 운영·법률 검토를 권장합니다.",
    },
    account: {
      name: "회원 가입과 계정",
      titleLabel: "항목 제목",
      descriptionLabel: "약관 본문",
      legalWarning: "약관 본문 변경 전 운영·법률 검토를 권장합니다.",
    },
    content: {
      name: "문의와 공개 범위",
      titleLabel: "항목 제목",
      descriptionLabel: "약관 본문",
      legalWarning: "약관 본문 변경 전 운영·법률 검토를 권장합니다.",
    },
    responsibility: {
      name: "책임과 면책",
      titleLabel: "항목 제목",
      descriptionLabel: "약관 본문",
      legalWarning:
        "면책 문구는 숨기거나 삭제할 수 없습니다. 변경 전 법률 검토를 권장합니다.",
    },
    changes: {
      name: "약관 변경과 문의",
      titleLabel: "항목 제목",
      descriptionLabel: "약관 본문",
      legalWarning: "약관 본문 변경 전 운영·법률 검토를 권장합니다.",
    },
  },
  "legal.privacy": Object.fromEntries(
    [
      ["intro", "방침 제목과 시행일"],
      ["collection", "처리하는 개인정보"],
      ["purpose", "처리 목적"],
      ["retention", "보유 및 이용 기간"],
      ["sharing", "제3자 제공과 처리위탁"],
      ["rights", "이용자의 권리"],
      ["safeguards", "안전성 확보 조치"],
      ["officer", "보호책임자와 문의"],
    ].map(([id, name]) => [
      id,
      {
        name,
        eyebrowLabel: id === "intro" ? "영문 안내" : undefined,
        titleLabel: "항목 제목",
        descriptionLabel: "개인정보처리방침 본문",
        textFields:
          id === "intro" ? { effectiveDate: field("시행일") } : undefined,
        legalWarning:
          "개인정보 법적 안내입니다. 숨기거나 삭제할 수 없으며 변경사항은 게시 이력에 남습니다.",
      },
    ]),
  ),
  "public.support": {
    hero: {
      name: "고객지원 첫 안내",
      eyebrowLabel: "영문 안내",
      titleLabel: "큰 제목",
      descriptionLabel: "설명",
      textFields: { highlight: field("강조 문구") },
    },
    channels: {
      name: "문의 방법",
      eyebrowLabel: "카드 배지",
      titleLabel: "카드 제목",
      descriptionLabel: "이용 안내",
    },
  },
  "partner.portal": {
    accessNotice: {
      name: "협력 전문가 접근 안내",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "접근 제한 제목",
      descriptionLabel: "접근 제한 설명",
      legalWarning:
        "실제 파트너 인증과 배정 권한이 구현되기 전에는 운영 정보 화면을 공개할 수 없습니다.",
    },
    sitemap: {
      name: "제휴사 사이트맵",
      titleLabel: "사이트맵 제목",
      descriptionLabel: "사이트맵 안내",
      legalWarning:
        "실제 URL과 제휴사 접근 권한은 App Router와 서버 권한에서 자동 판정됩니다. 표시 문구만 편집할 수 있습니다.",
      textFields: {
        menuLabel: field("사이드 메뉴 이름"),
        menuDescription: field("사이드 메뉴 설명"),
        publicGroupTitle: field("공개 서비스 그룹 제목"),
        roleGroupTitle: field("제휴사 전용 그룹 제목"),
        countPrefix: field("페이지 수 앞 문구"),
        countSuffix: field("페이지 수 뒤 문구"),
        automaticUpdateLabel: field("자동 갱신 안내"),
        openLabel: field("페이지 열기 버튼"),
      },
    },
    quoteEvaluation: {
      name: "회계감사 견적 평가",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "평가 입력 영역 제목",
      descriptionLabel: "평가 입력 안내",
      textFields: {
        eyebrow: field("폼 상단 작은 문구"),
        basicLegend: field("기본정보 영역 제목"),
        accountingFirmLabel: field("회계법인명 라벨"),
        targetCooperativeLabel: field("대상 농협 라벨"),
        fiscalYearLabel: field("사업연도 라벨"),
        submittedAtLabel: field("제출일시 라벨"),
        submittedAtHelp: field("제출일시 안내"),
        engagementPartnerLabel: field("담당회계사 이름 라벨"),
        proposerTypeLabel: field("제안 주체 유형 라벨"),
        requestContextMissing: field("견적요청 연결정보 누락 안내"),
        auditGroupWarning: field("감사반 부적격 경고"),
        costLegend: field("비용정보 영역 제목"),
        auditFeeLabel: field("감사보수 라벨"),
        auditFeeHelp: field("감사보수 도움말"),
        expenseModeLabel: field("제경비 청구방식 라벨"),
        expectedExpenseLabel: field("예상 제경비 라벨"),
        expenseIncludedHelp: field("제경비 포함 안내"),
        expenseSeparateHelp: field("제경비 별도 청구 안내"),
        totalPreviewLabel: field("예상 총부담액 라벨"),
        totalPreviewHelp: field("예상 총부담액 안내"),
        evaluationLegend: field("평가정보 영역 제목"),
        localAuditCountLabel: field("감사 수행 건수 라벨"),
        cpaCountLabel: field("공인회계사 수 라벨"),
        revenueLabel: field("회계법인 매출액 라벨"),
        cooperativeTypesLabel: field("수행 농협 유형 라벨"),
        noCooperativeTypesLabel: field("수행 유형 없음 라벨"),
        taxAgencyLabel: field("세무대리 수행 여부 라벨"),
        subsidySettlementLabel: field("보조금 정산 수행 여부 라벨"),
        factsConfirmationLabel: field("사실확인 동의 문구"),
        serverFinalNotice: field("서버 확정 결과 안내"),
      },
      legalWarning:
        "평가 계산식과 내부 저장 키는 보호되며 표시 문구만 편집할 수 있습니다.",
    },
    quoteDocument: {
      name: "고객 발송 견적서 PDF",
      eyebrowLabel: "관리자 구분 문구",
      titleLabel: "관리자 목록 제목",
      descriptionLabel: "관리 안내",
      textFields: {
        auditTitleTemplate: field(
          "외부회계감사 견적서 제목 형식",
          "{{year}}, {{cooperativeName}}, {{supplierName}} 치환값을 사용할 수 있습니다.",
        ),
        generalTitleTemplate: field(
          "일반 견적서 제목 형식",
          "{{supplierName}} 치환값을 사용할 수 있습니다.",
        ),
        recipientTemplate: field(
          "수신자 이름 형식",
          "{{cooperativeName}}, {{customerName}} 치환값을 사용할 수 있습니다.",
        ),
        quoteNumberLabel: field("견적번호 이름"),
        documentVersionLabel: field("문서 버전 이름"),
        recipientSectionTitle: field("수신 영역 제목"),
        recipientEmailLabel: field("수신 이메일 이름"),
        supplierSectionTitle: field("공급자 영역 제목"),
        businessNumberLabel: field("사업자등록번호 이름"),
        addressLabel: field("사업장 주소 이름"),
        supplierContactLabel: field("견적 담당자 이름"),
        contactLabel: field("연락처 이름"),
        missingValue: field("미등록 정보 표시문구"),
        sealMissing: field("직인 미등록 표시문구"),
        logoMissing: field("로고 미등록 표시문구"),
        quoteIntro: field("견적 표 상단 격식 문구"),
        itemHeader: field("항목 열 이름"),
        quantityHeader: field("수량 열 이름"),
        unitPriceHeader: field("단가 열 이름"),
        supplyAmountHeader: field("공급가액 열 이름"),
        subtotalLabel: field("공급가액 합계 이름"),
        vatLabel: field("부가세 이름"),
        totalLabel: field("최종 합계 이름"),
        currencySuffix: field("금액 단위"),
        scoreSuffix: field("점수 단위"),
        countSuffix: field("건수 단위"),
        hourSuffix: field("시간 단위"),
        peopleSuffix: field("인원 단위"),
        conditionsTitle: field("조건 영역 제목"),
        servicePeriodLabel: field("수행기간 이름"),
        validUntilLabel: field("유효기간 이름"),
        termsLabel: field("조건 이름"),
        notesLabel: field("비고 이름"),
        evaluationTitle: field("정량 평가 영역 제목"),
        evaluationConfigLabel: field("평가기준 이름"),
        evaluationScoreLabel: field("정량점수 이름"),
        criterionWeightLabel: field("평가항목 배점 이름"),
        criterionScoreLabel: field("평가항목 획득점수 이름"),
        revenueLabel: field("회계법인 매출액 이름"),
        recentAuditCountLabel: field("최근 농협 감사건수 이름"),
        auditedTypesLabel: field("감사 수행 농협 유형 이름"),
        taxExperienceLabel: field("농협 세무대리 경험 이름"),
        subsidyExperienceLabel: field("보조금 정산 경험 이름"),
        totalHoursLabel: field("총 예정 투입시간 이름"),
        partnerHoursLabel: field("책임회계사 투입시간 이름"),
        teamCountLabel: field("투입인력 이름"),
        yesLabel: field("해당 있음 표시"),
        noLabel: field("해당 없음 표시"),
        footerStatement: field("견적서 하단 신뢰 문구"),
        documentKindLabel: field("문서 종류 제목", "견적서 우측 상단 큰 제목으로 표시됩니다."),
        issueDateLabel: field("발행일 이름"),
        customerRefLabel: field("수신처 이름"),
        phoneLabel: field("전화 이름"),
        emailLabel: field("이메일 이름"),
        credentialsTitle: field("공급자 기본정보 영역 제목"),
        credentialsHelp: field("공급자 기본정보 안내"),
        evaluationFactsTitle: field("제휴사 평가정보 영역 제목"),
        evaluationFactsHelp: field("제휴사 평가정보 안내"),
        evaluationFactsFootnoteAssociation: field("농협감사 협회사 제휴실적 각주"),
        evaluationFactsFootnoteAssociationDef: field("농협감사 협회 설명 각주"),
        engagementPartnerLabel: field("담당회계사 이름"),
        proposerTypeLabel: field("제안 주체 이름"),
        proposerAccountingFirmLabel: field("회계법인 제안 주체 표시"),
        proposerAuditGroupLabel: field("감사반 제안 주체 표시"),
        cpaCountLabel: field("공인회계사 인원 수 이름"),
        localAuditCountLabel: field("2025년 지역농협 감사실적 이름"),
        cooperativeTypeLocalAgri: field("지역농협 유형 이름"),
        cooperativeTypeLocalLivestock: field("지역축협 유형 이름"),
        cooperativeTypeItem: field("품목농협·품목축협 유형 이름"),
        cooperativeTypeGinseng: field("인삼농협 유형 이름"),
        noneTypesLabel: field("해당 없음 표시"),
        taxRateLabel: field("부가세율 이름"),
        taxRateValue: field("부가세율 값"),
        thankYouStatement: field("하단 감사 인사"),
        comparisonQrTitle: field("비교 보고서 QR 제목"),
        comparisonQrHelp: field("비교 보고서 QR 안내"),
        acceptanceTitle: field("고객 확인 영역 제목"),
        acceptanceHint: field("고객 확인 안내"),
        printNameLabel: field("성명 이름"),
        questionsContactLabel: field("문의 이름"),
        supplierFormLegend: field("공급자 정보 영역 제목"),
        supplierFormHelp: field("공급자 기본값 수정 안내"),
        supplierNameInputLabel: field("회계법인명 입력 라벨"),
        supplierBusinessNumberInputLabel: field("사업자등록번호 입력 라벨"),
        supplierAddressInputLabel: field("사업장 주소 입력 라벨"),
        supplierContactNameInputLabel: field("견적 담당자 입력 라벨"),
        supplierContactPhoneInputLabel: field("견적 담당자 연락처 입력 라벨"),
        supplierContactEmailInputLabel: field("견적 담당자 이메일 입력 라벨"),
        logoUploadLabel: field("로고 업로드 라벨"),
        logoRegisteredHelp: field("로고 등록 완료 안내"),
        logoRequiredHelp: field("로고 등록 권장 안내"),
        sealUploadLabel: field("직인 업로드 라벨"),
        sealRegisteredHelp: field("직인 등록 완료 안내"),
        sealRequiredHelp: field("직인 등록 필요 안내"),
        quoteItemInputLabel: field("견적 항목 입력 라벨"),
        quantityInputLabel: field("수량 입력 라벨"),
        unitPriceInputLabel: field("단가 입력 라벨"),
        vatIncludedInputLabel: field("부가세 포함 선택 라벨"),
        vatExcludedOption: field("부가세 별도 선택 문구"),
        vatNoneOption: field("부가세 없음 선택 문구"),
        servicePeriodInputLabel: field("수행기간 입력 라벨"),
        servicePeriodPlaceholder: field("수행기간 입력 예시"),
        validUntilInputLabel: field("유효기간 입력 라벨"),
        validUntilPlaceholder: field("유효기간 입력 예시"),
        termsInputLabel: field("조건 입력 라벨"),
        notesInputLabel: field("비고 입력 라벨"),
        emailSubjectTemplate: field(
          "견적 도착 이메일 제목 형식",
          "{{partnerName}}, {{yearShort}} 치환값을 사용할 수 있습니다.",
        ),
        emailArrivalTemplate: field(
          "견적 도착 이메일 첫 문장",
          "{{partnerName}}, {{versionLabel}} 치환값을 사용할 수 있습니다.",
        ),
        emailRevisionSubjectTemplate: field(
          "수정 견적 이메일 제목 형식",
          "{{partnerName}}, {{yearShort}} 치환값을 사용할 수 있습니다. 회계감사 견적은 첫 발송과 같은 제목을 사용합니다.",
        ),
        emailRevisionArrivalTemplate: field(
          "수정 견적 이메일 첫 문장",
          "{{partnerName}}, {{versionLabel}} 치환값을 사용할 수 있습니다. v2 이후 발송에 사용됩니다.",
        ),
        emailTemporaryAccountNotice: field("임시회원 계정 안내"),
        emailAccountIdLabel: field("임시회원 아이디 이름"),
        emailActivationLinkLabel: field("비밀번호 설정 링크 문구"),
        emailSecurityNotice: field("임시비밀번호 보안 안내"),
        emailExistingAccountPrefix: field("기존 비밀번호 사용자 안내"),
        emailDownloadLinkLabel: field("견적서 다운로드 링크 문구"),
        emailDownloadTextLabel: field("텍스트 이메일 다운로드 이름"),
      },
      legalWarning:
        "문서 식별자, 금액 계산, 고객·공급자 실제 값과 전자서명은 보호됩니다. 표시 형식과 디자인만 편집할 수 있습니다.",
    },
  },
  "partner.apply": {
    hero: {
      name: "제휴 신청 첫 안내",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "화면 제목",
      descriptionLabel: "제휴 신청 안내",
      textFields: {
        loginPrompt: field("기존 계정 안내"),
        loginLabel: field("제휴사 로그인 링크"),
      },
    },
    form: {
      name: "제휴 신청 입력 안내",
      titleLabel: "영역 제목",
      descriptionLabel: "입력 도움말",
      textFields: {
        organizationNameLabel: field("업체명 라벨"),
        displayNameLabel: field("표시명 라벨"),
        displayNamePlaceholder: field("표시명 입력 예시"),
        professionLabel: field("직역 라벨"),
        managerNameLabel: field("담당자명 라벨"),
        emailLabel: field("이메일 라벨"),
        phoneLabel: field("연락처 라벨"),
        businessNumberLabel: field("사업자등록번호 라벨"),
        businessNumberPlaceholder: field("사업자등록번호 입력 예시"),
        businessAddressLabel: field("사업장 주소 라벨"),
        supportFieldsLegend: field("업무범위 영역 제목"),
        memoLabel: field("소개 및 운영 메모 라벨"),
        privacyConsentLabel: field(
          "개인정보 수집·이용 동의 문구",
          "필수 여부와 저장 키는 보호됩니다.",
        ),
        honeypotLabel: field("스팸 방지 입력 접근성 이름"),
      },
      legalWarning:
        "개인정보 동의 필수 여부, 스팸 방지 입력과 제출 저장 키는 변경할 수 없습니다.",
    },
  },
  "framework.notFound": {
    notFound: {
      name: "페이지 없음 안내",
      eyebrowLabel: "상태 번호",
      titleLabel: "안내 제목",
      descriptionLabel: "안내 설명",
    },
  },
  "public.consult": {
    steps: {
      name: "상담 진행 순서",
      eyebrowLabel: "영문 안내",
      titleLabel: "접근성 목록 이름",
      textFields: {
        ariaLabel: field("진행 순서 접근성 이름"),
        stepPrefix: field("단계 앞 문구"),
      },
      itemFields: {
        title: "단계 이름",
        description: "단계 설명",
      },
    },
    hero: {
      name: "문의 작성 첫 안내",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "큰 제목",
    },
    categorySelector: {
      name: "문의 유형 선택",
      titleLabel: "입력 표시 이름",
      descriptionLabel: "선택 도움말",
      textFields: { ariaLabel: field("접근성 이름") },
      itemFields: { title: "화면 표시 이름" },
    },
    visibilitySelector: {
      name: "공개 범위 선택",
      titleLabel: "입력 표시 이름",
      textFields: { ariaLabel: field("접근성 이름") },
      itemFields: {
        title: "화면 표시 이름",
        description: "선택 시 안내",
      },
    },
    requestFields: {
      name: "문의 내용과 첨부",
      titleLabel: "관리자 목록 이름",
      textFields: {
        followupNotice: field("후속 문의 안내"),
        subjectLabel: field("제목 표시 이름"),
        subjectPlaceholder: field("제목 입력 안내"),
        messageLabel: field("내용 표시 이름"),
        messagePlaceholder: field("내용 입력 안내"),
        photoLabel: field("사진 첨부 표시 이름"),
        optionalLabel: field("선택 배지"),
        photoButtonTitle: field("사진 추가 버튼"),
        photoHelp: field("사진 형식·용량 안내"),
        photoListAriaLabel: field("첨부 목록 접근성 이름"),
        deleteSuffix: field("첨부 삭제 접근성 문구"),
        bytesUnit: field("바이트 단위"),
        kilobytesUnit: field("킬로바이트 단위"),
        megabytesUnit: field("메가바이트 단위"),
        submitLabel: field("문의 등록 버튼"),
        submittingLabel: field("등록 처리 중 문구"),
      },
    },
    success: {
      name: "문의 접수 완료",
      titleLabel: "완료 제목",
      descriptionLabel: "완료 설명",
      textFields: {
        requestNumberLabel: field("접수번호 표시 이름"),
        resetLabel: field("새 문의 작성 버튼"),
      },
    },
  },
  "public.inquiries": {
    hero: {
      name: "문의 게시판 첫 안내",
      eyebrowLabel: "영문 안내",
      titleLabel: "큰 제목",
      descriptionLabel: "설명",
      textFields: { highlight: field("강조 문구") },
    },
    filters: {
      name: "검색과 목록 필터",
      titleLabel: "관리자 목록 이름",
      textFields: {
        boardAriaLabel: field("게시판 접근성 이름"),
        countPrefix: field("건수 앞 문구"),
        countSuffix: field("건수 뒤 문구"),
        allFilter: field("전체 문의 필터"),
        organizationFilter: field("우리 농협 문의 필터"),
        mineFilter: field("나의 문의 필터"),
        searchLabel: field("검색 표시 이름"),
        searchPlaceholder: field("검색 입력 안내"),
        filtersAriaLabel: field("필터 접근성 이름"),
        allGuestSummary: field("비회원 전체 목록 설명"),
        allMemberSummary: field("회원 전체 목록 설명"),
        organizationSummary: field("우리 농협 목록 설명"),
        mineSummary: field("나의 문의 목록 설명"),
      },
    },
    list: {
      name: "문의와 답변 목록",
      titleLabel: "관리자 목록 이름",
      textFields: {
        missingRequestNumber: field("접수번호 없음 안내"),
        requestHeading: field("문의 본문 제목"),
        answerHeading: field("답변 제목"),
        answerPending: field("답변 준비 중 안내"),
        lockedTitle: field("권한 제한 제목"),
        lockedDescription: field("권한 제한 설명"),
        loginLabel: field("로그인 이동 버튼"),
        visibilityPublic: field("전체 공개 배지"),
        visibilityOrganization: field("우리 농협 공개 배지"),
        visibilityPrivate: field("비공개 배지"),
        statusReceived: field("접수 완료 배지"),
        statusAnswered: field("답변 완료 배지"),
        statusCompleted: field("완료 배지"),
        statusFollowup: field("추가 문의 배지"),
        previewPublicSubject: field("미리보기 전체 공개 문의 제목"),
        previewPublicMessage: field("미리보기 전체 공개 문의 내용"),
        previewPublicAnswer: field("미리보기 답변 내용"),
        previewLockedSubject: field("미리보기 권한 제한 문의 제목"),
      },
    },
  },
  "public.faq": {
    hero: {
      name: "FAQ 첫 안내",
      eyebrowLabel: "영문 안내",
      titleLabel: "큰 제목",
      descriptionLabel: "설명",
      textFields: { highlight: field("강조 문구") },
    },
    filters: {
      name: "FAQ 검색과 유형",
      titleLabel: "관리자 목록 이름",
      textFields: {
        boardAriaLabel: field("FAQ 접근성 이름"),
        countPrefix: field("건수 앞 문구"),
        countSuffix: field("건수 뒤 문구"),
        summary: field("검색 도움말"),
        categoryLabel: field("유형 선택 표시 이름"),
        allCategoriesLabel: field("전체 유형 선택 문구"),
        searchLabel: field("검색 표시 이름"),
        searchPlaceholder: field("검색 입력 안내"),
      },
    },
    list: {
      name: "질문과 답변",
      titleLabel: "목록 이름",
      itemFields: {
        label: "질문 유형",
        title: "질문",
        description: "답변",
      },
    },
  },
  "member.mypage": {
    navigation: {
      name: "마이페이지 메뉴와 공통 안내",
      titleLabel: "관리자 목록 이름",
      legalWarning:
        "메뉴 연결값, 로그인 상태 확인과 이동 주소는 변경할 수 없습니다. 회원에게 보이는 이름과 안내만 편집됩니다.",
      textFields: Object.fromEntries(
        [
          ["navigationAriaLabel", "메뉴 접근성 이름"],
          ["brandMark", "서비스 상징 글자"],
          ["serviceName", "서비스 이름"],
          ["brandSubtitle", "회원 화면 이름"],
          ["breadcrumbPrefix", "현재 위치 앞 문구"],
          ["fallbackMemberName", "회원 이름 기본값"],
          ["avatarFallback", "회원 사진 기본 글자"],
          ["profileIncomplete", "프로필 미완료 상태"],
          ["organizationPending", "소속 확인 중 상태"],
          ["missingValue", "정보 없음 표시"],
          ["unknownValue", "알 수 없는 값 표시"],
          ["pointUnit", "포인트 단위"],
          ["homeLabel", "홈 이동 버튼"],
          ["logoutLabel", "로그아웃 버튼"],
          ["lastSyncPrefix", "마지막 동기화 앞 문구"],
          ["refreshLabel", "새로고침 버튼"],
          ["refreshingLabel", "새로고침 처리 중 문구"],
          ["newInquiryLabel", "새 문의 버튼"],
          ["incompleteNotice", "회원가입 미완료 안내"],
          ["continueSignupLabel", "회원가입 이어가기 버튼"],
          ["closeLabel", "알림 닫기 접근성 이름"],
        ].map(([key, label]) => [
          key,
          field(label, "마이페이지 공통 영역에서 회원에게 표시됩니다."),
        ]),
      ),
      itemFields: {
        title: "메뉴 표시 이름",
        description: "메뉴에서 확인할 수 있는 내용",
      },
    },
    sitemap: {
      name: "고객 사이트맵",
      titleLabel: "사이트맵 제목",
      descriptionLabel: "사이트맵 안내",
      legalWarning:
        "실제 URL과 고객 접근 권한은 App Router와 서버 권한에서 자동 판정됩니다. 표시 문구만 편집할 수 있습니다.",
      textFields: {
        publicGroupTitle: field("공개 서비스 그룹 제목"),
        roleGroupTitle: field("고객 전용 그룹 제목"),
        countPrefix: field("페이지 수 앞 문구"),
        countSuffix: field("페이지 수 뒤 문구"),
        automaticUpdateLabel: field("자동 갱신 안내"),
        openLabel: field("페이지 열기 버튼"),
      },
    },
    overview: {
      name: "이용 현황 요약",
      titleLabel: "영역 제목",
      textFields: Object.fromEntries(
        [
          ["inquiriesTopbarTitle", "문의 탭 상단 제목"],
          ["inquiriesTopbarDescription", "문의 탭 상단 설명"],
          ["balanceLabel", "보유 포인트 제목"],
          ["organizationFallback", "소속 농협 기본값"],
          ["walletSuffix", "지갑 이름 뒤 문구"],
          ["inquiryCountLabel", "등록 문의 수 제목"],
          ["inquiryCountHelp", "등록 문의 수 설명"],
          ["unreadAnswersLabel", "미열람 답변 수 제목"],
          ["unreadAnswersHelp", "미열람 답변 수 설명"],
          ["viewedAnswersLabel", "열람 답변 수 제목"],
          ["viewedAnswersHelp", "열람 답변 수 설명"],
          ["recentInquiriesTitle", "최근 문의 제목"],
          ["recentInquiriesDescription", "최근 문의 설명"],
          ["recentPointsTitle", "최근 포인트 제목"],
          ["recentPointsDescription", "최근 포인트 설명"],
          ["viewAllLabel", "전체 보기 버튼"],
          ["countSuffix", "건수 단위"],
          ["requestNumberHeading", "문의번호 열 이름"],
          ["subjectHeading", "제목 열 이름"],
          ["visibilityHeading", "공개범위 열 이름"],
          ["statusHeading", "상태 열 이름"],
          ["createdHeading", "등록일 열 이름"],
          ["emptyInquiriesLink", "문의 없음 이동 링크"],
          ["ledgerFallback", "포인트 항목 기본 이름"],
          ["visibilityPublic", "전체 공개 표시"],
          ["visibilityOrganization", "우리 농협 공개 표시"],
          ["visibilityPrivate", "비공개 표시"],
          ["statusSubmitted", "답변 대기 상태"],
          ["statusAnswered", "답변 완료 상태"],
          ["statusPublished", "답변 열람 상태"],
          ["statusFollowup", "추가 문의 상태"],
          ["statusCompleted", "상담 종료 상태"],
          ["ledgerFirstSignup", "농협 최초 가입 적립 이름"],
          ["ledgerUserSignup", "회원 가입 적립 이름"],
          ["ledgerAnswerView", "답변 열람 차감 이름"],
          ["ledgerManual", "수동 조정 이름"],
          ["ledgerAdminCredit", "운영자 적립 이름"],
          ["ledgerAdminDebit", "운영자 차감 이름"],
        ].map(([key, label]) => [
          key,
          field(label, "이용 현황 카드와 최근 내역에 표시됩니다."),
        ]),
      ),
    },
    inquiries: {
      name: "내 문의 목록",
      titleLabel: "목록 제목",
      descriptionLabel: "목록 설명",
      textFields: Object.fromEntries(
        [
          ["newInquiryLabel", "새 문의 버튼"],
          ["requestNumberHeading", "문의번호 열 이름"],
          ["subjectHeading", "제목 열 이름"],
          ["visibilityHeading", "공개범위 열 이름"],
          ["statusHeading", "상태 열 이름"],
          ["answerHeading", "답변 열 이름"],
          ["createdHeading", "등록일 열 이름"],
          ["viewedAnswerLabel", "열람 완료 표시"],
          ["viewAnswerLabel", "답변 확인 표시"],
          ["answerPendingLabel", "답변 대기 표시"],
          ["detailLabel", "상세 보기 버튼"],
          ["emptyLinkLabel", "문의 없음 이동 링크"],
          ["actionsHeading", "작업 열 접근성 이름"],
        ].map(([key, label]) => [
          key,
          field(label, "내 문의 목록에서 회원에게 표시됩니다."),
        ]),
      ),
    },
    points: {
      name: "포인트 내역과 이용 안내",
      titleLabel: "영역 제목",
      legalWarning:
        "포인트 적립·차감 계산과 이벤트 저장값은 변경할 수 없습니다. 표시 문구와 이용 안내만 편집됩니다.",
      textFields: Object.fromEntries(
        [
          ["balanceLabel", "현재 잔액 제목"],
          ["walletSuffix", "지갑 이름 뒤 문구"],
          ["earnedLabel", "총 적립 제목"],
          ["earnedHelp", "총 적립 설명"],
          ["usedLabel", "총 사용 제목"],
          ["usedHelp", "총 사용 설명"],
          ["countLabel", "포인트 이력 수 제목"],
          ["countHelp", "포인트 이력 수 설명"],
          ["guideTitle", "포인트 안내 제목"],
          ["guideDescription", "포인트 안내 설명"],
          ["historyTitle", "사용 내역 제목"],
          ["historyDescription", "사용 내역 설명"],
          ["dateHeading", "일시 열 이름"],
          ["eventHeading", "이벤트 열 이름"],
          ["descriptionHeading", "설명 열 이름"],
          ["changeHeading", "변동 열 이름"],
          ["balanceHeading", "잔액 열 이름"],
        ].map(([key, label]) => [
          key,
          field(label, "포인트 요약과 사용 내역에서 표시됩니다."),
        ]),
      ),
      itemFields: { title: "포인트 이용 안내 문구" },
    },
    profile: {
      name: "회원 정보와 수신 동의",
      titleLabel: "회원 정보 제목",
      descriptionLabel: "회원 정보 설명",
      legalWarning:
        "필수 동의 여부와 계정 저장값은 변경할 수 없습니다. 선택 수신 항목의 표시 문구만 편집됩니다.",
      textFields: Object.fromEntries(
        [
          ["nameLabel", "이름 항목"],
          ["emailLabel", "이메일 항목"],
          ["phoneLabel", "연락처 항목"],
          ["organizationLabel", "소속 농협 항목"],
          ["organizationMissing", "소속 미등록 표시"],
          ["organizationPending", "소속 확인 중 표시"],
          ["positionLabel", "직책 항목"],
          ["dutyLabel", "담당 업무 항목"],
          ["joinedLabel", "가입일 항목"],
          ["businessCardLabel", "명함 항목"],
          ["businessCardView", "명함 보기 링크"],
          ["businessCardEmpty", "명함 없음 표시"],
          ["walletTitle", "소속 농협 지갑 제목"],
          ["walletDescription", "소속 농협 지갑 설명"],
          ["walletOrganizationLabel", "지갑 농협명 항목"],
          ["walletBalanceLabel", "지갑 잔액 항목"],
          ["walletEarnedLabel", "누적 적립 항목"],
          ["walletUsedLabel", "누적 사용 항목"],
          ["walletMemberCountLabel", "조직 회원 수 항목"],
          ["memberSuffix", "회원 수 단위"],
          ["walletCreatedLabel", "조직 생성일 항목"],
          ["walletUpdatedLabel", "최근 업데이트 항목"],
          ["consentsTitle", "동의 항목 제목"],
          ["consentsDescription", "동의 항목 설명"],
          ["requiredConsentsTitle", "필수 동의 제목"],
          ["termsLabel", "이용약관 동의 이름"],
          ["privacyLabel", "개인정보 동의 이름"],
          ["optionalConsentsTitle", "선택 수신 동의 제목"],
          ["optionalConsentsDescription", "선택 수신 동의 설명"],
          ["marketingLabel", "마케팅 수신 이름"],
          ["consentEmailLabel", "이메일 수신 이름"],
          ["smsLabel", "문자 수신 이름"],
          ["kakaoLabel", "카카오 알림 수신 이름"],
          ["agreedLabel", "동의 상태"],
          ["disagreedLabel", "미동의 상태"],
          ["savingLabel", "동의 저장 중 문구"],
          ["incompleteTitle", "회원가입 미완료 제목"],
          ["incompleteDescription", "회원가입 미완료 설명"],
          ["continueSignupLabel", "회원가입 이어가기 버튼"],
        ].map(([key, label]) => [
          key,
          field(label, "회원 정보와 수신 동의 영역에 표시됩니다."),
        ]),
      ),
    },
  },
  "member.quotes": {
    hero: {
      name: "견적함 첫 안내",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "화면 제목",
      descriptionLabel: "다운로드 안내",
    },
  },
  "member.quoteDetail": {
    summary: {
      name: "견적서 상세 요약",
      titleLabel: "영역 제목",
      descriptionLabel: "견적서 상세 설명",
    },
  },
  "member.requestDetail": {
    summary: {
      name: "문의 상세 요약",
      eyebrowLabel: "상단 작은 문구",
      titleLabel: "관리자 목록 이름",
      textFields: Object.fromEntries(
        [
          ["backLabel", "문의 목록 이동 링크"],
          ["backHint", "목록 이동 도움말"],
          ["statusLabel", "상태 항목"],
          ["visibilityLabel", "공개범위 항목"],
          ["pointsLabel", "보유 포인트 항목"],
          ["pointUnit", "포인트 단위"],
          ["missingValue", "정보 없음 표시"],
          ["visibilityPublic", "전체 공개 표시"],
          ["visibilityOrganization", "우리 농협 공개 표시"],
          ["visibilityPrivate", "비공개 표시"],
          ["statusSubmitted", "답변 대기 상태"],
          ["statusAnswered", "답변 완료 상태"],
          ["statusPublished", "답변 열람 상태"],
          ["statusFollowup", "추가 문의 상태"],
          ["statusCompleted", "상담 종료 상태"],
        ].map(([key, label]) => [
          key,
          field(label, "문의 상세 상단 요약에 표시됩니다."),
        ]),
      ),
    },
    requestBody: {
      name: "문의 본문",
      eyebrowLabel: "영역 배지",
      titleLabel: "영역 제목",
      textFields: { receivedPrefix: field("접수일 앞 문구") },
    },
    attachments: {
      name: "첨부 사진",
      eyebrowLabel: "영역 배지",
      titleLabel: "영역 제목",
      textFields: { countSuffix: field("첨부 수 단위") },
    },
    answer: {
      name: "답변과 포인트 열람",
      eyebrowLabel: "영역 배지",
      titleLabel: "답변 등록 제목",
      descriptionLabel: "답변 준비 중 제목",
      legalWarning:
        "답변 열람 API, 포인트 차감과 중복 차감 방지 로직은 변경할 수 없습니다. 안내 문구만 편집됩니다.",
      textFields: Object.fromEntries(
        [
          ["emptyBody", "답변 본문 없음 안내"],
          ["pointPrefix", "포인트 차감 앞 문구"],
          ["pointSuffix", "포인트 차감 뒤 문구"],
          ["noDuplicateCharge", "중복 차감 방지 안내"],
          ["loadingLabel", "답변 열람 처리 중 버튼"],
          ["openLabel", "답변 열람 버튼"],
          ["pendingDescription", "답변 준비 중 설명"],
        ].map(([key, label]) => [
          key,
          field(label, "답변 열람 영역에서 회원에게 표시됩니다."),
        ]),
      ),
    },
    followupActions: {
      name: "답변 확인 후 다음 단계",
      eyebrowLabel: "영역 배지",
      titleLabel: "영역 제목",
      descriptionLabel: "영역 설명",
      legalWarning:
        "후속 문의 종류, 연결되는 문의 ID와 입력값은 변경할 수 없습니다. 버튼 이름과 설명만 편집됩니다.",
      textFields: Object.fromEntries(
        [
          ["followupTitle", "추가 문의 버튼 제목"],
          ["followupDescription", "추가 문의 버튼 설명"],
          ["estimateTitle", "추가상담·견적 버튼 제목"],
          ["estimateDescription", "추가상담·견적 버튼 설명"],
          ["completedTitle", "문의 완료 상태 제목"],
          ["completedDescription", "문의 완료 상태 설명"],
          ["completeTitle", "문의 완료 버튼 제목"],
          ["completeDescription", "문의 완료 버튼 설명"],
        ].map(([key, label]) => [
          key,
          field(label, "답변 확인 후 선택할 다음 단계에 표시됩니다."),
        ]),
      ),
    },
    rating: {
      name: "답변 평가",
      titleLabel: "평가 제목",
      descriptionLabel: "평가 도움말",
      legalWarning:
        "평가 점수 범위, 저장 항목과 문의 완료 순서는 변경할 수 없습니다. 표시 문구만 편집됩니다.",
      textFields: Object.fromEntries(
        [
          ["completedBadge", "평가 작성 완료 표시"],
          ["requiredBadge", "평가 필수 표시"],
          ["scoreAriaLabel", "점수 선택 접근성 이름"],
          ["scoreSuffix", "점수 단위"],
          ["helpfulLabel", "도움됨 선택 문구"],
          ["needsWorkLabel", "보완 필요 선택 문구"],
          ["commentPlaceholder", "평가 의견 입력 안내"],
          ["savingLabel", "평가 저장 중 버튼"],
          ["updateLabel", "평가 수정 버튼"],
          ["saveLabel", "평가 저장 버튼"],
          ["completingLabel", "문의 완료 처리 중 버튼"],
          ["completeLabel", "문의 완료 버튼"],
        ].map(([key, label]) => [
          key,
          field(label, "답변 평가 입력 영역에 표시됩니다."),
        ]),
      ),
    },
    dialogs: {
      name: "답변 열람과 문의 완료 확인 창",
      titleLabel: "관리자 목록 이름",
      legalWarning:
        "포인트 계산, 열람·완료 API와 처리 순서는 변경할 수 없습니다. 확인 창의 설명과 버튼 문구만 편집됩니다.",
      textFields: Object.fromEntries(
        [
          ["completeEyebrow", "문의 완료 확인 배지"],
          ["completeTitle", "문의 완료 확인 제목"],
          ["completeDescription", "문의 완료 확인 설명"],
          ["continueLabel", "계속 상담 버튼"],
          ["completingLabel", "문의 완료 처리 중 버튼"],
          ["endLabel", "상담 종료 버튼"],
          ["viewTitle", "답변 열람 확인 제목"],
          ["pointPrefix", "포인트 차감 앞 문구"],
          ["pointSuffix", "포인트 차감 뒤 문구"],
          ["noDuplicateCharge", "중복 차감 방지 안내"],
          ["costLabel", "차감 예정 포인트 항목"],
          ["balanceLabel", "현재 보유 포인트 항목"],
          ["insufficient", "포인트 부족 안내"],
          ["cancelLabel", "취소 버튼"],
          ["processingLabel", "열람 처리 중 버튼"],
          ["viewLabel", "답변 열람 확인 버튼"],
        ].map(([key, label]) => [
          key,
          field(label, "답변 열람 또는 상담 종료 확인 창에 표시됩니다."),
        ]),
      ),
    },
  },
  "admin.operations": {
    navigation: {
      name: "운영 메뉴와 공통 상단",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "관리 안내",
      legalWarning:
        "메뉴 ID와 연결되는 관리자 기능은 변경할 수 없습니다. 화면에 표시되는 이름과 설명만 편집됩니다.",
      textFields: {
        overviewDescription: field("운영 대시보드 설명"),
        membersDescription: field("회원 관리 설명"),
        partnersDescription: field("제휴사 관리 설명"),
        inquiriesDescription: field("상담 관리 설명"),
        auditQuotesDescription: field("회계감사 견적 설명"),
        auditEvaluationsDescription: field("감사평가 운영 설명"),
        pointsDescription: field("포인트 관리 설명"),
        auditDescription: field("운영 기록 설명"),
        sitemapDescription: field("사이트맵 설명"),
        navigationAriaLabel: field("메뉴 접근성 이름"),
        brandName: field("서비스 이름"),
        brandSubtitle: field("운영 화면 이름"),
        operatorRole: field("관리자 역할 표시"),
        backToContent: field("콘텐츠 관리 이동 버튼"),
        logout: field("로그아웃 버튼"),
        breadcrumbPrefix: field("현재 위치 앞 문구"),
        lastSynced: field("마지막 동기화 문구"),
        refresh: field("새로고침 버튼"),
        refreshing: field("새로고침 처리 중"),
        closeAriaLabel: field("알림 닫기 접근성 이름"),
      },
      itemFields: { title: "메뉴 표시 이름" },
    },
    sitemap: {
      name: "관리자 사이트맵",
      titleLabel: "사이트맵 제목",
      descriptionLabel: "사이트맵 안내",
      legalWarning:
        "실제 URL과 접근 권한은 App Router와 서버 권한에서 자동 판정됩니다. 표시 문구만 편집할 수 있습니다.",
      textFields: {
        publicGroupTitle: field("공개 서비스 그룹 제목"),
        roleGroupTitle: field("관리자 전용 그룹 제목"),
        countPrefix: field("페이지 수 앞 문구"),
        countSuffix: field("페이지 수 뒤 문구"),
        automaticUpdateLabel: field("자동 갱신 안내"),
        openLabel: field("페이지 열기 버튼"),
      },
    },
    overview: {
      name: "운영 대시보드",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      textFields: {
        memberKpi: field("가입 회원 지표"),
        requestKpi: field("문의 접수 지표"),
        answerKpi: field("등록 답변 지표"),
        ratingKpi: field("고객 평가 지표"),
        trendTitle: field("운영 추이 제목"),
        trendDescription: field("운영 추이 설명"),
        metricsTitle: field("주요 지표 제목"),
        metricsDescription: field("주요 지표 설명"),
        recentActivityTitle: field("최근 활동 제목"),
        recentActivityDescription: field("최근 활동 설명"),
        productionDataNotice: field("운영 데이터 전용 집계 안내"),
        topOrganizationsTitle: field("문의 상위 농협 제목"),
        topOrganizationsDescription: field("문의 상위 농협 설명"),
        noActivity: field("활동 없음 안내"),
        noData: field("자료 없음 안내"),
      },
    },
    members: {
      name: "회원과 운영자 관리",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      legalWarning:
        "회원·운영자 상태 값, 권한과 개인정보 조회 범위는 고정되어 있습니다. 표시 문구만 편집됩니다.",
      textFields: {
        subtabsAriaLabel: field("하위 메뉴 접근성 이름"),
        memberTabDescription: field("회원 관리 설명"),
        operatorTabDescription: field("운영자 관리 설명"),
        memberListTitle: field("회원 목록 제목"),
        memberSearchPlaceholder: field("회원 검색 안내"),
        operatorListTitle: field("운영자 목록 제목"),
        operatorSearchPlaceholder: field("운영자 검색 안내"),
        addOperator: field("운영자 추가 버튼"),
        memberEmpty: field("회원 검색 결과 없음"),
        operatorEmpty: field("운영자 검색 결과 없음"),
        memberDetailTitle: field("회원 상세 제목"),
        operatorDetailTitle: field("운영자 상세 제목"),
        noMemberSelected: field("회원 미선택 안내"),
        noOperatorSelected: field("운영자 미선택 안내"),
        changeCooperativeButton: field("소속 농협 변경 버튼"),
        cooperativeEditorAriaLabel: field("소속 변경 창 접근성 이름"),
        cooperativeEditorEyebrow: field("소속 변경 창 상단 문구"),
        cooperativeEditorTitle: field("소속 변경 창 제목"),
        cooperativeEditorDescription: field("소속 변경 안내"),
        currentCooperativeLabel: field("현재 소속 라벨"),
        newCooperativeSearchLabel: field("농협 검색 라벨"),
        newCooperativeSearchPlaceholder: field("농협 검색 입력 안내"),
        cooperativeSearchLoading: field("농협 검색 중 안내"),
        cooperativeSearchEmpty: field("농협 검색 결과 없음"),
        cooperativeChangeReasonLabel: field("소속 변경 사유 라벨"),
        cooperativeChangeReasonPlaceholder: field("소속 변경 사유 입력 안내"),
        cooperativeChangeCancel: field("소속 변경 취소 버튼"),
        cooperativeChangeConfirm: field("소속 변경 확인 버튼"),
        cooperativeChangeSaving: field("소속 변경 처리 중"),
        cooperativeChangeSuccess: field("소속 변경 성공 안내"),
        cooperativeChangeFailed: field("소속 변경 실패 안내"),
        cooperativeChangeUnchanged: field("동일 소속 안내"),
        cooperativeMasterTabDescription: field("농협 마스터 메뉴 설명"),
        cooperativeMasterTitle: field("농협 마스터 제목"),
        cooperativeMasterDescription: field("농협 마스터 설명"),
        cooperativeMasterTotal: field("농협 전체 건수 라벨"),
        cooperativeMasterAdd: field("농협 신규 등록 버튼"),
        cooperativeMasterSearchLabel: field("농협 검색 라벨"),
        cooperativeMasterSearchPlaceholder: field("농협 검색 입력 안내"),
        cooperativeMasterSearch: field("농협 검색 버튼"),
        cooperativeMasterLoading: field("농협 목록 로딩 안내"),
        cooperativeMasterLoadFailed: field("농협 목록 오류 안내"),
        cooperativeMasterSaveFailed: field("농협 저장 오류 안내"),
        cooperativeMasterStale: field("농협 동시 수정 안내"),
        cooperativeMasterName: field("농협명 라벨"),
        cooperativeMasterType: field("농협 유형 라벨"),
        cooperativeMasterRegion: field("농협 지역 라벨"),
        cooperativeMasterStatus: field("농협 운영 상태 라벨"),
        cooperativeMasterSuccessor: field("통합 승계 농협 라벨"),
        cooperativeMasterUpdatedAt: field("농협 수정일 라벨"),
        cooperativeMasterEdit: field("농협 수정 버튼"),
        cooperativeMasterEmpty: field("농협 검색 결과 없음"),
        cooperativeMasterMore: field("농협 다음 목록 버튼"),
        cooperativeMasterEditorAriaLabel: field("농협 편집 창 접근성 이름"),
        cooperativeMasterEyebrow: field("농협 편집 창 상단 문구"),
        cooperativeMasterEditTitle: field("농협 수정 창 제목"),
        cooperativeMasterCreateTitle: field("농협 등록 창 제목"),
        cooperativeMasterSido: field("시·도 라벨"),
        cooperativeMasterSigungu: field("시·군·구 라벨"),
        cooperativeMasterAddress: field("농협 주소 라벨"),
        cooperativeMasterEffectiveFrom: field("적용 시작일 라벨"),
        cooperativeMasterSuccessorSearch: field("승계 농협 검색 라벨"),
        cooperativeMasterSuccessorPlaceholder: field("승계 농협 검색 안내"),
        cooperativeMasterSelectedSuccessor: field("선택 승계 농협 안내"),
        cooperativeMasterHistoryWarning: field("과거 이력 보존 안내"),
        cooperativeMasterSaving: field("농협 저장 중 안내"),
        cooperativeMasterSave: field("농협 저장 버튼"),
        "cooperativeMasterStatus.active": field("운영 상태 이름"),
        "cooperativeMasterStatus.pending": field("등록 대기 상태 이름"),
        "cooperativeMasterStatus.merged": field("통합 상태 이름"),
        "cooperativeMasterStatus.closed": field("폐쇄 상태 이름"),
        cooperativeMasterTypeLocal: field("지역농협 유형 이름"),
        cooperativeMasterTypeLivestock: field("축협 유형 이름"),
        cooperativeMasterTypeCommodity: field("품목농협 유형 이름"),
      },
      itemFields: { title: "하위 메뉴 표시 이름" },
    },
    partners: {
      name: "제휴사 관리",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      legalWarning:
        "제휴사 ID, 배정 상태, 답변 승인 권한과 포인트 검증 범위는 코드에서 고정됩니다. 표시 문구만 편집됩니다.",
      textFields: {
        listTitle: field("제휴사 목록 제목"),
        listDescription: field("제휴사 목록 설명"),
        addPartner: field("제휴사 추가 버튼"),
        editPartner: field("제휴사 수정 버튼"),
        assignmentTitle: field("문의 배정 현황 제목"),
        draftTitle: field("답변 초안 목록 제목"),
        approveDraft: field("답변 초안 승인 버튼"),
        requestRevision: field("수정 요청 버튼"),
        businessRegistrationNumberLabel: field("사업자등록번호 항목"),
        businessAddressLabel: field("사업장 주소 항목"),
        businessRegistrationNumberPlaceholder: field("사업자등록번호 입력 예시"),
        businessRegistrationNumberInvalid: field("사업자등록번호 오류 안내"),
        businessRegistrationNumberRequired: field("사업자등록번호 필수 안내"),
        businessAddressRequired: field("사업장 주소 필수 안내"),
        quoteProfileTitle: field("견적 발송 정보 제목"),
        quoteProfileDescription: field("견적 발송 정보 설명"),
        quoteProfileReady: field("견적 정보 완료 안내"),
        quoteProfileMissingPrefix: field("견적 정보 부족 안내"),
        quoteProfileLogoRecommended: field("로고 권장 표시"),
        quoteProfileConsentRecommended: field("대행 동의 확인 표시"),
        logoLabel: field("로고 항목"),
        sealLabel: field("직인 항목"),
        logoHelp: field("로고 업로드 도움말"),
        sealHelp: field("직인 업로드 도움말"),
        assetRegistered: field("파일 등록됨 표시"),
        assetMissing: field("파일 미등록 표시"),
        logoUploadSuccess: field("로고 등록 성공 안내"),
        logoUploadFailed: field("로고 등록 실패 안내"),
        sealUploadSuccess: field("직인 등록 성공 안내"),
        sealUploadFailed: field("직인 등록 실패 안내"),
        proxyConsentLabel: field("대행 발송 동의 항목"),
        proxyConsentHelp: field("대행 발송 동의 도움말"),
        proxyConsentOn: field("대행 동의함 표시"),
        proxyConsentOff: field("대행 미동의 표시"),
        evaluationDefaultsTitle: field("평가 기본값 제목"),
        evaluationDefaultsDescription: field("평가 기본값 설명"),
        evaluationDefaultsSave: field("견적 기본정보 저장 버튼"),
        evaluationDefaultsSaved: field("견적 기본정보 저장 성공 안내"),
        evaluationDefaultsSaveFailed: field("견적 기본정보 저장 실패 안내"),
        evaluationDefaultsInvalid: field("평가 기본값 미입력 안내"),
        quoteProfileTerminated: field("종료 제휴사 수정 불가 안내"),
      },
    },
    inquiries: {
      name: "상담과 FAQ 관리",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      legalWarning:
        "문의 상태·공개 범위·FAQ 저장 값은 고정되어 있습니다. 선택지의 표시 이름만 편집됩니다.",
      textFields: {
        subtabsAriaLabel: field("하위 메뉴 접근성 이름"),
        requestTabDescription: field("문의 관리 설명"),
        faqTabDescription: field("FAQ 관리 설명"),
        requestListTitle: field("문의 목록 제목"),
        unifiedSearch: field("통합 검색 이름"),
        requestSearchPlaceholder: field("문의 검색 안내"),
        requestSearchAriaLabel: field("문의 검색 접근성 이름"),
        clearSearchAriaLabel: field("검색어 지우기 접근성 이름"),
        inquiryEmpty: field("문의 검색 결과 없음"),
        faqTitle: field("FAQ 관리 제목"),
        faqDescription: field("FAQ 관리 설명"),
        faqSearchPlaceholder: field("FAQ 검색 안내"),
        faqLoading: field("FAQ 불러오는 중"),
        faqEmpty: field("등록 FAQ 없음"),
        faqFilteredEmpty: field("FAQ 검색 결과 없음"),
        addFaq: field("FAQ 추가 버튼"),
      },
      itemFields: { title: "선택지 표시 이름" },
    },
    auditQuotes: {
      name: "회계감사 견적 접수",
      titleLabel: "목록 제목",
      descriptionLabel: "목록 설명",
      legalWarning:
        "접수 상태 값과 전환 규칙, 원문 개인정보 조회 권한은 변경할 수 없습니다.",
      textFields: {
        statusFilter: field("상태 필터 이름"),
        refresh: field("새로고침 버튼"),
        refreshing: field("불러오는 중 문구"),
        empty: field("접수 없음 안내"),
        detailTitle: field("상세 제목"),
        detailDescription: field("개인정보 조회 안내"),
        selectDetail: field("접수 미선택 안내"),
        detailLoading: field("상세 불러오는 중"),
        assigneePlaceholder: field("담당자 입력 안내"),
        save: field("저장 버튼"),
        saving: field("저장 처리 중"),
        retryNotification: field("알림 재시도 버튼"),
        retryRequestEmail: field("견적 요청 완료 메일 재발송 버튼"),
        retryQuoteEmail: field("견적서 발송 메일 재발송 버튼"),
        emailDeliveryTitle: field("고객 메일 발송 현황 제목"),
        emailDeliveryHelp: field("고객 메일 발송 상태 안내"),
        emailDeliveryEmpty: field("메일 발송 기록 없음 안내"),
        emailDeliveryAttemptsSuffix: field("발송 시도 횟수 단위"),
        emailDeliveryAccountLabel: field("메일 아이디 항목"),
        emailDeliveryRecipientLabel: field("실제 수신 주소 항목"),
        emailDeliveryCcLabel: field("참조 주소 항목"),
      },
      itemFields: { title: "상태 표시 이름" },
    },
    auditEvaluationAdmin: {
      name: "감사평가 운영",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      legalWarning:
        "메뉴 ID, 상태 값, API 주소, 평가 계산식과 저장 필드는 변경할 수 없습니다. 운영자에게 보이는 문구와 안전한 선택지 이름만 편집됩니다.",
      textFields: Object.fromEntries(
        [
          ["requiredFieldsTitle", "필수 입력 필드 제목"],
          ["requiredFieldsHelp", "필수 입력 필드 도움말"],
          ["quoteCountColumn", "견적 수 열 이름"],
          ["confirmationColumn", "고객 확인 열 이름"],
          ["reportGeneratedAtColumn", "보고서 생성일 열 이름"],
          ["republishButton", "과거 게시본 재게시 준비 버튼"],
          ["ruleEditorTitle", "산정 규칙 제목"],
          ["ruleTypeLabel", "규칙 유형 라벨"],
          ["ruleFieldLabel", "대상 필드 라벨"],
          ["operatorLabel", "비교 방식 라벨"],
          ["booleanValueLabel", "참·거짓 값 라벨"],
          ["weightedSubcriteriaHelp", "가중 세부기준 도움말"],
          ["subitemNameLabel", "세부기준 이름 라벨"],
          ["subitemWeightLabel", "세부 가중치 라벨"],
          ["addSubitemButton", "세부기준 추가 버튼"],
          ["removeSubitemButton", "세부기준 삭제 버튼"],
          ["rangeBandsHelp", "구간 편집 도움말"],
          ["minimumInclusiveLabel", "구간 최솟값 라벨"],
          ["maximumExclusiveLabel", "구간 최댓값 라벨"],
          ["bandScoreLabel", "구간 점수 라벨"],
          ["addBandButton", "구간 추가 버튼"],
          ["removeBandButton", "구간 삭제 버튼"],
          ["checklistItemsHelp", "체크리스트 도움말"],
          ["checklistItemLabel", "체크 항목 라벨"],
          ["checklistScoreLabel", "체크 항목 점수 라벨"],
          ["checklistRequiredLabel", "필수 체크 항목 라벨"],
          ["addChecklistItemButton", "체크 항목 추가 버튼"],
          ["removeChecklistItemButton", "체크 항목 삭제 버튼"],
          ["conditionTypeLabel", "자동 판정 조건 라벨"],
          ["conditionMinimumLabel", "최소 정수값 라벨"],
          ["conditionItemIdLabel", "제안항목 식별자 라벨"],
          ["validationRequiredFields", "필수 입력 필드 검증 메시지"],
          ["validationServerIssue", "서버 게시 검증 기본 메시지"],
          ["publishWarningTitle", "게시 경고 제목"],
          ["publishWarningDescription", "게시 경고 설명"],
          ["publishWarningConfirmLabel", "게시 경고 확인 문구"],
          ["publishWarningConfirmButton", "경고 확인 게시 버튼"],
          ["retentionSettingsTitle", "보존기간 설정 제목"],
          ["retentionSettingsHelp", "보존기간 설정 도움말"],
          ["sourceDocumentRetentionLabel", "원본 견적서 보존일 라벨"],
          ["sourceDocumentRetentionHelp", "원본 견적서 보존 도움말"],
          ["intermediateRetentionLabel", "중간데이터 보존일 라벨"],
          ["intermediateRetentionHelp", "중간데이터 보존 도움말"],
          ["reportRetentionLabel", "보고서 보존일 라벨"],
          ["reportRetentionHelp", "보고서 보존 도움말"],
          ["expiredAccessRetentionLabel", "만료 접근기록 보존일 라벨"],
          ["expiredAccessRetentionHelp", "만료 접근기록 보존 도움말"],
          ["auditLogRetentionLabel", "감사로그 보존일 라벨"],
          ["auditLogRetentionHelp", "감사로그 보존 도움말"],
          ["automaticRetentionLabel", "자동 만료 처리 라벨"],
          ["retentionPreviewTitle", "삭제 대상 미리보기 제목"],
          ["retentionPreviewHelp", "삭제 대상 미리보기 도움말"],
          ["retentionTargetCountLabel", "삭제 대상 수 라벨"],
          ["sourceDocumentRetentionTarget", "원본 삭제 대상 라벨"],
          ["intermediateRetentionTarget", "중간데이터 삭제 대상 라벨"],
          ["reportRetentionTarget", "보고서 삭제 대상 라벨"],
          ["expiredAccessRetentionTarget", "만료 접근기록 삭제 대상 라벨"],
          ["auditLogRetentionTarget", "감사로그 삭제 대상 라벨"],
          ["retentionRefreshButton", "삭제 대상 새로고침 버튼"],
          ["retentionExecuteButton", "삭제 실행 버튼"],
          ["retentionConfirmTitle", "보존 만료 삭제 확인 제목"],
          ["retentionConfirmDescription", "보존 만료 삭제 확인 설명"],
          ["retentionConfirmCheckbox", "보존 만료 삭제 확인 문구"],
        ].map(([key, label]) => [key, field(label)]),
      ),
      itemFields: {
        title: "메뉴·상태·파일명·산정 규칙·필드 표시 이름",
      },
    },
    points: {
      name: "농협 지갑과 포인트",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      legalWarning:
        "포인트 이벤트 값, 잔액 계산과 조정 요청 항목은 변경할 수 없습니다. 표시 문구만 편집됩니다.",
      textFields: {
        walletListTitle: field("지갑 목록 제목"),
        allTransactions: field("전체 거래 보기 버튼"),
        walletSearchPlaceholder: field("지갑 검색 안내"),
        walletSearchAriaLabel: field("지갑 검색 접근성 이름"),
        walletEmpty: field("등록 지갑 없음"),
        walletFilteredEmpty: field("지갑 검색 결과 없음"),
        selectedDetailTitle: field("선택 농협 상세 제목"),
        selectOrganization: field("농협 미선택 안내"),
        manualAdjustmentTitle: field("수동 조정 제목"),
        adjustmentHelp: field("수동 조정 도움말"),
        adjustmentPlaceholder: field("조정 포인트 입력 예시"),
        reasonPlaceholder: field("조정 사유 입력 안내"),
        reviewAdjustment: field("조정 확인 버튼"),
        recentTransactions: field("최근 거래 제목"),
        transactionEmpty: field("거래 내역 없음"),
      },
      itemFields: { title: "포인트 이벤트 표시 이름" },
    },
    auditLog: {
      name: "운영 작업 기록",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      textFields: {
        title: field("감사 로그 제목"),
        activityColumn: field("활동 열 이름"),
        targetColumn: field("대상 열 이름"),
        actorColumn: field("작업자 열 이름"),
        occurredAtColumn: field("시각 열 이름"),
        empty: field("기록 없음 안내"),
      },
    },
    dialogs: {
      name: "확인·편집 창",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      legalWarning:
        "확인 창 문구는 작업의 의미만 설명합니다. 실제 API 요청과 저장 항목에는 영향을 주지 않습니다.",
      textFields: {
        close: field("닫기 버튼"),
        cancel: field("취소 버튼"),
        save: field("저장 버튼"),
        saving: field("저장 처리 중"),
        processing: field("작업 처리 중"),
        faqEditorTitle: field("FAQ 편집 창 제목"),
        faqEditorDescription: field("FAQ 편집 창 설명"),
        pointConfirmTitle: field("포인트 조정 확인 제목"),
        pointConfirmDescription: field("포인트 조정 확인 설명"),
        passwordDialogTitle: field("비밀번호 재설정 제목"),
        passwordDialogDescription: field("비밀번호 재설정 설명"),
        permissionDialogTitle: field("권한 변경 확인 제목"),
        deleteOperatorDialogTitle: field("운영자 삭제 확인 제목"),
        deleteFaqDialogTitle: field("FAQ 삭제 확인 제목"),
        irreversibleWarning: field("되돌릴 수 없음 안내"),
      },
    },
    testDataManagement: {
      name: "테스트 데이터 관리",
      titleLabel: "관리자 화면 이름",
      descriptionLabel: "화면 설명",
      legalWarning:
        "확인문구 형식, 권한, manifest 검증, 삭제 대상과 보존 대상 판정은 보안상 편집할 수 없습니다. 표시 안내만 변경됩니다.",
      itemFields: {
        title: "단계·상태 표시 이름",
        description: "단계·상태 설명",
      },
    },
  },
  "admin.console": {
    navigation: {
      name: "콘텐츠 관리 메뉴",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      legalWarning:
        "메뉴 ID와 연결되는 화면 전환 값은 변경할 수 없습니다. 표시 이름과 설명만 편집됩니다.",
      textFields: {
        ariaLabel: field("메뉴 접근성 이름"),
      },
      itemFields: {
        title: "메뉴 표시 이름",
        description: "메뉴 짧은 설명",
      },
    },
    shell: {
      name: "관리자 공통 화면",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "영역 설명",
      legalWarning:
        "로그인, 권한 확인, 로그아웃과 이동 주소는 코드로 보호됩니다. 화면 문구만 편집됩니다.",
      textFields: Object.fromEntries(
        [
          ["homeAriaLabel", "관리자 홈 접근성 이름"],
          ["brandMark", "서비스 로고 글자"],
          ["brandName", "서비스 이름"],
          ["brandSubtitle", "관리자 화면 이름"],
          ["operationsLink", "회원·상담 운영 이동 문구"],
          ["testDataManagementLink", "테스트 데이터 관리 이동 문구"],
          ["userFallback", "관리자 이름 기본값"],
          ["userInitialFallback", "관리자 이름 첫 글자 기본값"],
          ["permissionLabel", "관리 권한 표시"],
          ["logout", "로그아웃 버튼"],
          ["breadcrumb", "현재 위치 앞 문구"],
          ["lastChecked", "마지막 확인 문구"],
          ["refresh", "새로고침 버튼"],
          ["refreshing", "새로고침 처리 중"],
          ["noticeCloseAriaLabel", "안내 닫기 접근성 이름"],
          ["recordMissing", "기록 없음 안내"],
          ["activityEmptyDescription", "작업 기록 없음 설명"],
        ].map(([key, label]) => [key, field(label)]),
      ),
    },
    dashboard: {
      name: "콘텐츠 운영 대시보드",
      titleLabel: "화면 제목",
      descriptionLabel: "화면 설명",
      textFields: Object.fromEntries(
        [
          ["summaryAriaLabel", "운영 요약 접근성 이름"],
          ["recentChangesTitle", "최근 수정 제목"],
          ["recentChangesDescription", "최근 수정 설명"],
          ["recentChangesEmpty", "최근 수정 없음"],
          ["recentPublishesTitle", "최근 게시 제목"],
          ["recentPublishesDescription", "최근 게시 설명"],
          ["recentPublishesEmpty", "최근 게시 없음"],
          ["viewAll", "전체 보기 버튼"],
          ["issuesTitle", "검토 항목 제목"],
          ["issuesDescription", "검토 항목 설명"],
          ["issueReview", "검토 항목 확인 버튼"],
          ["noIssuesTitle", "검토 문제 없음 제목"],
          ["noIssuesDescription", "검토 문제 없음 설명"],
        ].map(([key, label]) => [key, field(label)]),
      ),
      itemFields: {
        title: "지표 이름",
        description: "지표 설명",
        value: "건수 단위",
      },
    },
    pages: {
      name: "페이지 관리",
      titleLabel: "화면 제목",
      descriptionLabel: "화면 설명",
      legalWarning:
        "분류 필터 ID와 실제 분류 값, 편집·미리보기·게시 주소는 변경할 수 없습니다.",
      textFields: Object.fromEntries(
        [
          ["searchAriaLabel", "화면 검색 접근성 이름"],
          ["searchPlaceholder", "화면 검색 입력 안내"],
          ["filterAriaLabel", "화면 분류 접근성 이름"],
          ["countSuffix", "화면 개수 뒤 문구"],
          ["emptyTitle", "검색 결과 없음 제목"],
          ["emptyDescription", "검색 결과 없음 설명"],
          ["previewAriaSuffix", "미리보기 접근성 뒤 문구"],
          ["detailsAriaSuffix", "편집 정보 접근성 뒤 문구"],
          ["audienceLabel", "공개 범위 이름"],
          ["modifiedLabel", "최종 수정 이름"],
          ["edit", "편집 버튼"],
          ["preview", "미리보기 버튼"],
          ["publish", "게시 버튼"],
          ["publishAvailableTitle", "게시 가능 도움말"],
          ["publishUnavailableTitle", "게시 불가 도움말"],
        ].map(([key, label]) => [key, field(label)]),
      ),
      itemFields: { title: "분류 필터 표시 이름" },
    },
    commonAreas: {
      name: "공통 영역",
      titleLabel: "화면 제목",
      descriptionLabel: "화면 설명",
      textFields: {
        statusLabel: field("상태 이름"),
        modifiedLabel: field("최종 수정 이름"),
        edit: field("내용 편집 버튼"),
        comingSoon: field("준비 중 버튼"),
      },
    },
    design: {
      name: "디자인 설정",
      titleLabel: "화면 제목",
      descriptionLabel: "화면 설명",
      textFields: {
        calloutTitle: field("안전 안내 제목"),
        calloutDescription: field("안전 안내 설명"),
        change: field("설정 변경 버튼"),
        sampleText: field("글자 크기 보기 예시"),
      },
      itemFields: {
        title: "디자인 항목 이름",
        description: "디자인 항목 설명",
      },
    },
    assets: {
      name: "이미지와 파일",
      titleLabel: "화면 제목",
      descriptionLabel: "화면 설명",
      textFields: Object.fromEntries(
        [
          ["listTitle", "파일 목록 제목"],
          ["listDescription", "파일 목록 설명"],
          ["add", "파일 추가 버튼"],
          ["emptyTitle", "파일 없음 제목"],
          ["emptyDescription", "파일 없음 설명"],
          ["pdfBadge", "PDF 파일 배지"],
          ["imageBadge", "이미지 파일 배지"],
          ["pdfKind", "PDF 파일 종류 이름"],
          ["statusLabel", "상태 이름"],
          ["modifiedLabel", "최종 수정 이름"],
        ].map(([key, label]) => [key, field(label)]),
      ),
    },
    history: {
      name: "수정과 게시 이력",
      titleLabel: "화면 제목",
      descriptionLabel: "화면 설명",
      textFields: {
        listTitle: field("작업 기록 제목"),
        listDescription: field("작업 기록 설명"),
        empty: field("작업 기록 없음 안내"),
      },
    },
    pageInfoDialog: {
      name: "페이지 정보 창",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "창 설명",
      textFields: Object.fromEntries(
        [
          ["eyebrow", "창 상단 작은 문구"],
          ["closeAriaLabel", "창 닫기 접근성 이름"],
          ["addressLabel", "페이지 주소 이름"],
          ["audienceLabel", "보는 사람 이름"],
          ["statusLabel", "게시 상태 이름"],
          ["sectionsTitle", "화면 구성 제목"],
          ["sectionsDescription", "화면 구성 설명"],
          ["sectionCountSuffix", "영역 개수 뒤 문구"],
          ["visible", "표시 중 상태"],
          ["hidden", "숨김 상태"],
          ["itemCountPrefix", "목록 개수 앞 문구"],
          ["itemCountSuffix", "목록 개수 뒤 문구"],
          ["required", "필수 영역 배지"],
          ["advanced", "고급 정보 펼치기"],
          ["draftVersion", "초안 번호 이름"],
          ["publishedVersion", "게시 번호 이름"],
          ["none", "값 없음 안내"],
          ["safetyTitle", "초안 안전 안내 제목"],
          ["safetyDescription", "초안 안전 안내 설명"],
          ["preview", "미리보기 버튼"],
          ["openEditor", "페이지 편집기 버튼"],
        ].map(([key, label]) => [key, field(label)]),
      ),
    },
    publishDialog: {
      name: "게시 확인 창",
      titleLabel: "관리자 목록 이름",
      descriptionLabel: "창 설명",
      legalWarning:
        "실제 게시 대상, API 주소와 버전 확인 값은 변경할 수 없습니다. 확인 문구만 편집됩니다.",
      textFields: {
        titleSuffix: field("게시 확인 제목 뒤 문구"),
        description: field("게시 영향 안내"),
        impactLabel: field("영향받는 화면 이름"),
        cancel: field("취소 버튼"),
        publishing: field("게시 처리 중 버튼"),
        confirm: field("게시 확인 버튼"),
      },
    },
  },
};

const adminOperationsDefaults = CMS_PAGE_DEFAULTS["admin.operations"];
for (const section of adminOperationsDefaults.sections) {
  const presentation =
    CMS_ROUTE_SECTION_PRESENTATION["admin.operations"]?.[section.id];
  if (!presentation) continue;
  presentation.textFields ??= {};
  for (const [key, value] of Object.entries(section.text)) {
    presentation.textFields[key] ??= field(
      `“${value.length > 32 ? `${value.slice(0, 32)}…` : value}” 문구`,
      `${presentation.name}에서 고객과 운영자에게 표시되는 문구입니다.`,
    );
  }
}

export const CMS_ROUTE_MESSAGE_PRESENTATION: Partial<
  Record<CmsPageKey, Record<string, { label: string; help: string }>>
> = {
  "event.auditQuoteEvaluate": {
    disabled: field("서비스 비활성 안내"),
    requestAccepted: field("평가 시작 성공 안내"),
    invalidOrExpiredLink: field("세션 만료 안내"),
    accessDenied: field("평가 접근 거절 안내"),
    temporarilyUnavailable: field("요청 과다·일시 제한 안내"),
    genericError: field("접속 요청 일반 오류"),
  },
  "event.auditQuoteEvaluation": {
    disabled: field("서비스 비활성 안내"),
    denied: field("평가 건 접근 거절 안내"),
    requestAgainLabel: field("이메일 재접속 버튼"),
    uploadPending: field("업로드 정보 로딩 안내"),
    uploadSuccess: field("업로드 성공 안내"),
    unsupportedFileType: field("지원하지 않는 형식 안내"),
    emptyFile: field("빈 파일 안내"),
    fileTooLarge: field("파일 용량 초과 안내"),
    tooManyFiles: field("파일 개수 초과 안내"),
    corruptOrEncrypted: field("손상·암호 PDF 안내"),
    duplicateQuote: field("중복 견적서 안내"),
    wrongCase: field("다른 평가 건 문서 안내"),
    reviewRequired: field("담당자 검토 필요 안내"),
    networkRetry: field("네트워크 자동 재시도 안내"),
    uploadFailed: field("업로드 실패 안내"),
    deleteFailed: field("삭제 실패 안내"),
    accessExpired: field("접근 만료 안내"),
    logoutLabel: field("세션 종료 버튼"),
  },
  "event.auditQuoteEvaluationReview": {
    disabled: field("서비스 비활성 안내"),
    denied: field("평가 건 접근 거절 안내"),
    workspacePending: field("견적정보 로딩 안내"),
    workspaceFailed: field("견적정보 로딩 실패 안내"),
    correctionSaved: field("정정 자동 저장 완료 안내"),
    correctionFailed: field("정정 저장 실패 안내"),
    versionConflict: field("동시 수정 충돌 안내"),
    readinessBlocked: field("최종 확인 조건 미충족 안내"),
    finalCheckRequired: field("최종 확인 동의 필요 안내"),
    confirmationComplete: field("고객 최종 확인 완료 안내"),
    confirmationFailed: field("고객 최종 확인 실패 안내"),
    reportRequestFailed: field("보고서 생성 요청 실패 안내"),
    accessExpired: field("접근 만료 안내"),
    logoutLabel: field("세션 종료 버튼"),
  },
  "event.auditQuoteEvaluationReport": {
    disabled: field("보고서 기능 비활성 안내"),
    denied: field("보고서 접근 거절 안내"),
    notReady: field("보고서 미생성 안내"),
    loading: field("보고서 상태 확인 중 안내"),
    queued: field("보고서 생성 대기 안내"),
    generating: field("보고서 생성 진행 안내"),
    generationFailed: field("보고서 생성 실패 안내"),
    ready: field("보고서 생성 완료 안내"),
    reportActionFailed: field("보고서 작업 실패 안내"),
    downloadPending: field("다운로드 준비 중 안내"),
    logoutLabel: field("세션 종료 버튼"),
  },
  "auth.signup": Object.fromEntries(
    [
      ["submitting", "가입 신청 처리 중"],
      ["success", "가입 신청 접수 완료"],
      ["nameRequired", "이름 미입력"],
      ["phoneRequired", "휴대폰 미입력"],
      ["phoneInvalid", "휴대폰 형식 오류"],
      ["phoneVerificationRequired", "휴대폰 인증 필요"],
      ["phoneCodeRequired", "인증번호 미입력"],
      ["phoneConfirmRequired", "인증 확인 필요"],
      ["phoneReceiveFirst", "인증번호 발송 선행"],
      ["phoneCodeSixDigits", "인증번호 여섯 자리 안내"],
      ["phoneVerificationExpired", "휴대폰 인증 만료"],
      ["phoneVerificationRetry", "휴대폰 인증 재시도"],
      ["phoneAccountLimit", "휴대폰 계정 수 제한"],
      ["phoneCodeInvalid", "인증번호 불일치"],
      ["phoneCodeExpired", "인증번호 만료"],
      ["phoneTooMany", "인증 요청 제한"],
      ["phoneQuota", "문자 발송 한도"],
      ["phoneUnauthorizedDomain", "인증 허용 주소 오류"],
      ["phoneDisabled", "휴대폰 인증 비활성"],
      ["phoneCaptcha", "보안 인증 오류"],
      ["networkError", "네트워크 오류"],
      ["phoneGenericError", "휴대폰 인증 일반 오류"],
      ["emailRequired", "농협 이메일 미입력"],
      ["emailInvalid", "이메일 형식 오류"],
      ["emailCheckRequired", "이메일 중복확인 필요"],
      ["emailDuplicate", "가입된 이메일"],
      ["emailCheckError", "이메일 중복확인 오류"],
      ["passwordRequired", "비밀번호 미입력"],
      ["passwordMin", "비밀번호 최소 조건"],
      ["passwordPolicyError", "비밀번호 보안 정책 오류"],
      ["passwordConfirmRequired", "비밀번호 확인 미입력"],
      ["passwordMismatch", "비밀번호 불일치"],
      ["temporaryActivationInvalid", "임시회원 활성화 링크 오류"],
      ["temporaryActivationFailed", "임시회원 활성화 실패"],
      ["temporaryConversionSuccess", "정회원 전환 완료"],
      ["cooperativeRequired", "소속 농협 미선택"],
      ["positionRequired", "직책 미입력"],
      ["dutyRequired", "담당업무 미선택"],
      ["consentsRequired", "필수 동의 누락"],
      ["businessCardType", "명함 파일 형식 오류"],
      ["businessCardSize", "명함 파일 용량 오류"],
      ["missingFields", "필수 입력 누락"],
      ["invalidToken", "인증 정보 만료"],
      ["emailMismatch", "인증 이메일 불일치"],
      ["invalidCooperative", "소속 농협 정보 오류"],
      ["invalidPhoneVerification", "휴대폰 인증 정보 불일치"],
      ["permissionError", "가입 정보 저장 권한 오류"],
      ["genericError", "회원가입 일반 오류"],
    ].map(([key, label]) => [key, field(`${label} 안내`)]),
  ),
  "auth.login": PORTAL_LOGIN_MESSAGE_PRESENTATION,
  "auth.partnerLogin": PORTAL_LOGIN_MESSAGE_PRESENTATION,
  "auth.adminLogin": PORTAL_LOGIN_MESSAGE_PRESENTATION,
  "auth.portalAccessDenied": {
    logoutFailed: field("로그아웃 실패 안내"),
  },
  "public.consult": {
    submitting: field("상담 등록 처리 중 안내"),
    subjectRequired: field("제목 미입력 안내"),
    messageRequired: field("내용 미입력 안내"),
    authRequired: field("로그인 필요 안내"),
    organizationRequired: field("소속 농협 정보 없음 안내"),
    invalidAttachment: field("첨부파일 형식 오류 안내"),
    tooManyAttachments: field("첨부 개수 초과 안내"),
    imageOnly: field("이미지 파일 전용 안내"),
    imageTooLarge: field("이미지 용량 초과 안내"),
    genericError: field("상담 등록 일반 오류 안내"),
  },
  "public.inquiries": {
    loading: field("문의 목록 불러오는 중 안내"),
    empty: field("검색 결과 없음 안내"),
    denied: field("열람 권한 없음 안내"),
    genericError: field("문의 목록 오류 안내"),
  },
  "public.faq": {
    loading: field("FAQ 불러오는 중 안내"),
    empty: field("검색 결과 없음 안내"),
    fallback: field("기본 안내 표시 문구"),
  },
  "partner.portal": {
    denied: field("협력 전문가 권한 없음 안내"),
    evaluationCriteriaChanged: field("평가기준 변경 안내"),
    evaluationRequired: field("필수 평가정보 누락 안내"),
    evaluationInvalid: field("평가정보 형식 오류 안내"),
    evaluationRegistrationFailed: field("감사평가 견적 등록 실패 안내"),
    evaluationFallbackWarning: field("게시 평가기준 없음 안내"),
    quoteSaveFailed: field("견적 저장 실패 안내"),
    quoteAlreadyFinalized: field("이미 최종확정된 견적 안내"),
    quoteAlreadyFinalizedHint: field("최종확정 견적 입력 잠금 안내"),
    quoteAlreadyFinalizedPreview: field("최종확정 견적 PDF 미리보기 안내"),
    quoteAlreadyFinalizedSendDisabled: field("최종확정 발송 버튼 비활성 문구"),
    quoteMutationLocked: field("견적 저장 불가 상태 안내"),
    quoteRequestClosed: field("견적 요청 마감 안내"),
    quoteViewFinalizedButton: field("발송 견적서 미리보기 버튼"),
    quoteSentInboxHelp: field("보낸 견적함 안내"),
    quoteSentInboxEmpty: field("보낸 견적 없음 안내"),
    quoteReviseButton: field("견적 개정·재발송 버튼"),
    quoteReviseLoading: field("견적 개정 준비 중 안내"),
    quoteReviseStarted: field("견적 개정 시작 안내"),
    quoteReviseFailed: field("견적 개정 시작 실패 안내"),
    quoteReviseNotFinalized: field("미발송 견적 개정 불가 안내"),
    quoteDraftSaved: field("견적 초안 저장 성공 안내"),
    quoteFinalized: field("견적 확정·발송 안내"),
    quoteRequiredSummary: field("견적 필수정보 누락 안내"),
    quoteDraftIncomplete: field("미완성 견적 초안 저장 안내"),
    quotePreviewButton: field("견적 미리보기 버튼"),
    quotePreviewLoading: field("견적 미리보기 생성 중 안내"),
    quotePreviewEyebrow: field("견적 미리보기 상단 안내"),
    quotePreviewTitle: field("견적 미리보기 제목"),
    quotePreviewRecipient: field("견적 미리보기 수신자 라벨"),
    quotePreviewHelp: field("견적 미리보기 발송 전 안내"),
    quotePreviewEdit: field("견적 입력 수정 버튼"),
    quoteSendConfirm: field("견적 최종확정·발송 버튼"),
    quoteSending: field("견적 발송 처리 중 안내"),
    quoteDeliveryPendingHelp: field("메일 설정 전 견적함 등록·재시도 안내"),
    quoteDeliveryNotConfigured: field("메일 발송 설정 누락 안내"),
    quoteDeliveryFailed: field("메일 발송 실패·재시도 안내"),
    quoteNetworkFailed: field("견적 네트워크 오류 안내"),
    quoteLogoUploadFailed: field("로고 업로드 실패 안내"),
    quoteLogoUploadSuccess: field("로고 업로드 성공 안내"),
    quoteSealUploadFailed: field("직인 업로드 실패 안내"),
    quoteSealUploadSuccess: field("직인 업로드 성공 안내"),
    quoteSupplierProfileInvalid: field("공급자 정보 검증 오류 안내"),
    quoteLineItemsInvalid: field("견적 항목 검증 오류 안내"),
    quoteDraftSaving: field("견적 초안 저장 중 안내"),
    quoteDraftSaveButton: field("견적 초안 저장 버튼"),
    quoteAssignmentsEmpty: field("배정된 견적 없음 안내"),
  },
  "partner.apply": {
    submitLabel: field("제휴 신청 버튼"),
    submitting: field("제휴 신청 처리 중 안내"),
    success: field("제휴 신청 성공 안내"),
    invalid: field("제휴 신청 검증 오류 안내"),
  },
  "member.mypage": {
    loading: field("마이페이지 불러오는 중 안내"),
    loadingDescription: field("로그인과 지갑 확인 중 설명"),
    loginRequired: field("로그인 필요 안내"),
    loadFailed: field("마이페이지 불러오기 실패 제목"),
    retryDescription: field("다시 시도 도움말"),
    retryLabel: field("다시 시도 버튼"),
    otherLoginLabel: field("다른 계정 로그인 버튼"),
    refreshed: field("새로고침 완료 알림"),
    refreshFailed: field("새로고침 실패 알림"),
    logoutFailed: field("로그아웃 실패 알림"),
    consentLoginRequired: field("동의 변경 로그인 필요 알림"),
    consentSaved: field("수신 동의 저장 완료 알림"),
    consentSaveFailed: field("수신 동의 저장 실패 알림"),
    temporaryConversionSuccess: field("정회원 전환 완료 알림"),
    emptyInquiries: field("상담 내역 없음 안내"),
    emptyPoints: field("포인트 내역 없음 안내"),
    genericError: field("마이페이지 오류 안내"),
    relativeNow: field("방금 전 시간 표시"),
    relativeMinutes: field("분 단위 이전 시간 표시"),
    relativeHours: field("시간 단위 이전 시간 표시"),
    relativeDays: field("일 단위 이전 시간 표시"),
  },
  "member.quotes": {
    ...Object.fromEntries(
      [
        ["loading", "견적함 불러오는 중"],
        ["denied", "견적함 로그인 필요"],
        ["loadFailed", "견적함 불러오기 실패"],
        ["empty", "견적서 없음"],
        ["downloadLabel", "PDF 다운로드 버튼"],
        ["downloadFailed", "PDF 다운로드 실패"],
        ["totalLabel", "합계 항목"],
        ["statusLabel", "상태 항목"],
        ["versionLabel", "버전 항목"],
        ["evaluationScoreLabel", "정량 평가점수 항목"],
        ["scoreSuffix", "점수 단위"],
        ["currencySuffix", "금액 단위"],
        ["resubmissionRequired", "재제출 필요 안내"],
        ["resubmissionMissingPrefix", "누락 항목 앞 문구"],
        ["evaluationDetailsSuffix", "평가 상세 뒤 문구"],
        ["statusDraft", "작성 중 상태"],
        ["statusFinalized", "확정 상태"],
        ["statusDelivered", "발송 완료 상태"],
        ["statusDeliveryPending", "발송 대기 상태"],
        ["statusVoid", "취소 상태"],
        ["comparisonSectionTitle", "견적 비교 영역 제목"],
        ["comparisonSectionHelp", "견적 비교 영역 안내"],
        ["comparisonOpenLabel", "견적 비교 보기 버튼"],
        ["comparisonOpeningLabel", "비교 화면 여는 중 문구"],
        ["comparisonReportReadyLabel", "비교 보고서 보기 버튼"],
        ["comparisonNeedMoreQuotes", "비교 견적 부족 안내"],
        ["comparisonUnavailable", "비교 화면 이용 불가 안내"],
        ["comparisonFeatureDisabled", "비교 기능 비활성 안내"],
        ["comparisonQuoteCountSuffix", "수신 견적 수 단위"],
        ["credentialsTitle", "공급자 기본정보 제목"],
        ["evaluationFactsTitle", "제휴사 평가정보 제목"],
        ["evaluationFactsHelp", "제휴사 평가정보 안내"],
        ["businessNumberLabel", "사업자등록번호 항목"],
        ["addressLabel", "사업장 주소 항목"],
        ["supplierContactLabel", "견적 담당자 항목"],
        ["contactLabel", "연락처 항목"],
        ["engagementPartnerLabel", "담당회계사 항목"],
        ["proposerTypeLabel", "제안 주체 항목"],
        ["cpaCountLabel", "공인회계사 인원 수 항목"],
        ["revenueLabel", "회계법인 매출액 항목"],
        ["localAuditCountLabel", "2025년 지역농협 감사실적 항목"],
        ["recentAuditCountLabel", "최근 농협 감사건수 항목"],
        ["auditedTypesLabel", "감사 수행 농협 유형 항목"],
        ["taxExperienceLabel", "세무대리 경험 항목"],
        ["subsidyExperienceLabel", "보조금 정산 경험 항목"],
        ["yesLabel", "해당 있음 표시"],
        ["noLabel", "해당 없음 표시"],
        ["missingValue", "미등록 표시"],
        ["peopleSuffix", "인원 단위"],
        ["countSuffix", "건수 단위"],
        ["requestInfoTitle", "견적 신청 정보 제목"],
        ["requestInfoHelp", "견적 신청 정보 안내"],
        ["requestNameLabel", "견적 신청 이름 항목"],
        ["requestPhoneLabel", "견적 신청 전화번호 항목"],
        ["requestEmailLabel", "견적 신청 이메일 항목"],
        ["requestCooperativeLabel", "견적 신청 농협명 항목"],
      ].map(([key, label]) => [key, field(label)]),
    ),
  },
  "member.quoteDetail": {
    ...Object.fromEntries(
      [
        ["loading", "견적 상세 불러오는 중"],
        ["denied", "견적 상세 로그인 필요"],
        ["loadFailed", "견적 상세 불러오기 실패"],
        ["empty", "견적 상세 없음"],
        ["downloadLabel", "PDF 다운로드 버튼"],
        ["downloadFailed", "PDF 다운로드 실패"],
        ["totalLabel", "합계 항목"],
        ["statusLabel", "상태 항목"],
        ["versionLabel", "버전 항목"],
        ["evaluationScoreLabel", "정량 평가점수 항목"],
        ["scoreSuffix", "점수 단위"],
        ["currencySuffix", "금액 단위"],
        ["resubmissionRequired", "재제출 필요 안내"],
        ["resubmissionMissingPrefix", "누락 항목 앞 문구"],
        ["evaluationDetailsSuffix", "평가 상세 뒤 문구"],
        ["statusDraft", "작성 중 상태"],
        ["statusFinalized", "확정 상태"],
        ["statusDelivered", "발송 완료 상태"],
        ["statusDeliveryPending", "발송 대기 상태"],
        ["statusVoid", "취소 상태"],
        ["credentialsTitle", "공급자 기본정보 제목"],
        ["evaluationFactsTitle", "제휴사 평가정보 제목"],
        ["evaluationFactsHelp", "제휴사 평가정보 안내"],
        ["businessNumberLabel", "사업자등록번호 항목"],
        ["addressLabel", "사업장 주소 항목"],
        ["supplierContactLabel", "견적 담당자 항목"],
        ["contactLabel", "연락처 항목"],
        ["engagementPartnerLabel", "담당회계사 항목"],
        ["proposerTypeLabel", "제안 주체 항목"],
        ["cpaCountLabel", "공인회계사 인원 수 항목"],
        ["revenueLabel", "회계법인 매출액 항목"],
        ["localAuditCountLabel", "2025년 지역농협 감사실적 항목"],
        ["recentAuditCountLabel", "최근 농협 감사건수 항목"],
        ["auditedTypesLabel", "감사 수행 농협 유형 항목"],
        ["taxExperienceLabel", "세무대리 경험 항목"],
        ["subsidyExperienceLabel", "보조금 정산 경험 항목"],
        ["yesLabel", "해당 있음 표시"],
        ["noLabel", "해당 없음 표시"],
        ["missingValue", "미등록 표시"],
        ["peopleSuffix", "인원 단위"],
        ["countSuffix", "건수 단위"],
        ["requestInfoTitle", "견적 신청 정보 제목"],
        ["requestInfoHelp", "견적 신청 정보 안내"],
        ["requestNameLabel", "견적 신청 이름 항목"],
        ["requestPhoneLabel", "견적 신청 전화번호 항목"],
        ["requestEmailLabel", "견적 신청 이메일 항목"],
        ["requestCooperativeLabel", "견적 신청 농협명 항목"],
      ].map(([key, label]) => [key, field(label)]),
    ),
  },
  "member.requestDetail": {
    loading: field("문의 상세 불러오는 중 안내"),
    loadFailed: field("문의 상세 불러오기 실패 제목"),
    notFound: field("문의 없음·권한 없음 안내"),
    notFoundDescription: field("문의 접근 권한 확인 설명"),
    insufficientPoints: field("포인트 부족 안내"),
    viewFailed: field("답변 열람 실패 안내"),
    ratingSaved: field("답변 평가 저장 완료 안내"),
    ratingRequiresView: field("평가 전 답변 열람 안내"),
    ratingFailed: field("답변 평가 저장 실패 안내"),
    completeRequiresView: field("완료 전 답변 열람 안내"),
    completeRequiresRating: field("완료 전 답변 평가 안내"),
    completeSuccess: field("문의 완료 처리 안내"),
    completeFailed: field("문의 완료 처리 실패 안내"),
    genericError: field("문의 상세 오류 안내"),
  },
  "admin.operations": Object.fromEntries(
    [
      ["loading", "운영 화면 불러오는 중"],
      ["loadingDescription", "인증과 권한 확인 중"],
      ["denied", "관리자 권한 없음"],
      ["deniedDescription", "관리자 접근 제한"],
      ["loginAgain", "관리자 계정 다시 로그인"],
      ["empty", "운영 자료 없음"],
      ["genericError", "운영 화면 오류"],
      ["retry", "다시 시도"],
      ["saved", "저장 완료"],
      ["authRequired", "로그인 필요"],
      ["refreshed", "새로고침 완료"],
      ["refreshFailed", "새로고침 실패"],
      ["faqLoadFailed", "FAQ 불러오기 실패"],
      ["faqSaved", "FAQ 등록 완료"],
      ["faqUpdated", "FAQ 수정 완료"],
      ["faqSaveFailed", "FAQ 저장 실패"],
      ["faqDeleted", "FAQ 삭제 완료"],
      ["faqDeleteFailed", "FAQ 삭제 실패"],
      ["answerSaved", "답변 저장 완료"],
      ["answerSaveFailed", "답변 저장 실패"],
      ["assigneeRequired", "답변 담당자 누락"],
      ["pointFieldsRequired", "포인트 조정 입력 누락"],
      ["negativeBalance", "포인트 잔액 부족"],
      ["pointAdjusted", "포인트 조정 완료"],
      ["pointAdjustmentFailed", "포인트 조정 실패"],
      ["memberStatusFailed", "회원 상태 변경 실패"],
      ["operatorSaveFailed", "운영자 저장 실패"],
      ["operatorPermissionFailed", "운영자 권한 변경 실패"],
      ["passwordTooShort", "비밀번호 길이 안내"],
      ["passwordResetFailed", "비밀번호 재설정 실패"],
      ["operatorDeleteFailed", "운영자 삭제 실패"],
      ["auditQuoteListFailed", "견적 접수 목록 오류"],
      ["auditQuoteDetailFailed", "견적 접수 상세 오류"],
      ["auditQuoteSaved", "견적 접수 저장 완료"],
      ["auditQuoteConflict", "견적 접수 동시 수정"],
      ["auditQuoteInvalidTransition", "견적 상태 변경 제한"],
      ["auditQuoteSaveFailed", "견적 접수 저장 실패"],
      ["auditQuoteNotifySuccess", "견적 알림 재시도 결과"],
      ["auditQuoteNotifyFailed", "견적 알림 재시도 실패"],
      ["auditQuoteRequestEmailSuccess", "견적 요청 완료 메일 재발송 완료"],
      ["auditQuoteRequestEmailSuccessWithPassword", "임시 비밀번호 포함 재발송 완료"],
      ["auditQuoteRequestEmailFailed", "견적 요청 완료 메일 재발송 실패"],
      ["auditQuoteDeliveryEmailSuccess", "견적서 발송 메일 재발송 완료"],
      ["auditQuoteDeliveryEmailNone", "재발송할 견적서 없음"],
      ["auditQuoteDeliveryEmailFailed", "견적서 발송 메일 재발송 실패"],
    ].map(([key, label]) => [key, field(`${label} 안내`)]),
  ),
  "admin.console": Object.fromEntries(
    [
      ["loading", "콘텐츠 관리자 불러오는 중"],
      ["loadingDescription", "콘텐츠 상태 불러오는 중 설명"],
      ["denied", "관리자 권한 없음"],
      ["deniedDescription", "관리자 접근 제한 설명"],
      ["loginAgain", "다시 로그인 버튼"],
      ["genericError", "콘텐츠 관리자 오류"],
      ["genericErrorDescription", "콘텐츠 관리자 오류 설명"],
      ["retry", "다시 불러오기 버튼"],
      ["refreshed", "새로고침 완료"],
      ["refreshFailed", "새로고침 실패"],
      ["publishSuccessSuffix", "게시 완료 뒤 문구"],
      ["publishConflict", "동시 수정 충돌"],
      ["publishFailed", "게시 실패"],
    ].map(([key, label]) => [key, field(`${label} 안내`)]),
  ),
};

CMS_ROUTE_MESSAGE_PRESENTATION["admin.operations"] ??= {};
for (const [key, value] of Object.entries(adminOperationsDefaults.messages)) {
  CMS_ROUTE_MESSAGE_PRESENTATION["admin.operations"]![key] ??= field(
    `“${value.length > 32 ? `${value.slice(0, 32)}…` : value}” 안내`,
    "운영 작업의 상태, 완료 또는 오류 상황에 표시되는 안내입니다.",
  );
}
